### ISSUE TITLE
Crashes when launched

### ISSUE THREAD

**Issue by MaticBabnik** [ImpactDevelopment/ImpactIssues#1181]
**Describe the bug**

**To Reproduce**
1. Use titan launcher (cracked)
2. Click on 'Play'

**Expected behavior**
Impact launches.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[15:12:56] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[15:12:56] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[15:12:56] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[15:12:56] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[15:12:56] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[15:12:56] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[15:12:56] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[15:12:56] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more

```

</details>

**Comment by ScanmanTM** [comment]
Do you have 1.12.2 installed?

**Comment by gamingelaphant** [comment]
I have this issue also with the regular client

**Comment by plungoci** [comment]
I got same issue, any suggestions ?

**Comment by LeafHacker** [comment]
LaunchWrapper can't find Minecraft. You probably haven't run it before.
