### ISSUE TITLE
crash on starting

### ISSUE THREAD

**Issue by syrianrue** [ImpactDevelopment/ImpactIssues#1192]
**To Reproduce**
start normal default launcher 1.6.84j in Debian linux . click [Play] try to load 1.13.2 impact 4.6 - then it crashes with error...

OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[23:49:40] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 43723
	at java.lang.String.substring(String.java:1963)
	at clientapi.load.ClientTweaker.<clinit>(ClientTweaker.java)
	... 4 more

**Comment by 0-x-2-2** [comment]
just openjdk things

**Comment by SuperOP535** [comment]
lol debian

**Comment by 0-x-2-2** [comment]
>not using debian

pleb

**Comment by syrianrue** [comment]
how helpful, on the issues page of github. thank you for solving all the problems

**Comment by syrianrue** [comment]
> > not using debian
> 
> pleb



> just openjdk things

i thought that could be one of the issues. you think i should try with the official jdk

**Comment by syrianrue** [comment]
> lol debian

how helpful, on the issues page. thank you for solving all the problems

**Comment by dominikaaaa** [comment]
Can't reproduce.
