### ISSUE TITLE
Crash when joining a world

### ISSUE THREAD

**Issue by spookydascary24** [ImpactDevelopment/ImpactIssues#1368]
**Describe the bug**
Tried joining a world in Minecraft Vanilla, no mods or OptiFine or anything else, only Baritone and Impact. Worked for some minutes but then it crashed. Tried joining again but now it crashes instantly.

**To Reproduce**
1. Start Minecraft
2. Join server
3. Instant Crash

**Expected behavior**
I expected to join the server and be able to play on it using Impact and Baritone

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[20:27:46] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[20:27:46] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[20:27:46] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[20:27:46] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[20:27:46] [main/INFO]: Injecting into ClassLoader
[20:27:46] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 

Source=file:/C:/Users/User/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-

SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[20:27:46] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. 

Proceeding without FML support.
[20:27:46] [main/INFO]: Initialized Mixin bootstrap
[20:27:46] [main/INFO]: Setup Mixin Environment
[20:27:46] [main/INFO]: Registered Bytecode Transformes
[20:27:46] [main/INFO]: Compatibility level set to JAVA_8
[20:27:46] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[20:27:46] [main/INFO]: Loaded Mixin Configurations
[20:27:46] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[20:27:46] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[20:27:46] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:27:46] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinBlock, name: clientapi.load.mixin.MixinBlock
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinEntityLivingBase, name: clientapi.load.mixin.MixinEntityLivingBase
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinEntityPlayerSP, name: clientapi.load.mixin.MixinEntityPlayerSP
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinGuiBossOverlay, name: clientapi.load.mixin.MixinGuiBossOverlay
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinGuiIngame, name: clientapi.load.mixin.MixinGuiIngame
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinGuiSpectator, name: clientapi.load.mixin.MixinGuiSpectator
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinLayerArmorBase, name: clientapi.load.mixin.MixinLayerArmorBase
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinNetHandlerLoginClient, name: clientapi.load.mixin.MixinNetHandlerLoginClient
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinNetHandlerPlayClient, name: clientapi.load.mixin.MixinNetHandlerPlayClient
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinRender, name: clientapi.load.mixin.MixinRender
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinRenderItem, name: clientapi.load.mixin.MixinRenderItem
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinRenderManager, name: clientapi.load.mixin.MixinRenderManager
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
[20:27:47] [main/WARN]: Error loading class: Config (java.lang.ClassNotFoundException: The specified class 

'Config' was not found)
[20:27:47] [main/WARN]: @Mixin target Config was not found mixins.impact.json:optifine.MixinConfig
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinAnvilChunkLoader, name: baritone.launch.mixins.MixinAnvilChunkLoader
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinBlockPos, name: baritone.launch.mixins.MixinBlockPos
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinChunkProviderClient, name: baritone.launch.mixins.MixinChunkProviderClient
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinChunkProviderServer, name: baritone.launch.mixins.MixinChunkProviderServer
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinChunkRenderContainer, name: baritone.launch.mixins.MixinChunkRenderContainer
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinChunkRenderWorker, name: baritone.launch.mixins.MixinChunkRenderWorker
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinEntityLivingBase, name: baritone.launch.mixins.MixinEntityLivingBase
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinEntityPlayerSP, name: baritone.launch.mixins.MixinEntityPlayerSP
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinEntityRenderer, name: baritone.launch.mixins.MixinEntityRenderer
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinNetHandlerPlayClient, name: baritone.launch.mixins.MixinNetHandlerPlayClient
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinRenderChunk, name: baritone.launch.mixins.MixinRenderChunk
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinRenderList, name: baritone.launch.mixins.MixinRenderList
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinVboRenderList, name: baritone.launch.mixins.MixinVboRenderList
[20:27:47] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading 

mixins.baritone.json:MixinWorldClient, name: baritone.launch.mixins.MixinWorldClient
[20:27:48] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:27:49] [main/INFO]: Setting user: MyMinecraftAccount
[20:27:54] [main/WARN]: Skipping bad option: lastServer:
[20:27:54] [main/INFO]: LWJGL Version: 2.9.4
[20:28:06] [main/INFO]: Reloading ResourceManager: Default
[20:28:09] [Sound Library Loader/INFO]: Starting up SoundSystem...
[20:28:09] [Thread-3/INFO]: Initializing LWJGL OpenAL
[20:28:09] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:28:19] [Thread-3/INFO]: OpenAL initialized.
[20:28:19] [Sound Library Loader/INFO]: Sound engine started
[20:28:24] [main/INFO]: Created: 1024x512 textures-atlas
[20:28:31] [main/INFO]: Narrator library for x64 successfully loaded
[20:28:37] [main/INFO]: [STDOUT]: Baritone settings file not found, resetting.
[20:28:46] [main/INFO]: Loading Fonts
[20:28:57] [main/INFO]: Checking for Updates
[20:28:58] [main/INFO]: Loading Users
[20:29:01] [main/INFO]: [STDERR]: clientapi.util.Z: ERROR: 0:3: 'mat4' : syntax error syntax error


[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.H.w(H.java:5)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.A.e(A.java:2)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.x.f(x.java:8)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.e5.<init>(e5.java:9)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.eE.<init>(eE.java:3)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.eP.<init>(eP.java:9)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.c6.<init>(c6.java:21)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.f.s(f.java:18)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.Impact.r(Impact.java:13)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.aj.r(aj.java:11)
[20:29:01] [main/INFO]: [STDERR]: 	at bib.handler$init$zzl000(SourceFile:3138)
[20:29:01] [main/INFO]: [STDERR]: 	at bib.aq(SourceFile:583)
[20:29:01] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[20:29:01] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[20:29:01] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:29:01] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke

(NativeMethodAccessorImpl.java:62)
[20:29:01] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke

(DelegatingMethodAccessorImpl.java:43)
[20:29:01] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:29:01] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:29:01] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:29:01] [main/INFO]: [STDERR]: clientapi.util.Z: Cannot attach a shader to program if shader isn't generated!
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.A.p(A.java:3)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.B.lambda$nativeGen$0(B.java:7)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.B$$Lambda$1316/881140722.accept(Unknown Source)
[20:29:01] [main/INFO]: [STDERR]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.B.e(B.java:19)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.util.x.f(x.java:8)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.eP.<init>(eP.java:3)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.c6.<init>(c6.java:21)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.f.s(f.java:18)
[20:29:01] [main/INFO]: [STDERR]: 	at me.zero.clarinet.Impact.r(Impact.java:13)
[20:29:01] [main/INFO]: [STDERR]: 	at clientapi.aj.r(aj.java:11)
[20:29:01] [main/INFO]: [STDERR]: 	at bib.handler$init$zzl000(SourceFile:3138)
[20:29:01] [main/INFO]: [STDERR]: 	at bib.aq(SourceFile:583)
[20:29:01] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[20:29:01] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[20:29:01] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:29:01] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke

(NativeMethodAccessorImpl.java:62)
[20:29:01] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke

(DelegatingMethodAccessorImpl.java:43)
[20:29:01] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:29:01] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:29:01] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:29:04] [main/INFO]: Initialized 115 mods!
[20:29:05] [main/FATAL]: Unable to load spam config file: Spam config file is in invalid format
[20:30:40] [main/INFO]: Connecting to constantiam.org, 25565
[20:30:46] [main/INFO]: [STDOUT]: Baritone world data dir: C:\Users\User\AppData\Roaming\.minecraft

\baritone\constantiam.org\DIM0
[20:30:46] [main/INFO]: [STDOUT]: Cached world directory: C:\Users\User\AppData\Roaming\.minecraft

\baritone\constantiam.org\DIM0\cache
[20:30:46] [main/INFO]: [STDOUT]: Would save waypoints to C:\Users\User\AppData\Roaming\.minecraft

\baritone\constantiam.org\DIM0\waypoints
[20:30:46] [main/INFO]: [CHAT]                                      
[20:30:46] [main/INFO]: [CHAT] Thank you Constantiam, here's to a wonderful year! Love, Nyroc_
[20:30:46] [main/INFO]: [CHAT] MyMinecraftAccount joined the game
[20:30:47] [pool-5-thread-1/INFO]: [STDOUT]: Loading region 172,4 from disk C:\Users\User\AppData\Roaming

\.minecraft\baritone\constantiam.org\DIM0\cache
[20:30:47] [pool-5-thread-1/INFO]: [STDOUT]: Loaded region successfully in 153ms
[20:30:47] [pool-5-thread-1/INFO]: [STDOUT]: Loading region 172,5 from disk C:\Users\User\AppData\Roaming

\.minecraft\baritone\constantiam.org\DIM0\cache
[20:30:47] [pool-5-thread-1/INFO]: [STDOUT]: Loaded region successfully in 187ms
[20:30:48] [main/INFO]: [CHAT] The__Camera joined the game
[20:30:48] [main/INFO]: Loaded 328 advancements
[20:30:48] [main/INFO]: [CHAT] unrar joined the game
[20:30:48] [main/INFO]: [CHAT] <joshua047> just gonna go ahead and say, thats a really shit idea
[20:30:49] [main/INFO]: [CHAT] unrar left the game
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2
- Using Optifine? No 
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 8.1 64Bit

</details>

**Additional context**

What I tried to fix it is:

Delete Impact folder from .minecraft
Delete Impact from Versions and reinstall
Delete .minecraft and reinstall Minecraft
Restart PC (I was desperate)

**Comment by dominikaaaa** [comment]
Can't reproduce, closed due to inactivity.
