### ISSUE TITLE
[1.14] Alt menu crash

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactIssues#1562]
**Describe the bug**
When clicking the alt menu at the title screen, minecraft will crash.

**To Reproduce**
1. Go to 'alts'
2. Crash

**Expected behavior**
Able to use the alts menu.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 18/08/19 10:14
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at dsz.a(SourceFile:488)
	at dsz.b(SourceFile:451)
	at dsz.a(SourceFile:28)
	at dsb.a(SourceFile:64)
	at dsz.a(SourceFile:179)
	at dwn.a(SourceFile:67)
	at dwn.a(SourceFile:34)
	at dsa.a(SourceFile:385)
	at net.impactclient.5h.render(Unknown Source)
	at dnc.a(SourceFile:686)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dsz.a(SourceFile:488)
	at dsz.b(SourceFile:451)
	at dsz.a(SourceFile:28)
	at dsb.a(SourceFile:64)
	at dsz.a(SourceFile:179)
	at dwn.a(SourceFile:67)
	at dwn.a(SourceFile:34)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.impactclient.85)
	Entity ID: 2
	Entity Name: [ALT EMAIL]
	Entity's Exact location: 8.50, 65.00, 8.50
	Entity's Block location: World: (8,65,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: dwn@687dc7e6
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 4.02
Stacktrace:
	at dsa.a(SourceFile:385)
	at net.impactclient.5h.render(Unknown Source)

-- Screen render details --
Details:
	Screen name: net.impactclient.5h
	Mouse location: Scaled: (469, 291). Absolute: (938.000000, 583.000000)
	Screen size: Scaled: (960, 514). Absolute: (1920, 1027). Scale factor of 2.000000
Stacktrace:
	at dnc.a(SourceFile:686)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1395276520 bytes (1330 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.0-20190817-nightly
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4 20190817
- Using Optifine? No
- Enabled mods: https://i.imgur.com/anOslYN.png
- Operating System: Windows 10 64bit

</details>

**Comment by LeafHacker** [comment]
Strange, alts menu was working fine for me

**Comment by mikroskeem** [comment]
Can reproduce when there are multiple alts in the menu. I also use OptiFine & OS X.

Does not matter where you open the menu - in game or in main screen, clicking on second/third/next entry crashes the client. If you have single alt, then it works fine.

```
[15:05:22] [main/INFO]: [OptiFine] *** Reloading custom textures ***
[15:06:11] [main/FATAL]: Reported exception thrown!
m: Rendering screen
    at dnc.a(GameRenderer.java:919) ~[dnc.class:?]
    at cyc.e(SourceFile:954) ~[cyc.class:?]
    at cyc.b(SourceFile:410) [cyc.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:155) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_212]
    at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_212]
    at net.impactclient.5h.render(Unknown Source) ~[5h.class:?]
    at dnc.a(GameRenderer.java:901) ~[dnc.class:?]
    ... 9 more
```

**Comment by leijurv** [comment]
Fixed for today's nightly
