### ISSUE TITLE
[1.14] Crashing when connecting to certain server

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactIssues#1563]
**Describe the bug**
When connecting to mineplex minecraft will crash.

**To Reproduce**
1. Connect to mineplex
4. Crash

**Expected behavior**
Not to crash.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 18/08/19 10:37
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.impactclient.0Ys.0(Unknown Source)
	at net.impactclient.2j.0(Unknown Source)
	at net.impactclient.2j$$Lambda$2749/570508088.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.2j.0(Unknown Source)
	at net.impactclient.2j$$Lambda$1965/1206034776.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1758/2010498246.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.8C.post(Unknown Source)
	at dnc.handler$updateCameraAndRender$zzk000(SourceFile:1374)
	at dnc.a(SourceFile:639)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.0Ys.0(Unknown Source)
	at net.impactclient.2j.0(Unknown Source)
	at net.impactclient.2j$$Lambda$2749/570508088.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.2j.0(Unknown Source)
	at net.impactclient.2j$$Lambda$1965/1206034776.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1758/2010498246.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.8C.post(Unknown Source)
	at dnc.handler$updateCameraAndRender$zzk000(SourceFile:1374)

-- Affected level --
Details:
	All players: 14 total; [dmp['UseCodeKeem'/928680350, l='MpServer', x=0.50, y=72.77, z=0.50], dmq['SuperLuna0906'/928596991, l='MpServer', x=2.66, y=71.50, z=7.47], dmq['Jesko101'/928649296, l='MpServer', x=1.75, y=72.00, z=3.38], dmq['HKMichael0916'/924350113, l='MpServer', x=2.53, y=165.00, z=2.28], dmq['Diorex'/928066080, l='MpServer', x=20.25, y=72.00, z=21.28], dmq['Badblock6'/928634927, l='MpServer', x=19.88, y=72.00, z=17.06], dmq['WawaPlays'/928584537, l='MpServer', x=6.75, y=71.00, z=25.53], dmq['copprr'/927053064, l='MpServer', x=0.47, y=71.00, z=30.50], dmq['goldenslayer765'/928614506, l='MpServer', x=0.47, y=71.00, z=30.97], dmq['emil101007'/928482552, l='MpServer', x=-10.53, y=71.00, z=30.97], dmq['killermichi'/928612005, l='MpServer', x=-4.97, y=72.00, z=4.56], dmq['Watchingyou1998'/928017249, l='MpServer', x=0.09, y=72.00, z=-6.25], dmq['TaikaT0nttu'/928607107, l='MpServer', x=2.63, y=72.00, z=4.16], dmq['IcedAgua'/928685679, l='MpServer', x=0.50, y=73.00, z=0.50]]
	Chunk stats: Client Chunk Cache: 18225, 12
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-447,4,2352), Chunk: (at 1,0,0 in -28,147; contains blocks -448,0,2352 to -433,255,2367), Region: (-1,4; contains chunks -32,128 to -1,159, blocks -512,0,2048 to -1,255,2559)
	Level time: 28486052 game time, 76719724000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:5c6bc18:1418) <- Mineplex Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 653780800 bytes (623 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.0-20190817-nightly
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4 20190817
- Using Optifine? No
- Enabled mods: https://i.imgur.com/SGsvtpU.png
- Operating System: Windows 10 64bit
</details>

**Additional context**
Edit: I also crashed when connecting to hypixel, crash log: https://hastebin.com/udacekezox.xml

**Comment by leijurv** [comment]
Potentially the same cause as #1575, please check again once today's nightly is out.

**Comment by ScanmanTM** [comment]
No longer crashes on 20190820, closed.
