### ISSUE TITLE
[1.14] Client crashes when connecting to mc.minehut.com

### ISSUE THREAD

**Issue by FezzedOne** [ImpactDevelopment/ImpactIssues#1575]
**Describe the bug**
Client crash upon connecting to **mc.minehut.com**, shows a disconnection message immediately before crashing.

**To Reproduce**
1. Connect to **mc.minehut.com**.
2. Client immediately disconnects and then crashes.

**Expected behavior**
Expected behaviour is, well, not crashing upon connecting to this server.

**Screenshots**
*Enabled mods:*
![image](https://user-images.githubusercontent.com/48808404/63258194-8ae25280-c249-11e9-8b03-7fe673dd14f4.png)

<details> 
  <summary><strong>Game output</strong></summary>
 
```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 
```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 8/19/19 6:24 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.impactclient.08.0(Unknown Source)
	at net.impactclient.0_.0(Unknown Source)
	at net.impactclient.5A.0(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.impactclient.5A.0(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.7X.post(Unknown Source)
	at dnc.handler$updateCameraAndRender$zzk000(SourceFile:1393)
	at dnc.a(SourceFile:639)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.08.0(Unknown Source)
	at net.impactclient.0_.0(Unknown Source)
	at net.impactclient.5A.0(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.impactclient.5A.0(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.7X.post(Unknown Source)
	at dnc.handler$updateCameraAndRender$zzk000(SourceFile:1393)

-- Affected level --
Details:
	All players: 9 total; [dmp['FezzedOne'/20745, l='MpServer', x=1.00, y=95.00, z=1.00], dmq['mineboxarabic'/20737, l='MpServer', x=-1.00, y=95.00, z=-1.00], dmq['Bankeasy'/214, l='MpServer', x=-1.00, y=95.00, z=-1.00], dmq['__purple__'/20743, l='MpServer', x=-0.17, y=95.00, z=-1.26], dmq['Lasaah'/20739, l='MpServer', x=-0.35, y=95.00, z=-0.20], dmq['HypeForMe'/15967, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['SirAuriels'/20662, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['Nxtas'/20626, l='MpServer', x=-3.87, y=95.00, z=0.39], dmq['Kamoz_'/20723, l='MpServer', x=-2.21, y=99.63, z=4.21]]
	Chunk stats: Client Chunk Cache: 729, 245
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10 game time, 10 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:5c6bc18:1418) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 5.2.5-arch1-1-ARCH
	Java Version: 1.8.0_222, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1407291736 bytes (1342 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.0-20190818-nightly
	LWJGL: 3.2.2 build 10
	OpenGL: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)  GL version 3.0 Mesa 19.1.3, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4, build **20190818**
- Using Optifine? No.
- Enabled mods: As in screenshot above.
- Operating System: Arch Linux

</details>

**Additional context**
No other context.

**Comment by leijurv** [comment]
Fixed for today's nightly
