### ISSUE TITLE
i got registering texture error

### ISSUE THREAD

**Issue by bruh122324** [ImpactDevelopment/ImpactIssues#1601]
impact's latest version [4.7.3] i got registering texture error

optifine no
mods no
normal java version
lacunher: orginal (i tried on tlauncher too but still crashing)

there is crash report

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 8/28/19 1:10 PM
Description: Registering texture

java.lang.NullPointerException: Registering texture
	at net.impactclient.2H.a(Unknown Source)
	at cdh.a(SourceFile:84)
	at cdr.a(SourceFile:60)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.0Ah$$Lambda$62/1806394806.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.0Ah$$Lambda$57/1446594688.apply(Unknown Source)
	at java.util.stream.Collectors.lambda$toMap$171(Collectors.java:1321)
	at java.util.stream.Collectors$$Lambda$60/1464361868.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.2X.0(Unknown Source)
	at net.impactclient.4G.0(Unknown Source)
	at bib.handler$init$zzl000(SourceFile:3136)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.2H.a(Unknown Source)
	at cdh.a(SourceFile:84)

-- Resource location being registered --
Details:
	Resource location: minecraft:downloaded/2378311fabbccae299383fa84b1c8126b4c497ce
	Texture object class: net.impactclient.3M
Stacktrace:
	at cdr.a(SourceFile:60)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.0Ah$$Lambda$62/1806394806.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.0Ah$$Lambda$57/1446594688.apply(Unknown Source)
	at java.util.stream.Collectors.lambda$toMap$171(Collectors.java:1321)
	at java.util.stream.Collectors$$Lambda$60/1464361868.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.impactclient.0Ah.0(Unknown Source)
	at net.impactclient.2X.0(Unknown Source)
	at net.impactclient.4G.0(Unknown Source)
	at bib.handler$init$zzl000(SourceFile:3136)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141018592 bytes (134 MB) / 301989888 bytes (288 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.7.3
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.4.0 - Build 20.19.15.5063, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Türkçe (Türkiye)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU N3700 @ 1.60GHz

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
