### ISSUE TITLE
[1.14] Crash on startup

### ISSUE THREAD

**Issue by raidcookie** [ImpactDevelopment/ImpactIssues#1665]
Game crashes on startup

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/commons/ClassRemapper
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.spongepowered.asm.mixin.transformer.DefaultExtensions.create(DefaultExtensions.java:53)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.<init>(MixinTransformer.java:80)
	at org.spongepowered.asm.mixin.transformer.Proxy.<clinit>(Proxy.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:84)
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.beginPhase(MixinServiceLaunchWrapper.java:284)
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:156)
	at org.spongepowered.asm.launch.MixinBootstrap.init(MixinBootstrap.java:122)
	at clientapi.load.ClientTweaker.setupMixin(Unknown Source)
	at clientapi.load.ClientTweaker.injectIntoClassLoader(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:139)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.ClassRemapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4-20190916
- Using Optifine? Yes
- Enabled mods: None
- Operating System: Win10 x64

</details>

**Comment by LeafHacker** [comment]
My bad, didn't realise we depend on asm-commons too.

**Comment by LeafHacker** [comment]
Oh, this isn't our dependency, it's mixin's. idk why they aren't shadowing it but I guess we'll have to list it.

**Comment by LeafHacker** [comment]
Fixed in the next nightly
