### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by N7NobodyCats** [ImpactDevelopment/ImpactIssues#1677]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// My bad.

Time: 9/21/19 1:49 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2519/905917952.accept(Unknown Source)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2515/590207587.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SortedOps$RefSortingSink$$Lambda$84/584501954.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$1852/1285957717.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1693/2091029650.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.1t.post(Unknown Source)
	at dnc.handler$zzk000$onStartHand(SourceFile:1380)
	at dnc.b(SourceFile:946)
	at dnc.a(SourceFile:766)
	at dnc.a(SourceFile:630)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2519/905917952.accept(Unknown Source)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2515/590207587.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SortedOps$RefSortingSink$$Lambda$84/584501954.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$1852/1285957717.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1693/2091029650.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.1t.post(Unknown Source)
	at dnc.handler$zzk000$onStartHand(SourceFile:1380)
	at dnc.b(SourceFile:946)
	at dnc.a(SourceFile:766)

-- Affected level --
Details:
	All players: 31 total; [dmp['N7NobodyCats'/16034, l='MpServer', x=-1.00, y=95.00, z=-1.00], dmq['Lightning_M'/3387, l='MpServer', x=-0.46, y=95.00, z=-0.86], dmq['themisfis'/1879, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['Neon_Reaper'/3432, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['Keenu'/3424, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['LaMDaKiS'/3412, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['NotRealMe'/3201, l='MpServer', x=14.94, y=99.00, z=-29.75], dmq['_Leftyy'/268, l='MpServer', x=11.61, y=92.94, z=-14.75], dmq['rainbowprofle'/1742, l='MpServer', x=1.94, y=95.00, z=-1.88], dmq['Rift__'/600, l='MpServer', x=0.22, y=95.00, z=-6.70], dmq['teenangstweekly'/3264, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['THe_gyu'/2662, l='MpServer', x=1.00, y=95.00, z=-1.00], dmq['IPhantom'/3386, l='MpServer', x=3.76, y=95.00, z=-3.07], dmq['ASigge'/3366, l='MpServer', x=0.64, y=95.00, z=-0.86], dmq['Ggoblinus'/3381, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['h_gs'/3351, l='MpServer', x=8.12, y=93.00, z=-8.12], dmq['a_rosem72'/3373, l='MpServer', x=1.00, y=95.00, z=-1.00], dmq['HydRaJr'/652, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['masterbasse'/2008, l='MpServer', x=0.72, y=95.00, z=-1.56], dmq['Thatsmecodinary'/3368, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['molleman12'/3198, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['dea112'/3429, l='MpServer', x=0.89, y=95.42, z=-0.89], dmq['BEASTY42'/3434, l='MpServer', x=1.00, y=95.00, z=0.00], dmq['DynoDaniel'/2120, l='MpServer', x=1.00, y=95.00, z=1.00], dmq['BenPokka'/1804, l='MpServer', x=1.00, y=95.00, z=0.00], dmq['Spaicrab'/3435, l='MpServer', x=0.00, y=95.00, z=0.00], dmq['Mcbombom'/3092, l='MpServer', x=0.00, y=95.00, z=1.00], dmq['Faijo'/3060, l='MpServer', x=0.00, y=95.00, z=0.00], dmq['Olblocks'/3342, l='MpServer', x=30.18, y=93.00, z=-27.20], dmq['stefi_exe'/2925, l='MpServer', x=27.10, y=113.00, z=-23.18], dmq['Cafety_'/3437, l='MpServer', x=1.00, y=95.00, z=0.00]]
	Chunk stats: Client Chunk Cache: 729, 505
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,95,9), Chunk: (at 0,5,9 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18269 game time, 288000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:5c6bc18:1418) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1179287256 bytes (1124 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_nightly-20190919
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon HD 7570 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1011, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3 CPU 550 @ 3.20GHz

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.14.4-Impact_nightly-20190919 
- Using Optifine? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
shaders esp still turns screen black when around people wearing elytras :(

**Comment by N7NobodyCats** [comment]
game crashed again... i went to join a server and it was at "loading world" then it crashed and this is the report.
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/21/19 2:05 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2535/29195231.accept(Unknown Source)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2531/1637670238.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SortedOps$RefSortingSink$$Lambda$84/584501954.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$1865/218193338.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1706/894896772.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.1t.post(Unknown Source)
	at dnc.handler$zzk000$onStartHand(SourceFile:1380)
	at dnc.b(SourceFile:946)
	at dnc.a(SourceFile:766)
	at dnc.a(SourceFile:630)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2535/29195231.accept(Unknown Source)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$2531/1637670238.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SortedOps$RefSortingSink$$Lambda$84/584501954.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.5m.0(Unknown Source)
	at net.impactclient.5m$$Lambda$1865/218193338.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1706/894896772.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.1t.post(Unknown Source)
	at dnc.handler$zzk000$onStartHand(SourceFile:1380)
	at dnc.b(SourceFile:946)
	at dnc.a(SourceFile:766)

-- Affected level --
Details:
	All players: 33 total; [dmp['N7NobodyCats'/2013, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['FrostTea_'/1853, l='MpServer', x=-1.15, y=95.00, z=0.72], dmq['hugoxxs13'/1999, l='MpServer', x=-1.00, y=95.00, z=1.00], dmq['FredsTDB'/835, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['Bankeasy'/203, l='MpServer', x=-1.00, y=95.00, z=0.00], dmq['Huira'/1860, l='MpServer', x=-8.05, y=107.27, z=21.50], dmq['Jona4Play'/1962, l='MpServer', x=10.86, y=97.20, z=-32.27], dmq['XANDRES066'/1880, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['jaredfice'/561, l='MpServer', x=4.53, y=96.00, z=-8.24], dmq['joka0606'/1953, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['KyTzuki'/2006, l='MpServer', x=2.40, y=97.00, z=-7.57], dmq['ThiccBrows'/479, l='MpServer', x=0.00, y=95.00, z=-1.00], dmq['elixir01'/1958, l='MpServer', x=0.50, y=95.00, z=-2.23], dmq['69KAASMANDJE69'/1993, l='MpServer', x=1.00, y=95.00, z=-1.00], dmq['Charlie126_'/2008, l='MpServer', x=4.28, y=95.00, z=-3.28], dmq['anaghapoo'/1939, l='MpServer', x=12.59, y=93.00, z=-12.22], dmq['xInefficientx'/1978, l='MpServer', x=0.00, y=95.00, z=1.00], dmq['FudgeyRudgey'/458, l='MpServer', x=0.00, y=95.00, z=1.00], dmq['ImP_kLash'/1719, l='MpServer', x=1.00, y=95.00, z=1.00], dmq['PenguKnight'/1416, l='MpServer', x=1.00, y=95.00, z=0.00], dmq['WillsMcPc'/2011, l='MpServer', x=0.00, y=95.00, z=0.00], dmq['OriginalRPG'/1973, l='MpServer', x=0.00, y=95.00, z=1.00], dmq['ExoticBurn'/1995, l='MpServer', x=7.90, y=98.25, z=4.11], dmq['Ryan_OPturtle'/1469, l='MpServer', x=1.00, y=95.00, z=1.00], dmq['FireDots'/1773, l='MpServer', x=0.00, y=95.00, z=1.00], dmq['BrEAkfaStCake'/2000, l='MpServer', x=1.00, y=95.00, z=1.00], dmq['RubyWalter'/903, l='MpServer', x=0.00, y=95.00, z=0.00], dmq['Tigercub1907'/2012, l='MpServer', x=0.00, y=95.00, z=0.00], dmq['Pen15MZTER'/1986, l='MpServer', x=19.73, y=97.17, z=-41.88], dmq['Boban112'/1969, l='MpServer', x=24.95, y=93.00, z=-33.34], dmq['Pinkbutton'/1951, l='MpServer', x=22.27, y=93.00, z=-38.99], dmq['3asel'/1678, l='MpServer', x=21.80, y=100.15, z=-9.93], dmq['_fringee_'/2014, l='MpServer', x=1.00, y=95.00, z=1.00]]
	Chunk stats: Client Chunk Cache: 729, 529
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,95,9), Chunk: (at 0,5,9 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 160379 game time, 288000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:5c6bc18:1418) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1129438504 bytes (1077 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_nightly-20190919
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon HD 7570 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1011, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3 CPU 550 @ 3.20GHz

**Comment by leijurv** [comment]
This is a crash in ESP2D. Disable that for the time being.

**Comment by leijurv** [comment]
@N7NobodyCats which server?

**Comment by leijurv** [comment]
Figured it out, this could happen in any version

**Comment by leijurv** [comment]
fixed
