### ISSUE TITLE
Mixin already loaded error

### ISSUE THREAD

**Issue by nacjm** [ImpactDevelopment/ImpactIssues#1709]
**Describe the bug**
I am getting a direct crash on launch because the GUIGameover was already transformed

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Mixin prepare failed preparing gui.MixinGuiGameOver in mixins.impact.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.impact.json:gui.MixinGuiGameOver target net.minecraft.client.gui.GuiGameOver was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.impact.json:gui.MixinGuiGameOver target net.minecraft.client.gui.GuiGameOver was already transformed.
    at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885)
    at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856)
    at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809)
    at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569)
    at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451)
    at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://hastebin.com/ureheroxuw.sql
Game crashed before report could be generated
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: forge
- Operating System: Windows 10 64bit

</details>

**Additional context**

**Comment by nacjm** [comment]
Update: I had a friend of mine that does not have access to nightly try the public build with my pack and it seems that the public build still works fine. this issue is just occurring with nightly

**Comment by 0-x-2-2** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

**Comment by 0-x-2-2** [comment]
Afaik this is caused by a bad coremod with a race condition.

**Comment by nacjm** [comment]
Except it worked on the public build of impact. Nightly is the one that broke
