### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by ProkopRandacek** [ImpactDevelopment/ImpactIssues#1743]
**Describe the bug**
Cant launch minecraft

**To Reproduce**
1. Install Impact
2. Try to launch
3. See error

**Expected behavior**
The game to be launched

<details> 
  <summary><strong>Crash report</strong></summary>
 
```
[10:06:53] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[10:06:53] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[10:06:53] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[10:06:53] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[10:06:53] [main/INFO]: Injecting into ClassLoader
[10:06:53] [main/ERROR]: Initialising mixin subsystem after game pre-init phase! Some mixins may be skipped.
[10:06:53] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/home/prokop/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[10:06:53] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[10:06:53] [main/INFO]: Initialized Mixin bootstrap
[10:06:53] [main/INFO]: Setup Mixin Environment
[10:06:53] [main/INFO]: Compatibility level set to JAVA_8
[10:06:53] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[10:06:53] [main/INFO]: Loaded Mixin Configurations
[10:06:53] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[10:06:53] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[10:06:53] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinArmorLayer, name: clientapi.load.mixin.MixinArmorLayer
[10:06:53] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:185) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:155) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Resource
	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.isDelegationExcluded(LegacyTransformerHandle.java:62) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.MixinEnvironment.buildTransformerDelegationList(MixinEnvironment.java:1318) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.MixinEnvironment.getTransformers(MixinEnvironment.java:1277) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:380) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1676) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:273) ~[launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:170) ~[launchwrapper-of-2.1.jar:2.1]
	... 6 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.Resource
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.isDelegationExcluded(LegacyTransformerHandle.java:62) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.MixinEnvironment.buildTransformerDelegationList(MixinEnvironment.java:1318) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.MixinEnvironment.getTransformers(MixinEnvironment.java:1277) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:380) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1676) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:273) ~[launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:170) ~[launchwrapper-of-2.1.jar:2.1]
	... 6 more
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.8 1.14.4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Fedora 30

</details>

**Comment by leijurv** [comment]
Okay fair point, on linux there's no bundled jvm, but on mac and windows there is xD

run Minecraft with Java 8!!!!!
