### ISSUE TITLE
impact keeps crashing

### ISSUE THREAD

**Issue by Zweibel442** [ImpactDevelopment/ImpactIssues#1752]
Impact crashes whenever i load up on a more then 10-20 player server

idk what da problem is

**Expected behavior**
it crashes.

 

- Impact Version: 1.12.2 and 1.14.4
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: doesnt matter i tried it with 0 mods and with some visual mods
- Operating System: windows 7

**Comment by Zweibel442** [comment]
oh and if anyone wants the crash report here ya go
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/3724385/latest.log)

**Comment by Zweibel442** [comment]
[impact help.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/3724459/impact.help.txt)

**Comment by Zweibel442** [comment]
[impact help.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/3724467/impact.help.txt)

**Comment by Zweibel442** [comment]
[14:35:21] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[14:35:21] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[14:35:21] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[14:35:21] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[14:35:21] [main/INFO]: Injecting into ClassLoader
[14:35:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[14:35:26] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[14:35:26] [main/INFO]: Initialized Mixin bootstrap
[14:35:27] [main/INFO]: Setup Mixin Environment
[14:35:27] [main/INFO]: Compatibility level set to JAVA_8
[14:35:27] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[14:35:27] [main/INFO]: Loaded Mixin Configurations
[14:35:27] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[14:35:27] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[14:35:27] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[14:35:27] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlock, name: clientapi.load.mixin.MixinBlock
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityLivingBase, name: clientapi.load.mixin.MixinEntityLivingBase
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityPlayerSP, name: clientapi.load.mixin.MixinEntityPlayerSP
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiBossOverlay, name: clientapi.load.mixin.MixinGuiBossOverlay
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiIngame, name: clientapi.load.mixin.MixinGuiIngame
[14:35:27] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiSpectator, name: clientapi.load.mixin.MixinGuiSpectator
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLayerArmorBase, name: clientapi.load.mixin.MixinLayerArmorBase
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetHandlerLoginClient, name: clientapi.load.mixin.MixinNetHandlerLoginClient
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetHandlerPlayClient, name: clientapi.load.mixin.MixinNetHandlerPlayClient
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRender, name: clientapi.load.mixin.MixinRender
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderItem, name: clientapi.load.mixin.MixinRenderItem
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderManager, name: clientapi.load.mixin.MixinRenderManager
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
[14:35:28] [main/WARN]: Error loading class: Config (java.lang.ClassNotFoundException: The specified class 'Config' was not found)
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinAnvilChunkLoader, name: baritone.launch.mixins.MixinAnvilChunkLoader
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBitArray, name: baritone.launch.mixins.MixinBitArray
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBlockStateContainer, name: baritone.launch.mixins.MixinBlockStateContainer
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChatTabCompleter, name: baritone.launch.mixins.MixinChatTabCompleter
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkProviderClient, name: baritone.launch.mixins.MixinChunkProviderClient
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkProviderServer, name: baritone.launch.mixins.MixinChunkProviderServer
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkRenderContainer, name: baritone.launch.mixins.MixinChunkRenderContainer
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkRenderWorker, name: baritone.launch.mixins.MixinChunkRenderWorker
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityLivingBase, name: baritone.launch.mixins.MixinEntityLivingBase
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityPlayerSP, name: baritone.launch.mixins.MixinEntityPlayerSP
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderer, name: baritone.launch.mixins.MixinEntityRenderer
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinGuiScreen, name: baritone.launch.mixins.MixinGuiScreen
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetHandlerPlayClient, name: baritone.launch.mixins.MixinNetHandlerPlayClient
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerControllerMP, name: baritone.launch.mixins.MixinPlayerControllerMP
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinRenderChunk, name: baritone.launch.mixins.MixinRenderChunk
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinRenderList, name: baritone.launch.mixins.MixinRenderList
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinStateImplementation, name: baritone.launch.mixins.MixinStateImplementation
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinTabCompleter, name: baritone.launch.mixins.MixinTabCompleter
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinVboRenderList, name: baritone.launch.mixins.MixinVboRenderList
[14:35:28] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinWorldClient, name: baritone.launch.mixins.MixinWorldClient
[14:35:28] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:35:31] [main/INFO]: Setting user: Zweibel442
[14:35:36] [main/INFO]: LWJGL Version: 2.9.4
[14:35:38] [main/INFO]: Reloading ResourceManager: Default
[14:35:39] [Sound Library Loader/INFO]: Starting up SoundSystem...
[14:35:40] [Thread-4/INFO]: Initializing LWJGL OpenAL
[14:35:40] [Thread-4/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[14:35:40] [Thread-4/INFO]: OpenAL initialized.
[14:35:40] [Sound Library Loader/INFO]: Sound engine started
[14:35:46] [main/INFO]: Created: 1024x512 textures-atlas
[14:35:50] [main/INFO]: Narrator library for x64 successfully loaded
[14:35:57] [main/INFO]: Loading Fonts
[14:35:59] [main/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[14:35:59] [main/INFO]: [STDERR]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[14:35:59] [main/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[14:36:00] [main/INFO]: [STDOUT]: Sending event category=client action=launch label=4.8.1-1.12.2 cid=1227277848.1569675197
[14:36:00] [pool-6-thread-1/INFO]: Checking for Updates
[14:36:00] [pool-6-thread-1/INFO]: [STDOUT]: Offering updates to betas: false
[14:36:00] [pool-6-thread-1/INFO]: [STDOUT]: Fetching releases from ImpactDevelopment/ImpactReleases
[14:36:00] [pool-6-thread-1/INFO]: [STDOUT]: DOWNLOADING http://impactclient.net/releases.json
[14:36:02] [main/INFO]: [STDERR]: net.impactclient.9y: ERROR: 0:3: 'out' : not available in current GLSL version 
ERROR: 0:3: 'mat4' : syntax error syntax error


[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5K.3(5K.java:20)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5n.2(5n.java:4)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5j.1(5j.java:2)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5V.<init>(5V.java:11)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5a.<init>(5a.java:7)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5a.<init>(5a.java:9)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.7h.<init>(7h.java:105)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.96.1(96.java:12)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.2k.0(2k.java:33)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.0xt.0(0xt.java:8)
[14:36:02] [main/INFO]: [STDERR]: 	at bib.handler$init$zzl000(SourceFile:3152)
[14:36:02] [main/INFO]: [STDERR]: 	at bib.aq(SourceFile:583)
[14:36:02] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[14:36:02] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[14:36:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:36:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:36:02] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:36:02] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:36:02] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:36:02] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:36:02] [main/INFO]: [STDERR]: net.impactclient.9y: Cannot attach a shader to program if shader isn't generated!
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5l.0(5l.java:9)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5l$$Lambda$259/2027367579.accept(Unknown Source)
[14:36:02] [main/INFO]: [STDERR]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5l.2(5l.java:19)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5j.1(5j.java:2)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.5a.<init>(5a.java:2)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.7h.<init>(7h.java:105)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.96.1(96.java:12)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.2k.0(2k.java:33)
[14:36:02] [main/INFO]: [STDERR]: 	at net.impactclient.0xt.0(0xt.java:8)
[14:36:02] [main/INFO]: [STDERR]: 	at bib.handler$init$zzl000(SourceFile:3152)
[14:36:02] [main/INFO]: [STDERR]: 	at bib.aq(SourceFile:583)
[14:36:02] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[14:36:02] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[14:36:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:36:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:36:02] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:36:02] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:36:02] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:36:02] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:36:02] [main/INFO]: Initialized 117 mods!
[14:36:02] [main/FATAL]: Unable to load spam config file: Spam config file is in invalid format
[14:36:02] [main/INFO]: [STDOUT]: Initializing took 5411ms
[14:36:02] [main/ERROR]: Setting skin to impaste
[14:36:26] [main/INFO]: Connecting to moxmc.net, 25565
[14:36:36] [main/INFO]: [STDOUT]: Baritone world data dir: C:\Users\User\AppData\Roaming\.minecraft\baritone\moxmc.net\DIM0
[14:36:36] [main/INFO]: [STDOUT]: Cached world directory: C:\Users\User\AppData\Roaming\.minecraft\baritone\moxmc.net\DIM0\cache
[14:36:36] [main/INFO]: [STDOUT]: Would save waypoints to C:\Users\User\AppData\Roaming\.minecraft\baritone\moxmc.net\DIM0\waypoints
[14:36:37] [main/INFO]: [CHAT]                                      
[14:36:37] [main/INFO]: [CHAT]                                                                   
[14:36:37] [main/INFO]: [CHAT]  
[14:36:37] [main/INFO]: [CHAT]  Welcome back to Purple Prison
[14:36:37] [main/INFO]: [CHAT]  
[14:36:37] [main/INFO]: [CHAT]  New Features:
[14:36:37] [main/INFO]: [CHAT]  /gangs & /itemflip
[14:36:37] [main/INFO]: [CHAT]  
[14:36:37] [main/INFO]: [CHAT]  Discord: discord.purpleprison.net
[14:36:37] [main/INFO]: [CHAT]  Store: buy.purpleprison.net
[14:36:37] [main/INFO]: [CHAT]  
[14:36:37] [main/INFO]: [CHAT]                                                                   
[14:36:37] [pool-5-thread-1/INFO]: [STDOUT]: Loading region 0,0 from disk C:\Users\User\AppData\Roaming\.minecraft\baritone\moxmc.net\DIM0\cache
[14:36:38] [pool-5-thread-1/INFO]: [STDOUT]: Loaded region successfully in 478ms
[14:36:38] [pool-5-thread-1/INFO]: [STDOUT]: Loading region 0,-1 from disk C:\Users\User\AppData\Roaming\.minecraft\baritone\moxmc.net\DIM0\cache
[14:36:38] [pool-5-thread-1/INFO]: [STDOUT]: Loaded region successfully in 78ms
[14:36:38] [main/INFO]: Loaded 7 advancements
[14:36:38] [main/INFO]: [CHAT] §6§l§o[§5§oZ§6§l§o]§8 §7[Vivid] §7§l[§3§lK§d§lO§3§lT§d§lH§7§l] §r§r§f§2Hef§8Nah §d» is something new in here
[14:36:38] [main/INFO]: Loaded 8 advancements
[14:36:38] [main/INFO]: [CHAT] §6§l§o[§5§oZ§6§l§o]§8 §7[2] §3§l[§b§lD§f§lO§b§lP§f§lE§3§l] §f§fqsshole §d» na
[14:36:38] [main/INFO]: AutoCasting

**Comment by chris7479** [comment]
https://cdn.discordapp.com/attachments/633290924448940055/633290984410841098/latest.log
His latest.log file. Full this time

**Comment by NickWilde263** [comment]
Im also keep crashing when you try reconnecting whether using auto reconnect or not

**Comment by l1ving** [comment]
```
[15:10:13] [main/INFO]: [STDERR]: net.impactclient.9y: ERROR: 0:3: 'out' : not available in current GLSL version 
ERROR: 0:3: 'mat4' : syntax error syntax error

```
I had this happen in the past, doesn't happen anymore. Reopen if not fixed.
