### ISSUE TITLE
Can't launch Impact 1.14 with Optifine in MultiMC

### ISSUE THREAD

**Issue by KabanFriends** [ImpactDevelopment/ImpactIssues#1803]
**Describe the bug**
I tried to install Optifine in my Impact client instance (using MultiMC).
But it crashes when you start the game.

**To Reproduce**
1. Follow official steps you can find in wiki of Impact to Install Impact with MultiMC. (this github repo thing)
2. Follow https://github.com/ImpactDevelopment/ImpactIssues/wiki/Adding-OptiFine this wiki to manually add Optifine.
3. Launch the game and it crashes

**Expected behavior**
Game successfully loads and you can play Minecraft

**Screenshots**
![image](https://user-images.githubusercontent.com/45000995/67687631-f3814480-f9db-11e9-834f-bb8fbe71ff7a.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[23:33:10] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[23:33:10] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[23:33:10] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[23:33:10] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[23:33:10] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[23:33:10] [main/INFO]: Injecting into ClassLoader
[23:33:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/yk/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[23:33:10] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[23:33:10] [main/INFO]: Initialized Mixin bootstrap
[23:33:10] [main/INFO]: Setup Mixin Environment
[23:33:10] [main/INFO]: Compatibility level set to JAVA_8
[23:33:10] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[23:33:10] [main/INFO]: Loaded Mixin Configurations
[23:33:10] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[23:33:10] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[23:33:10] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
OptiFineForgeTweaker: acceptOptions
Error checking Forge server: java.lang.NullPointerException: null
OptiFineForgeTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: C:\Users\yk\AppData\Roaming\.minecraft\instances\Impact 1.14.4 4.8.2\libraries\OptiFine_1.14.4_HD_U_F4.jar
[23:33:10] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[23:33:10] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
OptiFineForgeTweaker: getLaunchArguments
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinArmorLayer, name: clientapi.load.mixin.MixinArmorLayer
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlockMode, name: clientapi.load.mixin.MixinBlockMode
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBossOverlayGui, name: clientapi.load.mixin.MixinBossOverlayGui
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayerEntity, name: clientapi.load.mixin.MixinClientPlayerEntity
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayNetHandler, name: clientapi.load.mixin.MixinClientPlayNetHandler
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRendererManager, name: clientapi.load.mixin.MixinEntityRendererManager
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFirstPersonRenderer, name: clientapi.load.mixin.MixinFirstPersonRenderer
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFogRenderer, name: clientapi.load.mixin.MixinFogRenderer
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGameRenderer, name: clientapi.load.mixin.MixinGameRenderer
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinIngameGui, name: clientapi.load.mixin.MixinIngameGui
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinKeyboardListener, name: clientapi.load.mixin.MixinKeyboardListener
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLivingEntity, name: clientapi.load.mixin.MixinLivingEntity
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMouseHelper, name: clientapi.load.mixin.MixinMouseHelper
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
[23:33:10] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinSpectatorGui, name: clientapi.load.mixin.MixinSpectatorGui
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
[23:33:11] [main/WARN]: Error loading class: Config (java.lang.ClassNotFoundException: The specified class 'Config' was not found)
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBitArray, name: baritone.launch.mixins.MixinBitArray
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBlockStateContainer, name: baritone.launch.mixins.MixinBlockStateContainer
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChatScreen, name: baritone.launch.mixins.MixinChatScreen
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkArray, name: baritone.launch.mixins.MixinChunkArray
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientChunkProvider, name: baritone.launch.mixins.MixinClientChunkProvider
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayerEntity, name: baritone.launch.mixins.MixinClientPlayerEntity
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayNetHandler, name: baritone.launch.mixins.MixinClientPlayNetHandler
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntity, name: baritone.launch.mixins.MixinEntity
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderManager, name: baritone.launch.mixins.MixinEntityRenderManager
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinGameRenderer, name: baritone.launch.mixins.MixinGameRenderer
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLivingEntity, name: baritone.launch.mixins.MixinLivingEntity
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLootContext, name: baritone.launch.mixins.MixinLootContext
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerController, name: baritone.launch.mixins.MixinPlayerController
[23:33:11] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinScreen, name: baritone.launch.mixins.MixinScreen
[23:33:11] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:33:11] [main/WARN]: Injection warning: LVT in aio::e(Lcsi;)Lcsi; has incompatible changes at opcode 148 in callback aio::handler$getAllowedMovement$development$zca000.
Expected: [Lcsc;, Lcsn;, Lctc;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Laaa;, Lcsi;, Z, Z, Z, Z]
   Found: [Lcsc;, Lcsn;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Laaa;, Lcsi;, Z, Z, Z, Z]
[23:33:12] [main/INFO]: [OptiFine] *** Reflector Forge ***
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.Attributes
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.BrandingControl
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.capabilities.ICapabilityProvider
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.capabilities.CapabilityProvider
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.ClientModLoader
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.ChunkEvent$Load
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.ClientHooks
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Post
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$FogColors
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$RenderFogEvent
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.entity.EntityJoinWorldEvent
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.IEventBus
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeBlock
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: dnv.getTexture
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: dpt.getModelData
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.addDestroyEffects
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.addHitEffects
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.canRenderInLayer
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getLightValue
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getSoundType
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getStateAtViewpoint
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.isAir
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeFluid
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeFluidState
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fluids.FluidAttributes
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: ais.getTags
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Field not present: aix.NAMETAG_DISTANCE
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.ForgeEventFactory
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: clj.getTags
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfig
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfig$Client
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfigSpec
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfigSpec$ConfigValue
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeItem
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeItemStack
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.ForgeI18n
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.IModel
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.setKeyConflictContext
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.setKeyModifierAndCode
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.getKeyModifier
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeMod
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: dof.fromJson
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEffect
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEffectInstance
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.registries.ForgeRegistryEntry
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeTileEntity
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: cvd$b.preDraw
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Method not present: cvd$b.postDraw
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeDimension
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.gui.GuiModList
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.IRenderHandler
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ItemModelMesherForge
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.LightUtil
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.MinecraftForge
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.MinecraftForgeClient
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.gui.NotificationModUpdateScreen
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.entity.PlaySoundAtEntityEvent
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderBlockOverlayEvent$OverlayType
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.registry.RenderingRegistry
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderItemInFrameEvent
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Pre
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Post
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Pre
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Post
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.ScreenshotEvent
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.server.ServerLifecycleHooks
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.SplashProgress
[23:33:12] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.WorldEvent$Load
[23:33:12] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
[23:33:12] [main/INFO]: Setting user: KabanFriends
[23:33:16] [main/INFO]: LWJGL Version: 3.2.2 build 10
[23:33:21] [main/INFO]: Narrator library for x64 successfully loaded
[23:33:21] [main/ERROR]: Couldn't inject button into MainMenuScreen, Realms button not found
[23:33:21] [main/INFO]: [OptiFine] *** Reloading textures ***
[23:33:21] [main/INFO]: [OptiFine] Resource packs: Default
FATAL ERROR in native method: Thread[Server-Worker-6,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglTexImage2D(Native Method)
FATAL ERROR in native method: Thread[Server-Worker-2,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.glTexImage2D(GL11C.java:1753)
	at org.lwjgl.opengl.GL11C.nglTexImage2D(Native Method)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:7055)
	at org.lwjgl.opengl.GL11C.glTexImage2D(GL11C.java:1753)
	at com.mojang.blaze3d.platform.GlStateManager.texImage2D(SourceFile:493)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:7055)
	at net.optifine.util.TextureUtils.detectGLMaximumTextureSize(TextureUtils.java:701)
	at com.mojang.blaze3d.platform.GlStateManager.texImage2D(SourceFile:493)
	at net.optifine.util.TextureUtils.getGLMaximumTextureSize(TextureUtils.java:688)
	at net.optifine.util.TextureUtils.detectGLMaximumTextureSize(TextureUtils.java:701)
	at dxa.a(AtlasTexture.java:331)
	at net.optifine.util.TextureUtils.getGLMaximumTextureSize(TextureUtils.java:688)
	at dxv.a(SourceFile:29)
	at dxv.b(SourceFile:11)
	at xl.a(SourceFile:11)
	at xl$$Lambda$1653/297366988.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	at dxa.a(AtlasTexture.java:331)
	at dlp.lambda$reload$3(ParticleManager.java:178)
	at dlp$$Lambda$1673/927226967.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.2 for 1.14.4
- Using Optifine? Yes (but can't launch)
- Using LiteLoader? No
- Enabled mods: None (except Optifine)
- Operating System: Windows 10 64bit

</details>

**Comment by devatator** [comment]
this might be a ploblem on your computer because it works fine for me.
Just check if you have forge or mods installed on your 1.14 instance, it might be the cause

**Comment by KabanFriends** [comment]
https://github.com/MMCInstances/OptifineInstances
I found this and replaced the instance with this premade instance and then installed Impact.
Now it works!

but I still don't know what caused that crash problem

**Comment by devatator** [comment]
Maybe you messed up the json but at least it works now
