### ISSUE TITLE
its a bug in baritone lol

### ISSUE THREAD

**Issue by KMatias123** [ImpactDevelopment/ImpactIssues#1861]

**Comment by KMatias123** [comment]
when u write follow %playername%

**Comment by KMatias123** [comment]
my log is too long so i take the part where the exception happens lol
[17:15:32] [main/INFO] [minecraft/GuiNewChat]: [CHAT] [Baritone] > follow player %playername%
[17:15:32] [main/INFO] [minecraft/GuiNewChat]: [CHAT] [Baritone] Following these types of entities:
[17:15:32] [main/INFO] [minecraft/GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cc.execute(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.a(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.onSendChatMessage(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.a(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zeh000(EntityPlayerSP.java)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:15:32] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.aw.execute(Unknown Source)
[17:15:32] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 32 more
[17:15:41] [main/INFO] [minecraft/GuiNewChat]: [CHAT] Dominik1997CZ turned into mush
[17:15:42] [main/INFO] [minecraft/GuiNewChat]: [CHAT] <Sebas0101> spanhis?]
[17:15:48] [main/INFO] [minecraft/GuiNewChat]: [CHAT] <Melwiin> no
[17:15:50] [main/INFO] [minecraft/GuiNewChat]: [CHAT] Saved screenshot as 2019-11-20_17.15.50.png
[17:15:55] [main/INFO] [minecraft/GuiNewChat]: [CHAT] Dominik1997CZ broke their fucking legs
[17:15:56] [main/INFO] [minecraft/GuiNewChat]: [CHAT] <PeruvianSlayer> spanhish? xD
[17:15:57] [main/INFO] [minecraft/GuiNewChat]: [CHAT] <Sebas0101> englis?]
[17:16:01] [Netty Client IO #4/INFO] [schematica]: Scheduling client settings reset.
[17:16:01] [main/INFO] [FML]: Applying holder lookups
[17:16:01] [main/INFO] [FML]: Holder lookups applied
[17:16:02] [pool-5-thread-46/INFO] [STDOUT]: [baritone.u:c:-1]: Started saving the world in a new thread
[17:16:02] [pool-5-thread-47/INFO] [STDOUT]: [baritone.u:b:-1]: Started saving saved containers in a new thread
[17:16:02] [pool-5-thread-46/INFO] [STDOUT]: [baritone.m:a:-1]: Saving region -1,-1 to disk D:\Program Files (x86)\MultiMC\instances\impact 4.8.1 for good anticheat\.minecraft\baritone\9b9t.com\DIM-1\cache
[17:16:02] [ForkJoinPool.commonPool-worker-6/INFO] [STDOUT]: [baritone.m:a:-1]: Saving region -1,0 to disk D:\Program Files (x86)\MultiMC\instances\impact 4.8.1 for good anticheat\.minecraft\baritone\9b9t.com\DIM-1\cache
[17:16:02] [ForkJoinPool.commonPool-worker-4/INFO] [STDOUT]: [baritone.m:a:-1]: Saving region 0,-1 to disk D:\Program Files (x86)\MultiMC\instances\impact 4.8.1 for good anticheat\.minecraft\baritone\9b9t.com\DIM-1\cache
[17:16:02] [ForkJoinPool.commonPool-worker-3/INFO] [STDOUT]: [baritone.m:a:-1]: Saving region 0,0 to disk D:\Program Files (x86)\MultiMC\instances\impact 4.8.1 for good anticheat\.minecraft\baritone\9b9t.com\DIM-1\cache
[17:16:02] [main/INFO] [schematica]: Client settings have been reset.
[17:16:02] [Netty Client IO #5/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, infinity, inventorytweaks, jei, lunatriuscore, mousetweaks, schematica, shulkertooltip, simpleignore, chunkbase_slimemod_ssp, worldeditcuife2, worldedit] at SERVER
[17:16:02] [ForkJoinPool.commonPool-worker-3/INFO] [STDOUT]: [baritone.m:a:-1]: Saved region successfully
[17:16:02] [Netty Client IO #7/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, infinity, inventorytweaks, jei, lunatriuscore, mousetweaks, schematica, shulkertooltip, simpleignore, chunkbase_slimemod_ssp, worldeditcuife2, worldedit] at SERVER
[17:16:02] [ForkJoinPool.commonPool-worker-4/INFO] [STDOUT]: [baritone.m:a:-1]: Saved region successfully
[17:16:02] [Netty Client IO #8/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, infinity, inventorytweaks, jei, lunatriuscore, mousetweaks, schematica, shulkertooltip, simpleignore, chunkbase_slimemod_ssp, worldeditcuife2, worldedit] at SERVER
[17:16:02] [ForkJoinPool.commonPool-worker-6/INFO] [STDOUT]: [baritone.m:a:-1]: Saved region successfully
[17:16:02] [pool-5-thread-46/INFO] [STDOUT]: [baritone.m:a:-1]: Saved region successfully
[17:16:02] [pool-5-thread-46/INFO] [STDOUT]: [baritone.n:save:-1]: World save took 569ms
[17:23:37] [pool-5-thread-2/INFO] [STDOUT]: [baritone.n:save:-1]: World save took 1ms
[17:23:39] [pool-5-thread-5/INFO] [STDOUT]: [baritone.n:save:-1]: World save took 0ms

**Comment by KMatias123** [comment]
if u want to reptroduce the thing just type it lol

**Comment by ScanmanTM** [comment]
☺️👉 https://github.com/cabaletta/baritone/issues
