### ISSUE TITLE
Crash on teleport on a server

### ISSUE THREAD

**Issue by ChillSheep** [ImpactDevelopment/ImpactIssues#1899]
**Describe the bug**
Crash on a specific minecraft server if I use /warp shop, it doesnt crash without impact

**To Reproduce**
1. Go to mc.atlantis-nt.com
2. Type /warp shop
3. It should crash

**Expected behavior**
The game should not crash

<details> 
  <summary><strong>Game output</strong></summary>
 

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/9/19 8:34 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.impactclient.66.1(66.java:330)
	at net.impactclient.66$$Lambda$1943/593059289.test(Unknown Source)
	at net.impactclient.2e.0(2e.java:6)
	at net.impactclient.4w.0(4w.java:10)
	at net.impactclient.4w$$Lambda$2591/1500541772.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at net.impactclient.4w.0(4w.java:2)
	at net.impactclient.6X$$Lambda$2815/1119148279.test(Unknown Source)
	at net.impactclient.6X.0(6X.java:32)
	at net.impactclient.6X$$Lambda$2816/338863747.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.impactclient.6X.0(6X.java:24)
	at net.impactclient.8V.0(8V.java:15)
	at net.impactclient.8L.0(8L.java:16)
	at net.impactclient.66.0(66.java:223)
	at net.impactclient.66$$Lambda$1916/1660050994.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1838/32772296.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.5Q.post(5Q.java:3)
	at dmp.handler$onPreUpdateWalking$zzd000(SourceFile:1254)
	at dmp.M(SourceFile)
	at dmp.h(SourceFile:208)
	at dkf.a(ClientWorld.java:220)
	at dkf$$Lambda$2652/2010451166.accept(Unknown Source)
	at bhr.a(SourceFile:675)
	at dkf.d(ClientWorld.java:179)
	at cyc.m(SourceFile:1433)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.66.1(66.java:330)
	at net.impactclient.66$$Lambda$1943/593059289.test(Unknown Source)
	at net.impactclient.2e.0(2e.java:6)
	at net.impactclient.4w.0(4w.java:10)
	at net.impactclient.4w$$Lambda$2591/1500541772.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at net.impactclient.4w.0(4w.java:2)
	at net.impactclient.6X$$Lambda$2815/1119148279.test(Unknown Source)
	at net.impactclient.6X.0(6X.java:32)
	at net.impactclient.6X$$Lambda$2816/338863747.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.impactclient.6X.0(6X.java:24)
	at net.impactclient.8V.0(8V.java:15)
	at net.impactclient.8L.0(8L.java:16)
	at net.impactclient.66.0(66.java:223)
	at net.impactclient.66$$Lambda$1916/1660050994.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1838/32772296.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.5Q.post(5Q.java:3)
	at dmp.handler$onPreUpdateWalking$zzd000(SourceFile:1254)
	at dmp.M(SourceFile)
	at dmp.h(SourceFile:208)
	at dkf.a(ClientWorld.java:220)
	at dkf$$Lambda$2652/2010451166.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (dmp)
	Entity ID: 36376
	Entity Name: MYNAME
	Entity's Exact location: -2138.50, 63.92, 2099.50
	Entity's Block location: World: (-2139,63,2099), Chunk: (at 5,3,3 in -134,131; contains blocks -2144,0,2096 to -2129,255,2111), Region: (-5,4; contains chunks -160,128 to -129,159, blocks -2560,0,2048 to -2049,255,2559)
	Entity's Momentum: 0.00, -0.16, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at bhr.a(SourceFile:675)
	at dkf.d(ClientWorld.java:179)

-- Affected level --
Details:
	All players: 1 total; [dmp['MYNAME'/36376, l='MpServer', x=-2138.50, y=63.92, z=2099.50]]
	Chunk stats: Client Chunk Cache: 361, 281
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-3207,56,169), Chunk: (at 9,3,9 in -201,10; contains blocks -3216,0,160 to -3201,255,175), Region: (-7,0; contains chunks -224,0 to -193,31, blocks -3584,0,0 to -3073,255,511)
	Level time: 279918615 game time, 326113242 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:c798407:1422) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(ClientWorld.java:574)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:425)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1289927664 bytes (1230 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.2-OptiFine_HD_U_F5
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.41
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by ChillSheep** [comment]
Additional Client Info
Impact Version: 4.8.2
Using Optifine? Yes
Using LiteLoader? No
Enabled mods: Anti Hunger,No Fall Criticals Fast Interact Boat Fly Riding Lag
Operating System: Windows Server 2019

**Comment by EthanPlayzDev** [comment]
Try without Optifine
