### ISSUE TITLE
Crash when clicking Link in Chat.

### ISSUE THREAD

**Issue by dandud100** [ImpactDevelopment/ImpactIssues#1910]
4.8.2 Impact 1.14.4 with Optifine_HD_U_F4 crashes when clicking on a link in chat.
Only Vanilla Minecraft with Optifine_HD_U_F4 doesnt.

`[17:04:26] [main/FATAL]: Reported exception thrown!
m: mouseClicked event handler
	at dcl.wrapScreenError(SourceFile:446) ~[1.14.4.jar:?]
	at cyd.a(SourceFile:86) ~[1.14.4.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at cuo.k(MainWindow.java:503) ~[cuo.class:?]
	at cuo.c(MainWindow.java:342) ~[cuo.class:?]
	at cyc.b(SourceFile:1023) ~[cyc.class:?]
	at cyc.e(SourceFile:976) ~[cyc.class:?]
	at cyc.b(SourceFile:410) [cyc.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
Caused by: java.lang.StackOverflowError
	at dcl.openLink(SourceFile) ~[dcl.class:?]
	at dcl.openLink(SourceFile) ~[dcl.class:?]
	at dcl.openLink(SourceFile) ~[dcl.class:?]`

**Comment by ScanmanTM** [comment]
can you search for issues before you post to avoid dupes, kthx.
