### ISSUE TITLE
instant crash on startup

### ISSUE THREAD

**Issue by tawan475** [ImpactDevelopment/ImpactIssues#1932]
**Describe the bug**
Crash on startup 

Note: I tried reinstalling minecraft/uninstall Impact 4.8.3 jar file and everything else work just fine.

**To Reproduce**
1. Install minecraft
2. Install forge 1.12.2.2847
2. Install impact 4.8.3
2. Install optifine 1.12.2 F5

**Expected behavior**
Normal startup

<details><summary><strong>Game output</strong></summary>
 

```
debug.log: https://pastebin.com/raw/zEU3eeAS
latest.log: https://pastebin.com/raw/cnAxmQDU
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 1/10/20 2:44 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.minecraft.item.ItemStack.redirect$isAdvanced$zcn000(ItemStack.java:1337)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:874)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$114/10579370.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$116/29404925.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 17965
	at java.lang.String.substring(String.java:1951)
	at net.impactclient.0GX.<clinit>(0GX.java)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.redirect$isAdvanced$zcn000(ItemStack.java:1337)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:874)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$114/10579370.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$116/29404925.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 223386520 bytes (213 MB) / 587202560 bytes (560 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature |
	|:----- |:--------- |:------------ |:----------------------------- |:--------- |
	| LCH   | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCH   | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCH   | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: ASUS EAH5450 Series GL version 4.5.13406 Compatibility Profile Context 15.201.1801.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 1x AMD Sempron(tm) 145 Processor
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13406 Compatibility Profile Context 15.201.1801.0
	OpenGlRenderer: ASUS EAH5450 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 1
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3 1.12.2  
- Using Optifine: Yes 1.12.2 F5 
- Using LiteLoader: No 
- Enabled mods: None 
- Operating System: Windows 7 32bit 

</details>

**Comment by ScanmanTM** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

**Comment by tawan475** [comment]
tried it with**out** forge still crash but without crash report this time
