### ISSUE TITLE
Game crashing after loading a new chunk after logging in

### ISSUE THREAD

**Issue by Crystallinqq** [ImpactDevelopment/ImpactIssues#1933]
**Describe the bug**
Game crashes after loading chunks with impact.

**To Reproduce**
1. run game
2. join server
3. walk a bit

**Expected behavior**
game to run
**Screenshots**
https://i.imgur.com/VKdkWx6.png
<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 1/9/20 4:28 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.ce.a(Unknown Source)
	at baritone.ce$$Lambda$748/186163873.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.ce.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zek000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.ce.a(Unknown Source)
	at baritone.ce$$Lambda$748/186163873.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.ce.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zek000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 6 total; [EntityPlayerSP['Crystallinqq'/57421, l='MpServer', x=81.06, y=109.00, z=63.70], EntityOtherPlayerMP['Ironbot1218'/55562, l='MpServer', x=63.33, y=3.45, z=39.70], EntityOtherPlayerMP['Biaflu'/54377, l='MpServer', x=68.95, y=109.15, z=99.05], EntityOtherPlayerMP['Namiix13'/54792, l='MpServer', x=64.55, y=108.00, z=80.38], EntityOtherPlayerMP['squidoodly'/57537, l='MpServer', x=64.85, y=108.00, z=76.25], EntityOtherPlayerMP['CFENGLRN'/57538, l='MpServer', x=64.90, y=108.00, z=73.88]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (64,108,80), Chunk: (at 0,6,0 in 4,5; contains blocks 64,0,80 to 79,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 97385 game time, 456567081 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityPlayerSP['Crystallinqq'/57421, l='MpServer', x=81.06, y=109.00, z=63.70], EntityOtherPlayerMP['squidoodly'/57537, l='MpServer', x=64.85, y=108.00, z=76.25], EntityOtherPlayerMP['CFENGLRN'/57538, l='MpServer', x=64.90, y=108.00, z=73.88], EntityEnderCrystal['entity.EnderCrystal.name'/7, l='MpServer', x=31.50, y=86.00, z=78.50], EntityEnderCrystal['entity.EnderCrystal.name'/57543, l='MpServer', x=19.50, y=3.00, z=83.50], EntityOtherPlayerMP['Namiix13'/54792, l='MpServer', x=64.55, y=108.00, z=80.38], EntityOtherPlayerMP['Ironbot1218'/55562, l='MpServer', x=63.33, y=3.45, z=39.70], EntityEnderCrystal['entity.EnderCrystal.name'/11, l='MpServer', x=44.50, y=86.00, z=46.50], EntityOtherPlayerMP['Namiix13'/54792, l='MpServer', x=64.55, y=108.00, z=80.38], EntityEnderCrystal['entity.EnderCrystal.name'/12, l='MpServer', x=43.50, y=86.00, z=71.50], EntityOtherPlayerMP['squidoodly'/57537, l='MpServer', x=64.85, y=108.00, z=76.25], EntityEnderCrystal['entity.EnderCrystal.name'/13, l='MpServer', x=34.50, y=86.00, z=78.50], EntityOtherPlayerMP['CFENGLRN'/57538, l='MpServer', x=64.90, y=108.00, z=73.88], EntityOtherPlayerMP['Ironbot1218'/55562, l='MpServer', x=63.33, y=3.45, z=39.70], EntityEnderCrystal['entity.EnderCrystal.name'/15, l='MpServer', x=58.50, y=86.00, z=47.50], EntityEnderCrystal['entity.EnderCrystal.name'/16, l='MpServer', x=56.50, y=86.00, z=47.50], EntityEnderCrystal['entity.EnderCrystal.name'/17, l='MpServer', x=59.50, y=86.00, z=45.50], EntityEnderCrystal['entity.EnderCrystal.name'/18, l='MpServer', x=54.50, y=86.00, z=47.50], EntityEnderCrystal['entity.EnderCrystal.name'/19, l='MpServer', x=57.50, y=86.00, z=49.50], EntityEnderCrystal['entity.EnderCrystal.name'/20, l='MpServer', x=55.50, y=86.00, z=49.50], EntityEnderCrystal['entity.EnderCrystal.name'/21, l='MpServer', x=53.50, y=86.00, z=49.50], EntityEnderCrystal['entity.EnderCrystal.name'/22, l='MpServer', x=63.50, y=86.00, z=114.50], EntityEnderCrystal['entity.EnderCrystal.name'/23, l='MpServer', x=61.50, y=86.00, z=114.50], EntityEnderCrystal['entity.EnderCrystal.name'/24, l='MpServer', x=62.50, y=86.00, z=112.50], EntityOtherPlayerMP['Biaflu'/54377, l='MpServer', x=68.95, y=109.15, z=99.05], EntityOtherPlayerMP['Namiix13'/54792, l='MpServer', x=13.30, y=2.00, z=85.35], EntityEnderCrystal['entity.EnderCrystal.name'/31, l='MpServer', x=64.50, y=86.00, z=46.50], EntityEnderCrystal['entity.EnderCrystal.name'/32, l='MpServer', x=67.50, y=86.00, z=47.50], EntityEnderCrystal['entity.EnderCrystal.name'/33, l='MpServer', x=67.50, y=86.00, z=45.50], EntityEnderCrystal['entity.EnderCrystal.name'/34, l='MpServer', x=65.50, y=86.00, z=111.50], EntityEnderCrystal['entity.EnderCrystal.name'/35, l='MpServer', x=68.50, y=86.00, z=113.50], EntityEnderCrystal['entity.EnderCrystal.name'/36, l='MpServer', x=65.50, y=86.00, z=113.50], EntityEnderCrystal['entity.EnderCrystal.name'/41, l='MpServer', x=95.50, y=86.00, z=93.50], EntityOtherPlayerMP['Biaflu'/54377, l='MpServer', x=68.95, y=109.15, z=99.05], EntityEnderCrystal['entity.EnderCrystal.name'/46, l='MpServer', x=96.50, y=86.00, z=91.50]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.14-SNAPSHOT:e4dda6b:297) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 387072960 bytes (369 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature |
	|:------ |:--------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.20' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.20, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.8.3 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: 
- Operating System: Windows 10 x64

</details>

**Additional context**
I think it occurs when I load new chunks in. I am not using baritone so idk why the stacktrace states

**Comment by 0-x-2-2** [comment]
Send full logs

**Comment by Crystallinqq** [comment]
https://hastebin.com/raw/izaweqekos @0-x-2-2

**Comment by Crystallinqq** [comment]
also occurs with 4.6

**Comment by 0-x-2-2** [comment]
Unable to reproduce with the same OS, Forge version, and Java version. The only way I can possibly think we can fix this is by using remote desktop or similar to control your computer to debug it.

**Comment by S-B99** [comment]
Closed due to inactivity.

**Comment by S-B99** [comment]
Please provide the requested information if this is still happening.
