### ISSUE TITLE
1.12.2 Thaumcraft Crashes

### ISSUE THREAD

**Issue by MayhemBill** [ImpactDevelopment/ImpactIssues#1957]
**Describe the bug**
game crashes with Thaumcraft installed 
**To Reproduce**
Launch game with Thaumcraft and Impact on Forge

**Expected behavior**
It start properly
**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Description: Initializing game

java.lang.NullPointerException
    at net.minecraft.block.Block.handler$isFullBlock$zeg000(Block.java:3196)
    at net.minecraft.block.Block.isFullBlock(Block.java)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.isFullBlock(BlockStateContainer.java:299)
    at thaumcraft.common.blocks.world.plants.BlockPlantVishroom.isFullCube(BlockPlantVishroom.java:37)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.isFullCube(BlockStateContainer.java:345)
    at com.raoulvdberge.refinedstorage.apiimpl.network.node.cover.CoverManager.isModelSupported(CoverManager.java:165)
    at com.raoulvdberge.refinedstorage.apiimpl.network.node.cover.CoverManager.isValidCover(CoverManager.java:157)
    at com.raoulvdberge.refinedstorage.item.ItemCover.getSubItems(ItemCover.java:119)
    at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:587)
    at net.minecraft.client.Minecraft.init(Minecraft.java:529)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.2 for 1.12.2
- Using Optifine? no
- Using LiteLoader? No
- Enabled mods: 
- Operating System: Windows 10 64bit"

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
