### ISSUE TITLE
 1.14.4 impact is not working 

### ISSUE THREAD

**Issue by Emirhan398** [ImpactDevelopment/ImpactIssues#1959]
[12:37:40] [Client Shutdown Thread/ERROR]: Caught previously unhandled exception :
java.lang.NoClassDefFoundError: dmp
	at net.minecraft.client.main.Main$2.run(SourceFile:138) ~[Main$2.class:?]
Caused by: java.lang.ClassNotFoundException: dmp
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:97) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 1 more
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

im always getting this text pls help me

**Comment by ScanmanTM** [comment]
Can you like, upload the whole log.

**Comment by Emirhan398** [comment]
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ınventory:Lawf; in awg for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lawf;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:273) ~[launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:170) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[Main.class:?]
	... 6 more
[16:21:41] [Client Shutdown Thread/ERROR]: Caught previously unhandled exception :
java.lang.NoClassDefFoundError: dmp
	at net.minecraft.client.main.Main$2.run(SourceFile:138) ~[Main$2.class:?]
Caused by: java.lang.ClassNotFoundException: dmp
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:97) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 1 more
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by LeafHacker** [comment]
> `java.lang.NoClassDefFoundError: dmp`
> `InvalidAccessorException: No candidates were found matching ınventory:Lawf; in awg for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lawf;)V`

Sounds like the classpath is missing a load of minecraft classes. I suspect either you version json is wrong or you haven't run the matching minecraft version before running impact.

Run Minecraft (vanilla) 1.14.4 first, then re-install Impact using the [latest installer](https://github.com/ImpactDevelopment/Installer/releases).

**Comment by Emirhan398** [comment]
i did but it happened again
