### ISSUE TITLE
Impact conflits with BuildCraft

### ISSUE THREAD

**Issue by ishland** [ImpactDevelopment/ImpactIssues#1965]
**Describe the bug**
When I use Impact 1.12.2 Forge and BuildCraft, BuildCraft crashed during Initialization stage.

**To Reproduce**
1. Use forge 2847
2. Intall Impact 1.12.2 for Forge
3. Throw BuildCraft into mods directory
4. The game crashed during loading

**Expected behavior**
I am able to play Minecraft with Impact and BuildCraft.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Pastebin: https://pastebin.com/iUrFQVkT
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 1/28/20 10:57 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)
Caused by: java.lang.IllegalStateException: Scanning facade states
    State = minecraft:double_stone_slab[seamless=true,variant=sandstone]
    Block = minecraft:double_stone_slab
    Stack = 1xtile.stoneSlab@1
    varying-properties: {
        PropertyBool{name=seamless, clazz=class java.lang.Boolean, values=[true, false]} = null
    }
	at buildcraft.silicon.plug.FacadeStateManager.scanBlock(FacadeStateManager.java:354)
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:213)
	at buildcraft.silicon.BCSilicon.init(BCSilicon.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.block.Block.handler$isFullBlock$zbj000(Block.java:3203)
	at net.minecraft.block.Block.func_149730_j(Block.java)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185913_b(BlockStateContainer.java:299)
	at net.minecraft.block.Block.isSideSolid(Block.java:1071)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:516)
	at buildcraft.silicon.plug.FacadeBlockStateInfo.<init>(FacadeBlockStateInfo.java:41)
	at buildcraft.silicon.plug.FacadeStateManager.scanBlock(FacadeStateManager.java:319)
	... 42 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_232, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20191016_492 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09), Eclipse OpenJ9
	Memory: 25516144 bytes (24 MB) / 513474560 bytes (489 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 14 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-openj9\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3g -Xcodecache128m -Xshareclasses:persistent,nonfatal,allowClasspaths -Xaggressive -XX:SharedCacheHardLimit=2g -Xjit:enableGPU -XcompilationThreads4 -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3 -Xgc:scvNoAdaptiveTenure
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                        | Signature |
	|:----- |:------------------- |:------------ |:----------------------------- |:--------- |
	| LCHI  | minecraft           | 1.12.2       | minecraft.jar                 | None      |
	| LCHI  | mcp                 | 9.42         | minecraft.jar                 | None      |
	| LCHI  | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHI  | forge               | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHI  | buildcraftlib       | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCHI  | buildcraftcore      | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCHI  | buildcraftbuilders  | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCHI  | buildcrafttransport | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCHE  | buildcraftsilicon   | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCH   | buildcraftcompat    | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCH   | buildcraftenergy    | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCH   | buildcraftfactory   | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |
	| LCH   | buildcraftrobotics  | 7.99.24.4    | buildcraft-all-7.99.24.4.jar  | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6472' Renderer: 'Intel(R) HD Graphics 620'
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3 for forge 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: No
- Operating System: Windows 10 1909

</details>

**Additional context**
java -version output:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20191016_492 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)
```

**Comment by Luggibumm** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
