### ISSUE TITLE
I got error running Impact 4.8.3 for 1.14.4

### ISSUE THREAD

**Issue by filiperose** [ImpactDevelopment/ImpactIssues#1987]
**Log:**

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/14/20 2:38 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/TextureUtil
	at cuo.a(MainWindow.java:213)
	at cuo.a(MainWindow.java:172)
	at cyc.au(SourceFile:469)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mojang.blaze3d.platform.TextureUtil
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Caused by: java.lang.SecurityException: class "com.mojang.blaze3d.platform.TextureUtil"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.a(MainWindow.java:213)
	at cuo.a(MainWindow.java:172)
	at cyc.au(SourceFile:469)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 613529504 bytes (585 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.3-OptiFine_HD_U_F5
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 630 GL version 4.6.0 - Build 26.20.100.7262, Intel
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 8

**Comment by S-B99** [comment]
what other mods are you using? please fill out the entire issue template next time

**Comment by 0-x-2-2** [comment]
> what other mods are you using? please fill out the entire issue template next time

OptiFine

**Comment by S-B99** [comment]
oh I missed that
they put it at the bottom for some reason

**Comment by 0-x-2-2** [comment]
> oh I missed that
> they put it at the bottom for some reason

It is called the crash report.

**Comment by S-B99** [comment]
I edited my message before you replied.

**Comment by ZeroMemes** [comment]
Try re-downloading the installer, this might be caused by the bug introduced in 0.8.2.
