### ISSUE TITLE
NumberFormatException after Animations is enabled

### ISSUE THREAD

**Issue by toriato** [ImpactDevelopment/ImpactIssues#1996]
**Describe the bug**
NumberFormatException occur when Animations is enabled.

**To Reproduce**
1. Enable *Misc / Animations*
2. Restart the game
3. Boom, NumberFormatException

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at net.impactclient.2b.0(2b.java:133)
	at net.impactclient.2b$$Lambda$2369/211787747.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1983/1417312717.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.0NR.post(0NR.java:2)
	at dbn.handler$preRunGameLoop$zzp000(SourceFile:2546)
	at dbn.d(SourceFile)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.15.2 nightly-20200213
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Animations
- Operating System: Windows 10 x64

</details>

**Comment by ScanmanTM** [comment]
Why are you using 20200213?????????
You ever thought of downloading the latest nightly???
