### ISSUE TITLE
[NIGHTLY-20200314] Impact donator status watermark / API broken, missing, or removed

### ISSUE THREAD

**Issue by toquengtoketin** [ImpactDevelopment/ImpactIssues#2063]
**Describe the bug**
This does not affect any Minecraft version, only Impact version.
The watermark presented at the title screen and in-game in the upper-left corner does not show the users' status while the watermark is turned on. Could not tell if bug or status revoked. Understanding nightly builds are still in development, felt as though this should be reported.

**To Reproduce**
1. Install Impact version `nightly-20200314`
2. Play the profile
3. Looking in the upper-left the status is missing, but still shows version
4. To verify status, downgrade to any\* nightly and status reappears

**Expected behavior**
Looking at the watermark, it should display a users Impact edition.

**Screenshots**
* [The Main Menu does not show the edition in 20200314](https://i.imgur.com/zn25JnS.png)
* [In-game does not show the edition either in 20200314](https://i.imgur.com/Qx4gY1h.png)
* [Downgrading to any\* other nightly restores the edition](https://i.imgur.com/fdC11B1.png)
* [What is appears to look like in stable builds](https://i.imgur.com/MTkzWf8.png)

<details> 
  <summary><strong>Game output</strong></summary>

`logs/*.log`
contained in the logs, affects nightlies, `nightly-20200310` and below, stable is fine, `nightly-20200314` doesn't appear to produce it

```
[19:40:45] [main/ERROR]: Error parsing GOLD
java.lang.NumberFormatException: For input string: "GOLD"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51]
	at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_51]
	at java.lang.Long.valueOf(Long.java:776) ~[?:1.8.0_51]
	at java.lang.Long.decode(Long.java:928) ~[?:1.8.0_51]
	at net.impactclient.07.0(07.java:19) [07.class:?]
	at net.impactclient.07.1(07.java:47) [07.class:?]
	at net.impactclient.7Q.5(7Q.java:41) [7Q.class:?]
	at net.impactclient.7Q$$Lambda$2737/1175395593.apply(Unknown Source) [7Q.class:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118) [?:1.8.0_51]
	at net.impactclient.7Q.5(7Q.java:22) [7Q.class:?]
	at dgf.drawWatermark(SourceFile:686) [dgf.class:?]
	at dgf.drawInfoText(SourceFile:601) [dgf.class:?]
	at dgf.handler$afterSuperRender$zeg000(SourceFile:668) [dgf.class:?]
	at dgf.render(SourceFile:251) [dgf.class:?]
	at dfq.render(SourceFile:62) [dfq.class:?]
	at dqn.a(SourceFile:593) [dqn.class:?]
	at dbn.d(SourceFile:989) [dbn.class:?]
	at dbn.d(SourceFile:619) [dbn.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
</details>

<details> 
  <summary><strong>Crash report</strong></summary>

```
n/a
```
</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>

- Impact Version: nightly-20200314 for X.XX.X
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods:
    <details> 
      <summary><strong>HUD</strong></summary>

    {"name":"hud","state":true,"bind":"RCONTROL","display":false,"values":[{"id":"watermark","value":true},{"id":"arraylist","value":true,"values":[{"id":"colors","value":"Random","values":[{"id":"saturation","value":50},{"id":"brightness","value":100}]},{"id":"style","value":"Flare"},{"id":"suffix","value":true,"values":[{"id":"color","value":"GRAY"},{"id":"brackets","value":true,"values":[{"id":"color","value":"DARK_GRAY"}]}]}]},{"id":"textshadowdistance","value":0.69},{"id":"effects","value":false},{"id":"potcounter","value":false},{"id":"coords","value":"Inline","values":[{"id":"nether","value":true},{"id":"overworld","value":true},{"id":"freecam","value":true}]},{"id":"speed","value":false,"values":[{"id":"distance","value":"METER"},{"id":"time","value":"SECOND"},{"id":"avg","value":true,"values":[{"id":"duration","value":2}]}]},{"id":"facing","value":true},{"id":"info","value":true,"values":[{"id":"nicerfps","value":true}]},{"id":"tabgui","value":true},{"id":"lagmeter","value":true,"values":[{"id":"duration","value":0.5},{"id":"blink","value":true},{"id":"bold","value":true}]},{"id":"statistics","value":false},{"id":"biome","value":false},{"id":"entities","value":false},{"id":"armor","value":true},{"id":"ttf","value":false},{"id":"baritone","value":false},{"id":"time","value":"NONE"}]}
    </details>
    <details> 
      <summary><strong>Main Menu</strong></summary>

    {"name":"mainmenu","state":true,"bind":"NONE","display":false,"values":[{"id":"custom","value":false},{"id":"custombackground","value":false,"values":[{"id":"image","value":"0"},{"id":"random","value":false}]},{"id":"hidetext","value":false}]}
	</details>
- Operating System: Windows 10 64bit
</details>

**Additional context**
[Donator, or above, features like ignite or cape still function normally](https://i.imgur.com/3LZAPme.gifv)

**Comment by LeafHacker** [comment]
This is due to ImpactDevelopment/ImpactServer#33 not being merged yet

**Comment by S-B99** [comment]
Closed as it is now merged.

**Comment by LeafHacker** [comment]
Note: old nightlies will no longer show an Edition; stable builds and the latest nightly will though
