### ISSUE TITLE
Crash (With Log)

### ISSUE THREAD

**Issue by sTiKyt** [ImpactDevelopment/ImpactIssues#2085]
**Describe the bug**
Game sometimes crash when you open any Inventory.

**To Reproduce**
1. Go to any inventory
2. Click on any item, drag & drop it
3. Maybe you're lucky, but usually it causes game to crash

**Expected behavior**
I want it to work properly...

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/24/20 2:32 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.impactclient.0xi.0(0xi.java:20)
	at net.impactclient.0xi$$Lambda$888/421374777.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$423/1616042314.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.0e.post(0e.java:6)
	at net.minecraft.client.gui.FontRenderer.localvar$getStringWidth$zzf000(FontRenderer.java:941)
	at net.minecraft.client.gui.FontRenderer.func_78256_a(FontRenderer.java)
	at squeek.appleskin.client.TooltipOverlayHandler.onRenderTooltip(TooltipOverlayHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_TooltipOverlayHandler_onRenderTooltip_PostText.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.0xi.0(0xi.java:20)
	at net.impactclient.0xi$$Lambda$888/421374777.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$423/1616042314.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.0e.post(0e.java:6)
	at net.minecraft.client.gui.FontRenderer.localvar$getStringWidth$zzf000(FontRenderer.java:941)
	at net.minecraft.client.gui.FontRenderer.func_78256_a(FontRenderer.java)
	at squeek.appleskin.client.TooltipOverlayHandler.onRenderTooltip(TooltipOverlayHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_TooltipOverlayHandler_onRenderTooltip_PostText.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (510, 299). Absolute: (1020, 481)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Xx_JarikGOOD_xX'/4127, l='MpServer', x=2405.68, y=64.00, z=-235.35], EntityOtherPlayerMP['_sTiKyt_'/287171, l='MpServer', x=2416.66, y=64.00, z=-235.28]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-92,64,-180), Chunk: (at 4,4,12 in -6,-12; contains blocks -96,0,-192 to -81,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 106755 game time, 25135619 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntityPlayerSP['Xx_JarikGOOD_xX'/4127, l='MpServer', x=2405.68, y=64.00, z=-235.35], EntityOtherPlayerMP['_sTiKyt_'/287171, l='MpServer', x=2416.66, y=64.00, z=-235.28], EntityOtherPlayerMP['_sTiKyt_'/287171, l='MpServer', x=2416.66, y=64.00, z=-235.28], EntitySkeleton['Скелет'/221167, l='MpServer', x=2401.49, y=54.00, z=-235.26], EntityArmorStand['Стійка для броні'/221166, l='MpServer', x=2401.50, y=63.00, z=-233.50], EntitySkeleton['Скелет'/283465, l='MpServer', x=2403.50, y=28.00, z=-221.50], EntityCreeper['Кріпер'/221171, l='MpServer', x=2402.64, y=27.00, z=-216.69], EntityArmorStand['Стійка для броні'/221170, l='MpServer', x=2400.50, y=64.00, z=-246.50], EntityItem['item.tile.sapling.oak'/355156, l='MpServer', x=2425.26, y=71.00, z=-227.61], EntityZombie['Зомбі'/221169, l='MpServer', x=2402.77, y=42.00, z=-251.50], EntityItem['item.tile.sapling.oak'/349046, l='MpServer', x=2425.15, y=64.00, z=-232.61], EntityCreeper['Кріпер'/221173, l='MpServer', x=2400.15, y=39.00, z=-222.53], EntityArmorStand['Стійка для броні'/221179, l='MpServer', x=2399.50, y=65.00, z=-246.50], EntitySkeleton['Скелет'/221178, l='MpServer', x=2387.28, y=81.00, z=-216.51], EntityItem['item.tile.sapling.oak'/349311, l='MpServer', x=2419.59, y=64.00, z=-230.46], EntityCreeper['Кріпер'/221177, l='MpServer', x=2387.52, y=54.00, z=-223.23], EntityZombieVillager['Зомбі-селянин'/315646, l='MpServer', x=2383.75, y=32.00, z=-253.57], EntityMinecartChest['Вагонетка зі скринею'/221183, l='MpServer', x=2409.50, y=36.06, z=-258.50], EntityItem['item.tile.sapling.oak'/337784, l='MpServer', x=2422.88, y=64.00, z=-219.86], EntityCaveSpider['Печерний павук'/221181, l='MpServer', x=2418.37, y=27.00, z=-254.35], EntityPig['Свиня'/221180, l='MpServer', x=2384.43, y=105.00, z=-259.25]]
	Retry entities: 0 total; []
	Server brand: BotFilter (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:0b124d1:unknown) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 13378996704 bytes (12759 MB) / 13790871552 bytes (13152 MB) up to 20031995904 bytes (19104 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx19074M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version      | Source                                  | Signature                                |
	|:------ |:-------------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp                        | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar           | None                                     |
	| LCHIJA | forge                      | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar           | None                                     |
	| LCHIJA | jei                        | 4.15.0.291   | jei_1.12.2-4.15.0.291.jar               | None                                     |
	| LCHIJA | appleskin                  | 1.0.9        | AppleSkin-mc1.12-1.0.9.jar              | None                                     |
	| LCHIJA | betterhud                  | 1.4.1        | betterhud-1.12.2-1.4.1.jar              | None                                     |
	| LCHIJA | blockdrops                 | 1.4.0        | blockdrops-1.12.2-1.4.0.jar             | None                                     |
	| LCHIJA | clarity                    | 1.1          | clarity-1.1.jar                         | None                                     |
	| LCHIJA | craftingtweaks             | 8.1.9        | CraftingTweaks_1.12.2-8.1.9.jar         | None                                     |
	| LCHIJA | fastbench                  | 1.7.3        | FastWorkbench-1.12.2-1.7.3.jar          | None                                     |
	| LCHIJA | waila                      | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar             | None                                     |
	| LCHIJA | jeiintegration             | 1.5.1.36     | jeiintegration_1.12.2-1.5.1.36.jar      | None                                     |
	| LCHIJA | journeymap                 | 1.12.2-5.7.0 | journeymap-1.12.2-5.7.0.jar             | None                                     |
	| LCHIJA | jeresources                | 0.9.2.60     | JustEnoughResources-1.12.2-0.9.2.60.jar | None                                     |
	| LCHIJA | modnametooltip             | 1.10.1       | modnametooltip_1.12.2-1.10.1.jar        | None                                     |
	| LCHIJA | moreoverlays               | 1.15.1       | moreoverlays-1.15.1-mc1.12.2.jar        | None                                     |
	| LCHIJA | mousetweaks                | 2.10         | MouseTweaks-2.10-mc1.12.2.jar           | None                                     |
	| LCHIJA | neat                       | 1.4-17       | Neat+1.4-17.jar                         | None                                     |
	| LCHIJA | scenter                    | 1.12-3.11.0  | scenter-1.12.2-3.12.0.jar               | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4          | tlskincape_1.12.2-1.4.jar               | None                                     |
	| LCHIJA | wawla                      | 2.6.274      | Wawla-1.12.2-2.6.274.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | wts                        | 1.1.0        | WTS-1.1.0.jar                           | None                                     |

	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4821' Renderer: 'Intel(R) HD Graphics 530'
	Launched Version: Forge 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4821, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: Українська (Україна)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: <4.8.3 for 1.12.2 
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods:Doesn't matter, crash happens anyway(Even when everything is disabled
- Operating System: Happened on 2 systems, Arch Linux & Windows 10

</details>

**Additional context**

**Comment by MightyKnight** [comment]
Impact does not officially support Forge. Your crash is likely caused by some Forge mod.

Install Impact without Forge, if it still crashes, create a new report.

**Comment by sTiKyt** [comment]
But there's no way to say which mod may be reason?

**Comment by sTiKyt** [comment]
I wasn't able to install it without forge because of bugs with MultiMC

**Comment by S-B99** [comment]
That's not baritones fault. You can check the log to see which mod caused it.
