### ISSUE TITLE
[Nightlies] Provide user feedback if account is non-donator

### ISSUE THREAD

**Issue by MightyKnight** [ImpactDevelopment/ImpactIssues#2113]
**Is your feature request related to a problem? Please describe.**
Currently Impact nightly just crashes when trying to start the game with a non-donator account. 
_This can be problematic when a user downloads the wrong installer or when a donator uses the wrong account._

It's less than ideal, because:
- it produces a **JVM crash** ([hs_err_pid14056.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4399583/hs_err_pid14056.log))
- confuses users and leads to a lot of invalid reports on Github/Discord
- doesn't inform about the cause of the crash

**Describe the solution you'd like**
Provide some form of user feedback that the account is not a donator:
> e.g.: You can only launch this version of Impact if your account has **donator status**.
Donate at https://impactclient.net/#donate.
If you think this message shouln't appear, go to our [Discord]() and aks for help there.

**This issue is for discussion on how to solve this problem. Some questions to think about:**
1. Where and how to display a message? (display ingame with all mods disabled OR force a normal minecraft crash and write it there)
2. Exact wording of the message

---

**Additional information**
<details> 
  <summary><strong>This is generated in the latest.log after in a wrong launch:</strong></summary>

```
Error getting Impact API token from minecraft login
java.io.IOException: /login/minecraft is not ok, it's 401
	at net.impactclient.1H.0(1H.java:18)
	at net.impactclient.0GE.<init>(0GE.java:36)
	at net.impactclient.75.1(75.java:10)
	at net.impactclient.0Ga.1(0Ga.java:22)
	at net.impactclient.32.0(32.java:9)
	at dbn.handler$init$zzp000(SourceFile:2518)
	at dbn.<init>(SourceFile:548)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
</details>

**Comment by MightyKnight** [comment]
**Pros for introducing a visible crash message**
- Users may be more likely to donate if they see the option to play 1.15.2-nightlies instead of being driven away because they think Impact doesn't work
- Less work for moderators and support on Discord/Github

**Comment by LeafHacker** [comment]
I agree the current solution is less than ideal. Personally, I think we should show a Minecraft GUI screen saying something like “Cannot authenticate Impact Account”.

**Comment by XPHonza** [comment]
that'd be hot af

**Comment by S-B99** [comment]
Instead of Cannot authenticate Impact account, which can be confusing to new users as they may think they need an Impact account to us it, when donating is the issue, it should be straight to the point and say something like "Error: Impact Premium launched without Premium account"

**Comment by LeafHacker** [comment]
> Instead of Cannot authenticate Impact account [it should] say something like "Error: Impact Premium launched without Premium account"

Maybe, however that isn't the only reason authentication could fail. For example the user could be offline.

**Comment by S-B99** [comment]
Oh tre.
