### ISSUE TITLE
Forge1.12.2 Impact-4.8.3-1.12.2.jar  conflict  BuildCraft

### ISSUE THREAD

**Issue by graytoowolf** [ImpactDevelopment/ImpactIssues#2163]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/11/20 2:50 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)
Caused by: java.lang.IllegalStateException: Scanning facade states
    State = minecraft:double_stone_slab[seamless=false,variant=quartz]
    Block = minecraft:double_stone_slab
    Stack = 1xtile.stoneSlab@7
    varying-properties: {
        PropertyBool{name=seamless, clazz=class java.lang.Boolean, values=[true, false]} = null
    }
	at buildcraft.silicon.plug.FacadeStateManager.scanBlock(FacadeStateManager.java:354)
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:213)
	at buildcraft.silicon.BCSilicon.init(BCSilicon.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
	at net.minecraft.block.Block.handler$isFullBlock$zbj000(Block.java:3203)
	at net.minecraft.block.Block.func_149730_j(Block.java)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185913_b(BlockStateContainer.java:299)
	at net.minecraft.block.Block.isSideSolid(Block.java:1071)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:516)
	at buildcraft.silicon.plug.FacadeBlockStateInfo.<init>(FacadeBlockStateInfo.java:41)
	at buildcraft.silicon.plug.FacadeStateManager.scanBlock(FacadeStateManager.java:319)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 495048568 bytes (472 MB) / 1723334656 bytes (1643 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2852 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                  | Signature                                |
	|:----- |:------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft           | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHI  | mcp                 | 9.42         | minecraft.jar                           | None                                     |
	| LCHI  | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2852-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge               | 14.23.5.2852 | forge-1.12.2-14.23.5.2852-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | buildcraftlib       | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHI  | buildcraftcore      | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHI  | buildcraftbuilders  | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHI  | buildcrafttransport | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHE  | buildcraftsilicon   | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 970/PCIe/SSE2'

**Comment by dominikaaaa** [comment]
Try uninstalling BuildCraft, that should fix the issue.
