### ISSUE TITLE
Installing with MultiMC for Impact 4.8.3 version 1.12.2 causes crash on launch

### ISSUE THREAD

**Issue by 9NONAGON** [ImpactDevelopment/ImpactIssues#2188]
**Describe the bug**
Installing Impact 4.8.3 for 1.12.2 for MultiMC crashes on launch

**To Reproduce**
1. Follow steps on https://github.com/ImpactDevelopment/ImpactIssues/wiki/Installing-with-MultiMC 

**Expected behavior**
"
![image](https://user-images.githubusercontent.com/41491518/79650776-cf2a4780-8176-11ea-95f5-92d07e039897.png)
"

```
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 18076


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
```

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.8.3
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  None
- Operating System:  Windows 10 x64

</details>

**Comment by dominikaaaa** [comment]
Use the official Minecraft launcher.

**Comment by 9NONAGON** [comment]
no

**Comment by LeafHacker** [comment]
https://github.com/MultiMC/MultiMC5/issues/2399

**Comment by Artoria2e5** [comment]
Reproduced using the official launcher with jdk14. The MultiMC bug says something about using j8 too, but given the cooool performance stuff in jdk14 (ZGC!) some fixing would be nice.

**Comment by dominikaaaa** [comment]
That's not impacts problem to fix, use jdk 8

**Comment by dominikaaaa** [comment]
Minecraft 1.12.2 only supports up to jdk 11 iirc
