### ISSUE TITLE
Game Crashing When Joining Server(This time i filled the template lol)

### ISSUE THREAD

**Issue by Memz-idk** [ImpactDevelopment/ImpactIssues#2193]
**Describe the bug**
Basically the Game just crashes when joining some servers

**To Reproduce**
1. Open the game
2. Join a server
3. Profit

**Expected behavior**
The game not crashing?

**Screenshots**
http://prntscr.com/s2xde2

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 20/04/20 17:56
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at dke.m(SourceFile:281)
	at dke.d(SourceFile:260)
	at cyc.m(SourceFile:1380)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dke.m(SourceFile:281)
	at dke.d(SourceFile:260)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 729, 22
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5117262 game time, 5388643 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3901387072 bytes (3720 MB) / 4496293888 bytes (4288 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3/1.14.4
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None/Doesn't Affect the Crash
- Operating System: Win 10

</details>

**Additional context**
This only happens in some servers not all servers

**Comment by Aaron2550** [comment]
Probably not the solution: Update java, newest is 1.8-241, you have 1.8-51

**Comment by dominikaaaa** [comment]
8u51 is provided by the mc launcher on windows, but yes updating Java usually fixes it.
