### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by VerseOW** [ImpactDevelopment/ImpactIssues#2232]
Game crashes

**To Reproduce**
1. Go to 2b2t
2. Either get in and play or sometimes in queue you get crashed too (Might've fixed the queue thing with switching to non optifine though, but not sure)
3. Crash

**Expected behavior**
Should be able to play

<details> 
  <summary><strong>Game output</strong></summary>
 

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 4/30/20 10:23 PM
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index: 42, Size: 38
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at afr.a(SourceFile:197)
	at bsa.a(SourceFile:422)
	at net.impactclient.15.0(15.java:43)
	at net.impactclient.8D.0(8D.java:17)
	at net.impactclient.8D$$Lambda$443/585691212.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$107/650613770.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.0e.post(0e.java:6)
	at bud.handler$onPreUpdate$zzd000(SourceFile:1162)
	at bud.B_(SourceFile)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)
	at amu.k(SourceFile:1382)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at afr.a(SourceFile:197)
	at bsa.a(SourceFile:422)
	at net.impactclient.15.0(15.java:43)
	at net.impactclient.8D.0(8D.java:17)
	at net.impactclient.8D$$Lambda$443/585691212.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$107/650613770.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.0e.post(0e.java:6)
	at bud.handler$onPreUpdate$zzd000(SourceFile:1162)
	at bud.B_(SourceFile)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)

-- Entity being ticked --
Details:
	Entity Type: null (bud)
	Entity ID: 35
	Entity Name: NOT SHOWING
	Entity's Exact location: NOT SHOWING 
	Entity's Block location: World: NOT SHOWING
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at amu.k(SourceFile:1382)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bud['NO'/35, l='MpServer', x=NO, y=NO, z=NO]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 110523 game time, 2104109317 day time
	Level dimension: NO
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 4 total; [bud['NO'/35, l='MpServer', x=NO, y=NO, z=NO], acs['Creeper'/1709377, l='MpServer', x=NO, y=NO, z=NO], aag['Sheep'/1708678, l='MpServer', x=NO, y=NO, z=NO], adt['Zombie'/1713733, l='MpServer', x=NO, y=NO, z=NO]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327) <- 2b2t
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bsb.a(WorldClient.java:532)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:428)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 625472320 bytes (596 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.12.2-Impact_4.8.3-OptiFine_HD_U_D3
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: Hi ) (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor  

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Anti Bot, Criticals, Auto Eat, Auto Tool, Item Saver, Respawn, Anti Blind, Click GUI, Crosshair+, ESP, HUD, Light, Main Menu, Nametags, Search, Storage ESP, Tracers, No Push, Anti Hunger, New Chunks, Auto Cheat, Auto Reconnect
- Operating System: Windows 10: 64 bit

</details>

**Additional context**
I also don't know if this has anything to do with it but it always seems to be when I'm interacting with an enchantment table, not the first time I use it but I'll usually use it around ten times, go to get more Exp again like usual, then randomly one of the next times I use it, it crashes, idk if it's a coincidence cause that's mainly what I'm focusing on right now so it takes up the majority of the time I play right now, or if it's the actual issue.

**Comment by VerseOW** [comment]
Replaced names and coords with NO and NOT SHOWING btw

**Comment by LeafHacker** [comment]
> or sometimes in queue you get crashed too

Note: the crash this user has experianced in queue is _unrelated_ to the crash described here. There is a seperate crash report in #2229

**Comment by VerseOW** [comment]
It's deffo something to do with enchanting as I just played for over four hours with no crash, the only thing I did differently was not enchant
