### ISSUE TITLE
When i try to run java -jar installer.jar i get a white screen

### ISSUE THREAD

**Issue by patoacriano** [ImpactDevelopment/ImpactIssues#2258]
java.nio.file.NoSuchFileException: /home/eu/.minecraft/Impact/cid.txt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at io.github.ImpactDevelopment.installer.utils.Tracky.<clinit>(Tracky.java:57)
        at io.github.ImpactDevelopment.installer.Installer.main(Installer.java:71)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sending event category=installer action=display label=null cid=e121d588-f2d8-4c62-a40c-9558482b69ea
Fetching releases from ImpactDevelopment/ImpactReleases
DOWNLOADING http://impactclient.net/releases.json

**Comment by dominikaaaa** [comment]
Use oracle JDK
