### ISSUE TITLE
Crashing when openin minecraft

### ISSUE THREAD

**Issue by kindofmushroom** [ImpactDevelopment/ImpactIssues#2262]
When I want to play Minecraft without mods, I have no problems, but when I install any version of the impact client I get this crash problem. I tried to play minecraft with impact two another pc, and i got same crash issue. My minecraft account is premium it's not cracked. When I looked at the Issues page, I saw that Turkish users had the same problem. I tried java 8 u241, java 8 u251 versions. 
**To Reproduce**
1. Go to '....'

**Expected behavior**
I want the problem to be solved.

**Screenshots**
https://prnt.sc/sd7qx6

<details> 
  <summary><strong>Game output</strong></summary>
 

I just pasted warns(3), errors(48), fatal(2), no infos and debug.
```
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.15.2/1.15.2.jar
11:42:36.246
Have local file C:\Users\User\AppData\Roaming\.minecraft\versions\1.15.2\1.15.2.jar but don't know what size or hash it should be. Have to assume it's good.
11:42:37.883
Mixin config mixins.impact.json does not specify "minVersion" property
11:42:37.895
Mixin config mixins.baritone.json does not specify "minVersion" property
11:42:38.191
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinArmorLayer, name: clientapi.load.mixin.MixinArmorLayer
11:42:38.269
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlockMode, name: clientapi.load.mixin.MixinBlockMode
11:42:38.275
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBossOverlayGui, name: clientapi.load.mixin.MixinBossOverlayGui
11:42:38.281
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayerEntity, name: clientapi.load.mixin.MixinClientPlayerEntity
11:42:38.308
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayNetHandler, name: clientapi.load.mixin.MixinClientPlayNetHandler
11:42:38.345
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
11:42:38.381
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
11:42:38.386
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRendererManager, name: clientapi.load.mixin.MixinEntityRendererManager
11:42:38.392
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFirstPersonRenderer, name: clientapi.load.mixin.MixinFirstPersonRenderer
11:42:38.402
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFogRenderer, name: clientapi.load.mixin.MixinFogRenderer
11:42:38.406
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
11:42:38.414
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGameRenderer, name: clientapi.load.mixin.MixinGameRenderer
11:42:38.422
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinIngameGui, name: clientapi.load.mixin.MixinIngameGui
11:42:38.429
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
11:42:38.434
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinKeyboardListener, name: clientapi.load.mixin.MixinKeyboardListener
11:42:38.439
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLivingEntity, name: clientapi.load.mixin.MixinLivingEntity
11:42:38.461
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
11:42:38.491
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMouseHelper, name: clientapi.load.mixin.MixinMouseHelper
11:42:38.495
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
11:42:38.497
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
11:42:38.500
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
11:42:38.507
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinOverlayRenderer, name: clientapi.load.mixin.MixinOverlayRenderer
11:42:38.510
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
11:42:38.516
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
11:42:38.520
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinSpectatorGui, name: clientapi.load.mixin.MixinSpectatorGui
11:42:38.523
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
11:42:38.527
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinWorldRenderer, name: clientapi.load.mixin.MixinWorldRenderer
11:42:38.729
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBitArray, name: baritone.launch.mixins.MixinBitArray
11:42:38.738
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkArray, name: baritone.launch.mixins.MixinChunkArray
11:42:38.741
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientChunkProvider, name: baritone.launch.mixins.MixinClientChunkProvider
11:42:38.745
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayerEntity, name: baritone.launch.mixins.MixinClientPlayerEntity
11:42:38.748
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayNetHandler, name: baritone.launch.mixins.MixinClientPlayNetHandler
11:42:38.750
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinCommandSuggestionHelper, name: baritone.launch.mixins.MixinCommandSuggestionHelper
11:42:38.754
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntity, name: baritone.launch.mixins.MixinEntity
11:42:38.757
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderManager, name: baritone.launch.mixins.MixinEntityRenderManager
11:42:38.759
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
11:42:38.762
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLivingEntity, name: baritone.launch.mixins.MixinLivingEntity
11:42:38.765
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLootContext, name: baritone.launch.mixins.MixinLootContext
11:42:38.769
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
11:42:38.771
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
11:42:38.773
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPalettedContainer, name: baritone.launch.mixins.MixinPalettedContainer
11:42:38.777
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerController, name: baritone.launch.mixins.MixinPlayerController
11:42:38.780
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinScreen, name: baritone.launch.mixins.MixinScreen
11:42:38.785
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinWorldRenderer, name: baritone.launch.mixins.MixinWorldRenderer
11:42:40.073
Injection warning: LVT in akq::e(Lcvl;)Lcvl; has incompatible changes at opcode 148 in callback akq::handler$getAllowedMovement$development$zcd000.
Expected: [Lcvf;, Lcvq;, Lcwf;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Labt;, Lcvl;, Z, Z, Z, Z]
   Found: [Lcvf;, Lcvq;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Labt;, Lcvl;, Z, Z, Z, Z]
11:42:40.231
Mixin apply failed mixins.impact.json:accessor.AccessorPlayerEntity -> ayj: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching ınventory:Layi; in ayj for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Layi;)V
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ınventory:Layi; in ayj for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Layi;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947)
	at 
org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        11:42:40.250
Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: dqb
	at net.minecraft.client.main.Main.main(SourceFile:174)
	... 6 more
Caused by: java.lang.ClassNotFoundException: dqb
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
  11:42:40.324
Caught previously unhandled exception :
java.lang.NoClassDefFoundError: dqb
	at net.minecraft.client.main.Main$2.run(SourceFile:143)
Caused by: java.lang.ClassNotFoundException: dqb
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
11:42:40.391
Process crashed with exit code 1
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
--- There is no crash report file ---
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.15.2 all nightly versions, impact 4.8 for 1.14.4(not nightly)
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: -
- Operating System: Windows 8.1

</details>

**Additional context**

**Comment by kindofmushroom** [comment]
There are too many people experiencing the same problem, but no one has found a real solution to the issue.

**Comment by TheChickenBros** [comment]
I have this same problem when using version 8.3 or whatever. Just use the version that ends with a two for now.

**Comment by kindofmushroom** [comment]
> " Just use the version that ends with a two for now."
I don't get it, what do you mean? Sorry.

**Comment by kindofmushroom** [comment]
Hey! I solved. I created new user in my computer, then i changed language Turkish to English. After all, i installed impact and it's worked.

**Comment by LeafHacker** [comment]
Duplicate of #2228
