### ISSUE TITLE
Game crashes when alts tab is clicked

### ISSUE THREAD

**Issue by darkdarc21** [ImpactDevelopment/ImpactIssues#2284]
I'm using impact 4.8.3 on mac and whenever I open the alts tab my screen changes to saving world then my game crashes.

**To Reproduce**
1. Go to Minecraft home screen
2. Click on impact button
3. Click on alts

**Expected behavior**
It is supposed to open the alts menu.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 15/05/20 9:01 AM
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at net.impactclient.9j.7(9j.java:6)
	at net.impactclient.7t.init(7t.java:168)
	at dcl.init(SourceFile:330)
	at cyc.a(SourceFile:830)
	at net.impactclient.3J.8(3J.java:6)
	at czi.onPress(SourceFile:18)
	at czd.onClick(SourceFile:15)
	at czg.mouseClicked(SourceFile:154)
	at dad.mouseClicked(SourceFile:27)
	at cyd.b(SourceFile:86)
	at dcl.wrapScreenError(SourceFile:441)
	at cyd.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3129)
	at cuo.c(MainWindow.java:358)
	at cyc.b(SourceFile:1027)
	at cyc.e(SourceFile:976)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.9j.7(9j.java:6)
	at net.impactclient.7t.init(7t.java:168)
	at dcl.init(SourceFile:330)
	at cyc.a(SourceFile:830)
	at net.impactclient.3J.8(3J.java:6)
	at czi.onPress(SourceFile:18)
	at czd.onClick(SourceFile:15)
	at czg.mouseClicked(SourceFile:154)
	at dad.mouseClicked(SourceFile:27)
	at cyd.b(SourceFile:86)

-- Affected screen --
Details:
	Screen name: net.impactclient.3J
Stacktrace:
	at dcl.wrapScreenError(SourceFile:441)
	at cyd.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3129)
	at cuo.c(MainWindow.java:358)
	at cyc.b(SourceFile:1027)
	at cyc.e(SourceFile:976)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1688894008 bytes (1610 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.3-OptiFine_HD_U_F4_pre2
	LWJGL: 3.2.1 build 12
	OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-12.10.12, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3 - 1.14.4
- Using Optifine? Yes 
- Using LiteLoader? No
- Enabled mods: Yes
- Operating System: Macos (Mojave)

</details>

**Comment by LeafHacker** [comment]
Why was this closed?

**Comment by darkdarc21** [comment]
> Why was this closed?

After reinstalling impact 5 times the issue went away.

**Comment by dominikaaaa** [comment]
# x
