### ISSUE TITLE
Game crashing without even loading.

### ISSUE THREAD

**Issue by bubzer** [ImpactDevelopment/ImpactIssues#2345]
When I'm starting the game, (impact 1.15.2) it automatically closes, with errorlog of:

Unable to launch
java.lang.ClassNotFoundException: clientapi.load.ClientTweaker
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

My sistem is:
R2700X
32GB RAM
Aorus X470 Gaming 5 Wi-Fi

**Comment by Fokz210** [comment]
I have that bug too, but on some launchers (like tlauncher.org) it is starting normally, but without mods. With mods i am having same issue

**Comment by ScanmanTM** [comment]
Follow the template.
_This may help: Use versions 0527 or lower_
