### ISSUE TITLE
Nightly 20200529

### ISSUE THREAD

**Issue by KillaMeep** [ImpactDevelopment/ImpactIssues#2346]
running 1.15.2 nightly and it crashes with this log:

[18:44:24]` [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[18:44:24] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: clientapi.load.ClientTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by ScanmanTM** [comment]
Use versions 0527 or lower
