### ISSUE TITLE
Nightly/minecraft Crashses when starting nightly 1.12.2

### ISSUE THREAD

**Issue by Qazzman987** [ImpactDevelopment/ImpactIssues#2368]
**Describe the bug**
When i start up Nightly 1.12.2 it crahses minecraft then it says "Error Game crashed An unexpected issue occurred and the game has crashed. We're sorry for the inconveience."

**To Reproduce**
1. Start the minecraft launcher.
2. Chossen impact nightly for 1.12.2
3. Press play
4. It starts up and crashes and then you can see it crash.

**Expected behavior**
I would expect it to start up normaly.

**Screenshots**
![Skärmbild (1)](https://user-images.githubusercontent.com/66552070/83965818-a55bea00-a8b6-11ea-91cb-24410636e4f8.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
12:05:59.564
Launching wrapped minecraft {net.minecraft.client.main.Main}
12:05:59.975
Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: bud
	at net.minecraft.client.main.Main.main(SourceFile:38)
	... 6 more
Caused by: java.lang.ClassNotFoundException: bud
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: bua
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 9 more
Caused by: java.lang.ClassNotFoundException: bua
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 15 more
Caused by: java.lang.NegativeArraySizeException
	at org.spongepowered.asm.lib.Frame.merge(Frame.java:1447)
	at org.spongepowered.asm.lib.MethodWriter.visitMaxs(MethodWriter.java:1516)
	at org.spongepowered.asm.lib.tree.MethodNode.accept(MethodNode.java:835)
	at org.spongepowered.asm.lib.tree.MethodNode.accept(MethodNode.java:727)
	at org.spongepowered.asm.lib.tree.ClassNode.accept(ClassNode.java:412)
	at org.spongepowered.asm.transformers.TreeTransformer.writeClass(TreeTransformer.java:82)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.writeClass(MixinTransformer.java:809)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.writeClass(MixinTransformer.java:803)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:715)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 18 more
12:06:00.051

12:06:00.051
Process crashed with exit code 1
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? <-- No -->
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
Works with other versions of minecraft like 1.15.2 (with nightly)

**Comment by Qazzman987** [comment]
Sadly no crash report.

**Comment by ScanmanTM** [comment]
update to 606 
### **:)**
