### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Qazzman987** [ImpactDevelopment/ImpactIssues#2438]
**Describe the bug**
Starting up impact nightly 20200613 and crashes.

**To Reproduce**
1. download impact nightly 20200613
2. Click on 'play'
3. See error

**Expected behavior**
start up normaly.

**Screenshots**
![Skärmklipp](https://user-images.githubusercontent.com/66552070/84596772-ec6e5000-ae5f-11ea-9895-32c3cc6d4971.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
16:57:01.715
Unable to load spam config file: Spam config file is in invalid format
16:57:02.459

---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-06-14 16:57
Description: Initializing game

java.util.regex.PatternSyntaxException: Unclosed character class near index 0
[
^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.clazz(Pattern.java:2548)
	at java.util.regex.Pattern.sequence(Pattern.java:2063)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2368)
	at java.lang.String.split(String.java:2410)
	at net.impactclient.03.2(03.java:52)
	at net.impactclient.03$$Lambda$2524/81418318.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.03.1(03.java:31)
	at net.impactclient.0hv.0(0hv.java:85)
	at net.impactclient.2X.0(2X.java:7)
	at dbn.handler$init$zzp000(SourceFile:2535)
	at dbn.<init>(SourceFile:548)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.clazz(Pattern.java:2548)
	at java.util.regex.Pattern.sequence(Pattern.java:2063)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2368)
	at java.lang.String.split(String.java:2410)
	at net.impactclient.03.2(03.java:52)
	at net.impactclient.03$$Lambda$2524/81418318.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.03.1(03.java:31)
	at net.impactclient.0hv.0(0hv.java:85)
	at net.impactclient.2X.0(2X.java:7)
	at dbn.handler$init$zzp000(SourceFile:2535)
	at dbn.<init>(SourceFile:548)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4216382080 bytes (4021 MB) / 5268045824 bytes (5024 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2-Impact_nightly-20200613
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Qazzman\AppData\Roaming\.minecraft\crash-reports\crash-2020-06-14_16.57.01-client.txt
16:57:02.471
Process crashed with exit code -1
```

</details>
output yea
<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[crash-2020-06-14_17.01.44-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4776669/crash-2020-06-14_17.01.44-client.txt)


```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
works for 1.14.4.

**Comment by Qazzman987** [comment]
Impact Version: Nightly 20200613
    Using Optifine no
    Using LiteLoader no
    Enabled mods: none
    Operating System: win 10 64 bit
