### ISSUE TITLE
Touch Screen UI Crash

### ISSUE THREAD

**Issue by aytimothy** [ImpactDevelopment/ImpactIssues#2467]
It looks like there is a bug in the UI code to do with user input. If you attempt to click any Impact-related menu with a touchscreen, the game will crash and you'll get a `java.lang.NullPointerException`.

Does not happen when pressing stuff with a touchscreen in any vanilla menu.

* Game Version: **1.12.2**

You can reproduce it by:

1. (Using a mouse, obviously) Click "Impact" in the Main Menu (or Pause Screen).
2. Click any button by tapping on it with your touchscreen.
3. ???
4. Crash.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/23/20 12:26 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.impactclient.5k.func_146284_a(5k.java:52)
	at net.minecraft.client.gui.GuiScreen.redirect$actionPerformed$zee000(GuiScreen.java:738)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.impactclient.5k.func_73864_a(5k.java:14)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552)

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.6.1
	Minecraft version: Minecraft 1.12.2 (forge-14.23.5.2854/fml,forge,LiteLoader/Forge)
	Expected version: 1.12.2
	Protocol version: 340
	Data version: 1343
	File location: ~~ERROR~~ IllegalArgumentException: URI is not hierarchical
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at net.minecraft.crash.CrashReportCategory.func_85073_a(CrashReportCategory.java:116)
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:292)
	at wdl.WDL.addInfoToCrash(WDL.java:1643)
	at wdl.WDLEvents$HooksListener.onCrashReportPopulateEnvironment(WDLEvents.java:795)
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:181)
	at net.minecraft.crash.CrashReport.handler$onCrashReportPopulateEnvironment$zfi000(CrashReport.java:532)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:40)
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:359)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@ea30797 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@ea30797 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: net.minecraft.client.Minecraft@669a0f3e
	worldClient: net.minecraft.client.multiplayer.WorldClient@2ddcaa2c
	networkManager: net.minecraft.network.NetworkManager@290c0892
	player: EntityPlayerSP['aytimothy'/14092, l='MpServer', x=-2.17, y=244.69, z=2.01]
	windowContainer: net.minecraft.inventory.ContainerPlayer@59b0596f
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	entityPositions: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: true
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: 
	baseFolderName: 2b2t_org
	serverProps: wdl.config.Configuration@4acca64d
	worldProps: wdl.config.Configuration@4acca64d
	globalProps: wdl.config.Configuration@279061bf
	defaultProps: wdl.config.DefaultConfiguration@1145698c
	gameRules: net.minecraft.world.GameRules@4ae521ea

-- World Downloader Mod - Server properties --
Details:
	LinkedWorlds: 
	LastSaved: 1592802204373
	RandomSeed: 

-- World Downloader Mod - World properties --
Details:
	LinkedWorlds: 
	LastSaved: 1592802204373
	RandomSeed: 

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: W/"0a3c704f8508344c98591cad5798318d"

-- Sanity checks --
Details:
	TRIPWIRE: Passed
	VERSION: Passed
	TRANSLATION: Passed
	MIXIN_INVENTORYBASIC: Passed
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: Passed
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: Passed
	ENCODING: Passed

-- Affected screen --
Details:
	Screen name: net.impactclient.5k

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['aytimothy'/14092, l='MpServer', x=-2.17, y=244.69, z=2.01]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,256,0), Chunk: (at 0,16,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 50816 game time, 20400 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['aytimothy'/14092, l='MpServer', x=-2.17, y=244.69, z=2.01]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346) <- 2b2t
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1778390208 bytes (1696 MB) / 3898081280 bytes (3717 MB) up to 6681526272 bytes (6372 MB)
	LiteLoader Brand: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
	LiteLoader Mods: 1 loaded mod(s)
          - LiteModWDL version 4.0.6.1-1.12.2
	LaunchWrapper: 24 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PotionEffectTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7168m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version      | Source                        | Signature                                |
	|:------ |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp        | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | journeymap | 1.12.2-5.7.1 | journeymap-1.12.2-5.7.1.jar   | None                                     |
	| LCHIJA | reauth     | 3.6.0        | reauth-3.6.0.jar              | daba0ec4df71b6da841768c49fb873def208a1e3 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6293' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.5.0 - Build 24.20.100.6293, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
```

**Comment by dominikaaaa** [comment]
do people seriously use impact with a touch screen

**Comment by aytimothy** [comment]
> do people seriously use impact with a touch screen

Nope, I just accidentally touch the screen from time to time. I'm primarily a keyboard+mouse.

**Comment by dominikaaaa** [comment]
bruh I just have my touch screen disabled
