### ISSUE TITLE
Impact crashes each time I try and make a macro.

### ISSUE THREAD

**Issue by Radzoweb** [ImpactDevelopment/ImpactIssues#2477]
---- Minecraft Crash Report ----
// My bad.

Time: 25/06/20 12:27 PM
Description: mouseClicked event handler

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.impactclient.0Ya.1(0Ya.java:54)
	at net.impactclient.0Ya.<init>(0Ya.java:38)
	at net.impactclient.6g.init(6g.java:15)
	at dgb.init(SourceFile:338)
	at dbn.a(SourceFile:863)
	at net.impactclient.2Y.1(2Y.java:25)
	at dcv.onPress(SourceFile:18)
	at dcq.onClick(SourceFile:15)
	at dct.mouseClicked(SourceFile:150)
	at ddr.mouseClicked(SourceFile:27)
	at dbo.b(SourceFile:86)
	at dgb.wrapScreenError(SourceFile:447)
	at dbo.a(SourceFile:86)
	at dbo.c(SourceFile:150)
	at ais.execute(SourceFile:94)
	at dbo.b(SourceFile:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)
	at cxx.e(SourceFile:301)
	at dbn.d(SourceFile:1012)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.impactclient.0Ya.1(0Ya.java:54)
	at net.impactclient.0Ya.<init>(0Ya.java:38)
	at net.impactclient.6g.init(6g.java:15)
	at dgb.init(SourceFile:338)
	at dbn.a(SourceFile:863)
	at net.impactclient.2Y.1(2Y.java:25)
	at dcv.onPress(SourceFile:18)
	at dcq.onClick(SourceFile:15)
	at dct.mouseClicked(SourceFile:150)
	at ddr.mouseClicked(SourceFile:27)
	at dbo.b(SourceFile:86)

-- Affected screen --
Details:
	Screen name: net.impactclient.2Y
Stacktrace:
	at dgb.wrapScreenError(SourceFile:447)
	at dbo.a(SourceFile:86)
	at dbo.c(SourceFile:150)
	at ais.execute(SourceFile:94)
	at dbo.b(SourceFile:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

-- Affected level --
Details:
	All players: 1 total; [dqb['RadPower1'/109, l='MpServer', x=26.30, y=68.00, z=-364.70]]
	Chunk stats: Client Chunk Cache: 361, 225
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 8962414195576017367
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (26,63,-348), Chunk: (at 10,3,4 in 1,-22; contains blocks 16,0,-352 to 31,255,-337), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 133606 game time, 942103 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(SourceFile:450)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:634)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 416371280 bytes (397 MB) / 973078528 bytes (928 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.15.2-Impact_4.9.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 26.20.100.7757, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/3D-Noteblock-Displays-1.15-V2.2.zip, file/OpenInventoryGUI.zip (incompatible), file/bare-bones-e610.zip, file/red.zip, file/seamless-glass-syh.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by dominikaaaa** [comment]
fill out the template

**Comment by Radzoweb** [comment]
what template?

**Comment by dominikaaaa** [comment]
the template that comes up when you make a new issue
