### ISSUE TITLE
crashing on start :/

### ISSUE THREAD

**Issue by AbsoluteBananas** [ImpactDevelopment/ImpactIssues#2555]
The client is crashing on start
it gives an error message (see screenshots)

**To Reproduce**
idk

**Expected behavior**
i want the client to start
**Screenshots**
![image](https://user-images.githubusercontent.com/69084690/89105430-f1d82780-d418-11ea-8356-c3ebd6a28516.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: n/a
- Operating System: Windows 10 64 bit

</details>

**Additional context**
idk what all the output stuff is, im not a coder.
if someone could explain to me the steps, i'd be happy to follow them and show.

**Comment by ScanmanTM** [comment]
bro i am over fucking whelmed with the amount of information provided, had to scroll really far down to read all them logs you attached for us.

Attach your latest.log from .minecraft/logs.

**Comment by AbsoluteBananas** [comment]
[17:02:48] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[17:02:48] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[17:02:48] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[17:02:48] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[17:02:48] [main/INFO]: Injecting into ClassLoader
[17:02:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[17:02:48] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[17:02:48] [main/INFO]: Initialized Mixin bootstrap
[17:02:48] [main/INFO]: Setup Mixin Environment
[17:02:48] [main/INFO]: Compatibility level set to JAVA_8
[17:02:48] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[17:02:48] [main/INFO]: Loaded Mixin Configurations
[17:02:48] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[17:02:48] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[17:02:48] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[17:02:48] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[17:02:48] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more

**Comment by AbsoluteBananas** [comment]
sorry about the lack of logs, im not a tech man i just want to 2b2t lmao

**Comment by ScanmanTM** [comment]
Can you drag and drop the file itself?

**Comment by AbsoluteBananas** [comment]
ok

**Comment by AbsoluteBananas** [comment]
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5010911/latest.log)

**Comment by AbsoluteBananas** [comment]
there we are

**Comment by dominikaaaa** [comment]
is that seriously the entire file?

**Comment by AbsoluteBananas** [comment]
yh

Why?

**Comment by AbsoluteBananas** [comment]
srry i went somewhere

**Comment by dominikaaaa** [comment]
Because there isn't much to go off of. Make sure you're using JDK 8

**Comment by AbsoluteBananas** [comment]
whats jdk 8?

i heard of it somewhere but i dont have developer kit downloaded

**Comment by dominikaaaa** [comment]
https://www.oracle.com/java/technologies/javase-jdk8-downloads.html

Hopefully. I can't really tell as the log is weird

**Comment by AbsoluteBananas** [comment]
k

**Comment by AbsoluteBananas** [comment]
no, it still gives the error message

when you said the log is so small, it seems right because it takes about a second to load and then it says it's crashed

**Comment by AbsoluteBananas** [comment]
hello?

**Comment by AbsoluteBananas** [comment]
also dominikaaaa i saw u on the kami blue as credits
