### ISSUE TITLE
Non [a-z0-9/._-] character in path of location: minecraft:Cobblestone ("0004")

### ISSUE THREAD

**Issue by hotpiggycharlie** [ImpactDevelopment/ImpactIssues#2612]
**odd error**
random error when loading impact 1.15.2

**To Reproduce**
1. Go to impact 1.9 1.15.2
2. Click on play
3. See error
4. Start to cry

**Expected behavior**
run impact
 

```
The game crashed whilst initializing game
Error: r: Non [a-z0-9/._-] character in path of location: minecraft:Cobblestone ("0004")
Exit Code: -1
```
 

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 05/09/20 20:21
Description: Initializing game

r: Non [a-z0-9/._-] character in path of location: minecraft:Cobblestone ("0004")
	at sm.<init>(SourceFile:38)
	at sm.<init>(SourceFile:43)
	at net.impactclient.3F$$Lambda$2360/90285221.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.3F.1(3F.java:13)
	at net.impactclient.8R.<init>(8R.java:17)
	at net.impactclient.4K.1(4K.java:2)
	at net.impactclient.1L.0(1L.java:31)
	at net.impactclient.5q.0(5q.java:7)
	at dbn.handler$init$zzp000(SourceFile:2520)
	at dbn.<init>(SourceFile:548)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at sm.<init>(SourceFile:38)
	at sm.<init>(SourceFile:43)
	at net.impactclient.3F$$Lambda$2360/90285221.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.impactclient.3F.1(3F.java:13)
	at net.impactclient.8R.<init>(8R.java:17)
	at net.impactclient.4K.1(4K.java:2)
	at net.impactclient.1L.0(1L.java:31)
	at net.impactclient.5q.0(5q.java:7)
	at dbn.handler$init$zzp000(SourceFile:2520)
	at dbn.<init>(SourceFile:548)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 949517704 bytes (905 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2-Impact_4.9.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.14736 Compatibility Profile Context 20.8.1 27.20.2001.13001, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor 
```
 

- Impact Version: 4.9 for 1.15.2
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods:  non 
- Operating System: Windows 10 64bit

**Additional context**
i have tried to reinstall impact and the 1.12.2 version does work

**Comment by dominikaaaa** [comment]
Well for some reason you have `minecraft:Cobblestone` in a file path somewhere, you have to delete it.
