### ISSUE TITLE
minecraft crashes on launch

### ISSUE THREAD

**Issue by thatweirdkaden** [ImpactDevelopment/ImpactIssues#2642]
**Describe the bug**
(title)

**To Reproduce**
1. open impact on any version above 4.3.0
2. minecraft opens
3. minecraft dies then error'

**Expected behavior**
Impact loads with no problems whatsoever.

**Screenshots**
![image](https://user-images.githubusercontent.com/64016144/94378134-8a72e700-00ec-11eb-8fcf-60d19305ecf3.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
Exit Code: -1

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/27/20 5:57 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at net.impactclient.0aP.<clinit>(0aP.java:40)
	at net.impactclient.8P.2(8P.java:48)
	at net.impactclient.73.0(73.java:13)
	at net.impactclient.8P.<init>(8P.java:61)
	at net.impactclient.3V.1(3V.java:34)
	at net.impactclient.0ay.2(0ay.java:69)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at net.impactclient.0aP.<clinit>(0aP.java:40)
	at net.impactclient.8P.2(8P.java:48)
	at net.impactclient.73.0(73.java:13)
	at net.impactclient.8P.<init>(8P.java:61)
	at net.impactclient.3V.1(3V.java:34)
	at net.impactclient.0ay.2(0ay.java:69)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 109484928 bytes (104 MB) / 301989888 bytes (288 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.9.1
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by l1ving** [comment]
> java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)

Redownload Impact

**Comment by thatweirdkaden** [comment]
this is like the 7th time ive redownloaded impact and it still does it for versions over 4.3.0

**Comment by l1ving** [comment]
What OS?

**Comment by LIEN72** [comment]
Its prob windows 10 for him

**Comment by thatweirdkaden** [comment]
any news?

**Comment by l1ving** [comment]
![Screenshot_20201007_141444](https://user-images.githubusercontent.com/17222512/95370904-7460e580-08a7-11eb-8e18-84129bfd6596.png)
