### ISSUE TITLE
Impact keep crash when trying to reconnecting

### ISSUE THREAD

**Issue by NickWilde263** [ImpactDevelopment/ImpactIssues#2643]
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5289520/latest.log)
that my log then this the error report
---- Minecraft Crash Report ----
// Oops.

Time: 9/28/20 3:54 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
        at blk.k(SourceFile:389)
        at blk.q(SourceFile:377)
        at bib.t(SourceFile:1625)
        at bib.az(SourceFile:1000)
        at bib.a(SourceFile:419)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at blk.k(SourceFile:389)
        at blk.q(SourceFile:377)

-- Affected screen --
Details:
        Screen name: bky
Stacktrace:
        at bib.t(SourceFile:1625)
        at bib.az(SourceFile:1000)
        at bib.a(SourceFile:419)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 5.6.0-kali2-amd64
        Java Version: 1.8.0_251, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 415996280 bytes (396 MB) / 594542592 bytes (567 MB) up to 713031680 bytes (680 MB)
        JVM Flags: 6 total; -XX:+UseG1GC -Xmn8M -Xmx680M -Xms1M -XX:ReservedCodeCacheSize=70M -Xss1M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        Launched Version: 1.12.2-Impact_4.9.1-OptiFine_HD_U_F4
        LWJGL: 2.9.4
        OpenGL: Mesa Intel(R) UHD Graphics 600 (GLK 2) GL version 4.6 (Compatibility Profile) Mesa 20.0.7, Intel
        GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

        Using VBOs: Yes
        Is Modded: Very likely; Jar signature invalidated
        Type: Client (map_client.txt)
        Resource Packs: 
        Current Language: English (US)
        Profiler Position: N/A (disabled)
        CPU: 2x Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
#@!@# Game crashed! Crash report saved to: #@!@# /prv/Minecraft/crash-reports/crash-2020-09-28_15.54.42-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

Steps to reproduce:
1. Connect to a server
2. Disconnect
3. Repeat step 1 to 3 until it crashes

System Info:
RAM: 4 GB
OS: Linux
'uname -a' output: Linux ****** 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64 GNU/Linux
CPU: Already reported in error repor

**Comment by NickWilde263** [comment]
Also try connect to a server that not online

**Comment by l1ving** [comment]
> kali

:moyai:

**Comment by NickWilde263** [comment]
That my main OS

**Comment by NickWilde263** [comment]
i think minecraft shoulddn't crash just because connection issue so i open issue

**Comment by l1ving** [comment]
> Repeat step 1 to 3 until it crashes

Did you try not doing that

**Comment by NickWilde263** [comment]
I put auto reconnect and it crash then i try to manually reconnect

**Comment by NickWilde263** [comment]
so devs know the problem not in auto reconnect

**Comment by NickWilde263** [comment]
> > Repeat step 1 to 3 until it crashes
> 
> Did you try not doing that

some time it crash on first connect

**Comment by l1ving** [comment]
What version of impact, what other mods are you using (if any) and are you using Forge?

**Comment by NickWilde263** [comment]
no i not using forge

**Comment by NickWilde263** [comment]
impact 4.9.1

**Comment by NickWilde263** [comment]
with OptiFine

**Comment by l1ving** [comment]
Try without optifine

**Comment by NickWilde263** [comment]
maybe later i playing MInecraft 1.16.3 now

**Comment by NickWilde263** [comment]
i will send the result later

**Comment by NickWilde263** [comment]
I use not crack launcher or legal launcher i use scripts to manage clients

**Comment by berrely** [comment]
Does it work without your scripts?

**Comment by l1ving** [comment]
Closed as stale. Reopen if you can still reproduce this.
