### ISSUE TITLE
Poor mixins

### ISSUE THREAD

**Issue by Zeldagamer442** [ImpactDevelopment/ImpactIssues#2673]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Command: "C:\\Program Files\\Java\\jre1.8.0_261\\bin\\java.exe" -javaagent:C:\Users\User\AppData\Roaming\.SLauncher/brander.jar -Dminecraft.client.jar=C:\Users\User\AppData\Roaming\.minecraft\versions\1.14.4\1.14.4.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx768m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=C:\Users\User\AppData\Roaming\.minecraft\versions\1.14.4-Impact_4.9.1-OptiFine_HD_U_F5\natives -Dminecraft.launcher.brand=SLauncher -Dminecraft.launcher.version=3.4.8 -cp C:\Users\User\AppData\Roaming\.minecraft\libraries\com\github\ImpactDevelopment\Impact\4.9.1-1.14.4\Impact-4.9.1-1.14.4.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\cabaletta\baritone-api\1.4.6\baritone-api-1.4.6.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\optifine\launchwrapper-of\2.1\launchwrapper-of-2.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\github\ImpactDevelopment\SimpleTweaker\1.2\SimpleTweaker-1.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\github\ZeroMemes\Alpine\1.8\Alpine-1.8.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\net\impactclient\feather\1.0-3.2\feather-1.0-3.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\net\jodah\typetools\0.5.0\typetools-0.5.0.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\io\jsonwebtoken\jjwt-api\0.10.7\jjwt-api-0.10.7.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\io\jsonwebtoken\jjwt-impl\0.10.7\jjwt-impl-0.10.7.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\io\jsonwebtoken\jjwt-orgjson\0.10.7\jjwt-orgjson-0.10.7.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\spongepowered\mixin\0.7.11-SNAPSHOT\mixin-0.7.11-SNAPSHOT.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\github\ImpactDevelopment\Installer\0.8.5\Installer-0.8.5.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\club\minnced\java-discord-rpc\2.0.1\java-discord-rpc-2.0.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\json\json\20190722\json-20190722.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\club\minnced\discord-rpc-release\v3.3.0\discord-rpc-release-v3.3.0.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.14.4_HD_U_F5\OptiFine-1.14.4_HD_U_F5.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\User\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;C:\Users\User\AppData\Roaming\.minecraft\versions\1.14.4\1.14.4.jar net.minecraft.launchwrapper.Launch --username PiratikOkrabatik --version "SLauncher 3.4.8" --gameDir C:\Users\User\AppData\Roaming\.minecraft --assetsDir C:\Users\User\AppData\Roaming\.minecraft\assets --assetIndex 1.14 --uuid c19931b0adad3ef6b99c6fac252850a6 --accessToken 4d21f4ceec924005bda6a548353b6aac --userType mojang --versionType "SLauncher 3.4.8" --width 854 --height 480 --tweakClass clientapi.load.ClientTweaker --tweakClass baritone.launch.BaritoneTweaker --tweakClass optifine.OptiFineTweaker
[22:05:24] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[22:05:25] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[22:05:25] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[22:05:25] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[22:05:25] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[22:05:25] [main/INFO]: Injecting into ClassLoader
[22:05:25] [main/ERROR]: Initialising mixin subsystem after game pre-init phase! Some mixins may be skipped.
[22:05:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[22:05:25] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[22:05:25] [main/INFO]: Initialized Mixin bootstrap
[22:05:25] [main/INFO]: Setup Mixin Environment
[22:05:25] [main/INFO]: Compatibility level set to JAVA_8
[22:05:25] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[22:05:25] [main/INFO]: Loaded Mixin Configurations
[22:05:25] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[22:05:25] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[22:05:25] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: C:\Users\User\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.14.4_HD_U_F5\OptiFine-1.14.4_HD_U_F5.jar
OptiFineTweaker: getLaunchArguments
[22:05:25] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinArmorLayer, name: clientapi.load.mixin.MixinArmorLayer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlockMode, name: clientapi.load.mixin.MixinBlockMode
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBossOverlayGui, name: clientapi.load.mixin.MixinBossOverlayGui
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayerEntity, name: clientapi.load.mixin.MixinClientPlayerEntity
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayNetHandler, name: clientapi.load.mixin.MixinClientPlayNetHandler
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRendererManager, name: clientapi.load.mixin.MixinEntityRendererManager
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFirstPersonRenderer, name: clientapi.load.mixin.MixinFirstPersonRenderer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFogRenderer, name: clientapi.load.mixin.MixinFogRenderer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGameRenderer, name: clientapi.load.mixin.MixinGameRenderer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinIngameGui, name: clientapi.load.mixin.MixinIngameGui
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinKeyboardListener, name: clientapi.load.mixin.MixinKeyboardListener
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLivingEntity, name: clientapi.load.mixin.MixinLivingEntity
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMouseHelper, name: clientapi.load.mixin.MixinMouseHelper
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinSpectatorGui, name: clientapi.load.mixin.MixinSpectatorGui
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBitArray, name: baritone.launch.mixins.MixinBitArray
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBlockStateContainer, name: baritone.launch.mixins.MixinBlockStateContainer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChatScreen, name: baritone.launch.mixins.MixinChatScreen
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkArray, name: baritone.launch.mixins.MixinChunkArray
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientChunkProvider, name: baritone.launch.mixins.MixinClientChunkProvider
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayerEntity, name: baritone.launch.mixins.MixinClientPlayerEntity
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayNetHandler, name: baritone.launch.mixins.MixinClientPlayNetHandler
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntity, name: baritone.launch.mixins.MixinEntity
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderManager, name: baritone.launch.mixins.MixinEntityRenderManager
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinGameRenderer, name: baritone.launch.mixins.MixinGameRenderer
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLivingEntity, name: baritone.launch.mixins.MixinLivingEntity
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLootContext, name: baritone.launch.mixins.MixinLootContext
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerController, name: baritone.launch.mixins.MixinPlayerController
[22:05:26] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinScreen, name: baritone.launch.mixins.MixinScreen
[22:05:26] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:05:26] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
Caused by: joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option version, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179) ~[OptionSet.class:?]
	at net.minecraft.client.main.Main.a(SourceFile:164) ~[Main.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:108) ~[Main.class:?]
	... 6 more

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: <4.9.1>
- Using Optifine? <Yes>
- Using LiteLoader? <No>
- Enabled mods: <Nothing>
- Operating System: <Windows 8.1 Lite>

</details>

**Additional context**
its not launching WITH Optifine,but if i running impact WITHOUT Optifine it runs perfect

**Comment by l1ving** [comment]
> https://github.com/jopt-simple/jopt-simple

?????

Also fill out the template properly.
