### ISSUE TITLE
Launching Installer from command line in Arch Linux (with the proper java runtime enviroment?)

### ISSUE THREAD

**Issue by Taniks1618** [ImpactDevelopment/ImpactIssues#2748]
### Launching
When I launch the installer with
```
$ java -jar installer-0.9.3.jar
```
it spits out...
```
java.nio.file.NoSuchFileException: /home/carter/.minecraft/Impact/cid.txt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at io.github.ImpactDevelopment.installer.utils.Tracky.<clinit>(Unknown Source)
        at io.github.ImpactDevelopment.installer.Installer.main(Unknown Source)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sending event category=installer action=display label=null cid=ef419c38-a75f-4e97-899a-af0cd53d552d
Fetching releases from ImpactDevelopment/ImpactReleases
DOWNLOADING http://impactclient.net/releases.json
```
![2020-12-05-104715_3600x1080_scrot](https://user-images.githubusercontent.com/51769491/101259214-29b7ea00-36ed-11eb-9a46-aced1696f60c.jpg)

I let this run for about an hour and did nothing, I have good internet so I don't think it is my internet

### Java Packages
I only have Installed these packages, so I think the environment is good?

```
jre8-openjdk 8.u265-1
jre8-openjdk-headless 8.u265-1
java-runtime-common 3-3
```

**Comment by l1ving** [comment]
scuffed installer lol

use a gui

**Comment by l1ving** [comment]
if you want to make a bug report go here https://github.com/ImpactDevelopment/ImpactInstaller
