### ISSUE TITLE
crashs after starting

### ISSUE THREAD

**Issue by danilqweasd12321** [ImpactDevelopment/ImpactIssues#2849]
**Describe the bug**
Game does crash

**To Reproduce**
1. Just start minecraft
2. waiting
3. then crashs

**Expected behavior**
I'm sad that it won't start

**Screenshots**
N/A

<details> 
  <summary><strong>Game output</strong></summary>
 

```
N/A
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/15/21 1:13 PM
Description: Initializing game

java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL15.glGenBuffers(GL15.java:116)
	at pw.knx.feather.structures.VBO.<init>(VBO.java:50)
	at net.impactclient.9z.<init>(9z.java:191)
	at net.impactclient.3V.1(3V.java:34)
	at net.impactclient.0ay.2(0ay.java:69)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL15.glGenBuffers(GL15.java:116)
	at pw.knx.feather.structures.VBO.<init>(VBO.java:50)
	at net.impactclient.9z.<init>(9z.java:191)
	at net.impactclient.3V.1(3V.java:34)
	at net.impactclient.0ay.2(0ay.java:69)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 89199952 bytes (85 MB) / 266838016 bytes (254 MB) up to 1144258560 bytes (1091 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx1103M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.9.1-OptiFine_HD_U_F4
	LWJGL: 2.9.4
	OpenGL: Intel 945G GL version 1.4.0 - Build 8.14.10.1930, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is supported, EXT_blend_func_separate is supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is not supported, and EXT_framebuffer_object is not supported.
Shaders are not available because OpenGL 2.1 is not supported, ARB_shader_objects is not supported, ARB_vertex_shader is not supported, and ARB_fragment_shader is not supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: no info my CPU!
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.12.2-Impact_4.9.1-OptiFine_HD_U_F4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Nothing
- Operating System: Winodws 7 32bit

</details>

**Comment by danilqweasd12321** [comment]
bump

**Comment by Zezypisa** [comment]
What verison of MC is this? and it is a nightly version of Impact?

**Comment by Flurrrr** [comment]
^ If you are using a nightly version of impact make sure you're starting the game with a Minecraft account that's linked to an impact premium account
