### ISSUE TITLE
[1.12.2] Crashes on Launch with MultiMC

### ISSUE THREAD

**Issue by jylescoad-ward** [ImpactDevelopment/ImpactIssues#2861]
Impact Client 4.9 running on 1.12.2 Crashing on startup with MultiMC 5 (0.6.11-1430)

**To Reproduce**
1. Install Impact Client v4.9 (JAR Installer) for 1.12.2 without OptiFine into MultiMC
2. Launch MultiMC
3. Set Java VM Minimum Memory to 1024mb and maximum memory to 5120mb
3. Start Impact Client 4.9 in Online Mode

**Expected behavior**
Impact Client should launch as usual.

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
MultiMC version: 0.6.11-1430


Minecraft folder is:
C:/Games/MultiMC/instances/Impact-4.9-1.12.2/.minecraft


Java path is:
C:/Program Files/Java/jdk-15.0.1/bin/javaw.exe


Java is version 15.0.1, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Games/MultiMC/instances/Impact-4.9-1.12.2/natives

Libraries:
  C:/Games/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Games/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Games/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Games/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Games/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Games/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Games/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Games/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Games/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Games/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Games/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Games/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Games/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Games/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Games/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Games/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Games/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Games/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Games/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Games/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Games/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Games/MultiMC/libraries/com/github/ImpactDevelopment/Impact/4.9.1-1.12.2/Impact-4.9.1-1.12.2.jar
  C:/Games/MultiMC/libraries/cabaletta/baritone-api/1.2.14/baritone-api-1.2.14.jar
  C:/Games/MultiMC/libraries/com/github/ImpactDevelopment/SimpleTweaker/1.2/SimpleTweaker-1.2.jar
  C:/Games/MultiMC/libraries/com/github/ZeroMemes/Alpine/1.8/Alpine-1.8.jar
  C:/Games/MultiMC/libraries/net/impactclient/feather/1.0-2.9/feather-1.0-2.9.jar
  C:/Games/MultiMC/libraries/net/jodah/typetools/0.5.0/typetools-0.5.0.jar
  C:/Games/MultiMC/libraries/io/jsonwebtoken/jjwt-api/0.10.7/jjwt-api-0.10.7.jar
  C:/Games/MultiMC/libraries/io/jsonwebtoken/jjwt-impl/0.10.7/jjwt-impl-0.10.7.jar
  C:/Games/MultiMC/libraries/io/jsonwebtoken/jjwt-orgjson/0.10.7/jjwt-orgjson-0.10.7.jar
  C:/Games/MultiMC/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar
  C:/Games/MultiMC/libraries/com/github/ImpactDevelopment/Installer/0.8.5/Installer-0.8.5.jar
  C:/Games/MultiMC/libraries/club/minnced/java-discord-rpc/2.0.1/java-discord-rpc-2.0.1.jar
  C:/Games/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Games/MultiMC/libraries/org/json/json/20190722/json-20190722.jar
  C:/Games/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Games/MultiMC/libraries/club/minnced/discord-rpc-release/v3.3.0/discord-rpc-release-v3.3.0.jar
  C:/Games/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Games/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Games/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Games/MultiMC/instances/Impact-4.9-1.12.2/.minecraft --assetsDir C:/Games/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass clientapi.load.ClientTweaker --tweakClass baritone.launch.BaritoneTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx5120m, -Duser.language=en]


Minecraft process ID: 19464


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 22 Jan 2021 22:56:46 +0800

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: No mods enabled, default install
- Operating System: Windows 10 64-bit 1903 with Developer Mode Enabled
- Java Version: openjdk version "15.0.1" 2020-10-20

</details>

**Comment by CesiumCs** [comment]
> Java Version: openjdk version "15.0.1" 2020-10-20

tell multimc to use java 8 for impact

**Comment by jylescoad-ward** [comment]
> 
> 
> > Java Version: openjdk version "15.0.1" 2020-10-20
> 
> tell multimc to use java 8 for impact

Fixed thank you

**Comment by LeafHacker** [comment]
I wonder if jdk version is something we can specify as part of our installation. Or maybe we can't because that has to be setup by the user?

**Comment by jylescoad-ward** [comment]
> 
> 
> I wonder if jdk version is something we can specify as part of our installation. Or maybe we can't because that has to be setup by the user?

well mabye on the installation, if the java version is pretty new (i.e, 13 and newer) perhaps a popup saying that its an un-stable version?
