### ISSUE TITLE
Impact Crashes 

### ISSUE THREAD

**Issue by DabbinGaming** [ImpactDevelopment/ImpactIssues#2866]
Desc:

So basically I installed 1.12.2 impact nightly and 1.16.4 impact nightly. My 1.15.2 (not nightly) still works but none of the nightly ones do.

To Reproduce:
Download Nightly 1.12.2 or 1.16.4 nightly
run 1.12.2 or 1.16.4 nightly

expected behavior:
crash

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[19:48:30] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[19:48:30] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[19:48:30] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[19:48:30] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[19:48:30] [main/INFO]: Injecting into ClassLoader
[19:48:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/----/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[19:48:30] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[19:48:30] [main/INFO]: Initialized Mixin bootstrap
[19:48:30] [main/INFO]: Setup Mixin Environment
[19:48:30] [main/INFO]: Compatibility level set to JAVA_8
[19:48:30] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[19:48:30] [main/INFO]: Loaded Mixin Configurations
[19:48:30] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[19:48:30] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[19:48:30] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:48:30] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBipedArmorLayer, name: clientapi.load.mixin.MixinBipedArmorLayer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlockMode, name: clientapi.load.mixin.MixinBlockMode
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBossOverlayGui, name: clientapi.load.mixin.MixinBossOverlayGui
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayerEntity, name: clientapi.load.mixin.MixinClientPlayerEntity
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayNetHandler, name: clientapi.load.mixin.MixinClientPlayNetHandler
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRendererManager, name: clientapi.load.mixin.MixinEntityRendererManager
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFirstPersonRenderer, name: clientapi.load.mixin.MixinFirstPersonRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFogRenderer, name: clientapi.load.mixin.MixinFogRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGameRenderer, name: clientapi.load.mixin.MixinGameRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinIngameGui, name: clientapi.load.mixin.MixinIngameGui
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinKeyboardListener, name: clientapi.load.mixin.MixinKeyboardListener
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLivingEntity, name: clientapi.load.mixin.MixinLivingEntity
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMouseHelper, name: clientapi.load.mixin.MixinMouseHelper
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinOverlayRenderer, name: clientapi.load.mixin.MixinOverlayRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinSpectatorGui, name: clientapi.load.mixin.MixinSpectatorGui
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinWorldRenderer, name: clientapi.load.mixin.MixinWorldRenderer
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkArray, name: baritone.launch.mixins.MixinChunkArray
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientChunkProvider, name: baritone.launch.mixins.MixinClientChunkProvider
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayerEntity, name: baritone.launch.mixins.MixinClientPlayerEntity
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayNetHandler, name: baritone.launch.mixins.MixinClientPlayNetHandler
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinCommandSuggestionHelper, name: baritone.launch.mixins.MixinCommandSuggestionHelper
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntity, name: baritone.launch.mixins.MixinEntity
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderManager, name: baritone.launch.mixins.MixinEntityRenderManager
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLivingEntity, name: baritone.launch.mixins.MixinLivingEntity
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLootContext, name: baritone.launch.mixins.MixinLootContext
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerController, name: baritone.launch.mixins.MixinPlayerController
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinScreen, name: baritone.launch.mixins.MixinScreen
[19:48:31] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinWorldRenderer, name: baritone.launch.mixins.MixinWorldRenderer
[19:48:31] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:48:32] [main/WARN]: Injection warning: LVT in aqa::g(Ldcn;)Ldcn; has incompatible changes at opcode 148 in callback aqa::handler$getAllowedMovement$development$zcc000.
Expected: [Ldci;, Ldcs;, Lddh;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Lafo;, Ldcn;, Z, Z, Z, Z]
   Found: [Ldci;, Ldcs;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Lafo;, Ldcn;, Z, Z, Z, Z]
[19:48:38] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:48:38] [main/INFO]: Setting user: 
[19:48:39] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:48:41] [main/WARN]: Couldn't get pack info for: abl: 'pack.mcmeta' in ResourcePack 'C:\Users\----\AppData\Roaming\.minecraft\resourcepacks\! 5bruhh 5[16].zip'
[19:48:41] [main/WARN]: Couldn't get pack info for: abl: 'pack.mcmeta' in ResourcePack 'C:\Users\----/AppData\Roaming\.minecraft\resourcepacks\outlined-ores-for-1-16-e1800.zip'
[19:48:41] [main/WARN]: Couldn't get pack info for: abl: 'pack.mcmeta' in ResourcePack 'C:\Users\----\AppData\Roaming\.minecraft\resourcepacks\§8! §4Devine §7x32.zip'
[19:48:41] [main/WARN]: Removed resource pack Fabric Mods from options because it doesn't seem to exist anymore
[19:48:43] [main/INFO]: Narrator library for x64 successfully loaded
[19:48:44] [main/INFO]: Reloading ResourceManager: Default
[19:48:45] [main/INFO]: Initializing Fonts
[19:48:50] [main/ERROR]: Error getting Impact API token from minecraft login
java.io.IOException: /login/minecraft is not ok, it's 401
	at net.impactclient.0RX.0(0RX.java:16) [0RX.class:?]
	at net.impactclient.0D.<init>(0D.java:27) [0D.class:?]
	
	
	

	at net.impactclient.5J.0(5J.java:13) [5J.class:?]
	at net.impactclient.01S.0(01S.java:95) [01S.class:?]
	at net.impactclient.6V.0(6V.java:7) [6V.class:?]
	at djz.handler$init$zzp000(SourceFile:2854) [djz.class:?]
	at djz.<init>(SourceFile:592) [djz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:177) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[19:48:50] [main/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:48:50] [main/INFO]: [STDERR]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:48:50] [main/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[19:48:50] [main/INFO]: [STDOUT]: Sending event category=client action=launch label=nightly-20210115-1.16.4 cid=160128926.1606894016
[19:48:50] [pool-4-thread-1/INFO]: Checking for Updates
[19:48:50] [pool-4-thread-1/INFO]: [STDOUT]: Offering updates to betas: false
[19:48:50] [pool-4-thread-1/INFO]: [STDOUT]: Fetching releases from ImpactDevelopment/ImpactReleases
[19:48:50] [pool-4-thread-1/INFO]: [STDOUT]: DOWNLOADING http://impactclient.net/releases.json
[19:48:54] [main/INFO]: OpenGL debug message, id=0, source=SHADER COMPILER, type=ERROR, severity=HIGH, message=SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 7, "": ERROR: 0:3: 'varying out' : syntax error syntax error


[19:48:54] [main/INFO]: [STDERR]: net.impactclient.48: ERROR: 0:3: 'varying out' : syntax error syntax error


[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.2F.3(2F.java:20)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0T.0(0T.java:12)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0Y.0(0Y.java:3)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0j.<init>(0j.java:5)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0W.<init>(0W.java:6)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0W.<init>(0W.java:9)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.8y.<init>(8y.java:48)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.01A.1(01A.java:5)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.01S.0(01S.java:55)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.6V.0(6V.java:7)
[19:48:54] [main/INFO]: [STDERR]: 	at djz.handler$init$zzp000(SourceFile:2854)
[19:48:54] [main/INFO]: [STDERR]: 	at djz.<init>(SourceFile:592)
[19:48:54] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:177)
[19:48:54] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:48:54] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:48:54] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:48:54] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:48:54] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:48:54] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:48:54] [main/INFO]: [STDERR]: net.impactclient.48: Cannot attach a shader to program if shader isn't generated!
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0c.0(0c.java:10)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0c$$Lambda$3063/1357251908.accept(Unknown Source)
[19:48:54] [main/INFO]: [STDERR]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0c.0(0c.java:41)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0Y.0(0Y.java:3)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.0W.<init>(0W.java:5)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.8y.<init>(8y.java:48)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.01A.1(01A.java:5)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.01S.0(01S.java:55)
[19:48:54] [main/INFO]: [STDERR]: 	at net.impactclient.6V.0(6V.java:7)
[19:48:54] [main/INFO]: [STDERR]: 	at djz.handler$init$zzp000(SourceFile:2854)
[19:48:54] [main/INFO]: [STDERR]: 	at djz.<init>(SourceFile:592)
[19:48:54] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:177)
[19:48:54] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:48:54] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:48:54] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:48:54] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:48:54] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:48:54] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:48:54] [main/INFO]: Initialized 119 mods!
[19:48:54] [main/ERROR]: ########## GL ERROR ##########
[19:48:54] [main/ERROR]: @ Post startup
[19:48:54] [main/ERROR]: 65539: Invalid key -1
[19:48:54] [main/FATAL]: Unable to load spam config file: Spam config file is in invalid format
[19:48:55] [main/INFO]: [CHAT] [Impact] Added 3 as a friend!
[19:48:55] [main/INFO]: [CHAT] [Impact] Added  as a friend!
[19:48:55] [main/INFO]: [CHAT] [Impact] Added as a friend!
[19:48:55] [main/INFO]: [STDOUT]: Initializing took 10917ms
[19:48:55] [main/ERROR]: Setting skin to impaste
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:55] [main/INFO]: [STDOUT]: Impact Error Code 102
[19:48:57] [main/INFO]: OpenAL initialized.
[19:48:57] [main/INFO]: Sound engine started
[19:48:58] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:48:58] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:48:58] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:48:58] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:48:58] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:48:58] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:48:58] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:49:00] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:49:00] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:49:00] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
```

</details>

**Comment by JustAnOkapi** [comment]
are you logged in on the same account you have impact premium?

**Comment by berrely** [comment]
Please fill out the issue template properly.

**Comment by DabbinGaming** [comment]
Template?

**Comment by Flurrrr** [comment]
[This](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md) is the bug report template, also make sure you are launching the nightlies with an Impact premium account
