### ISSUE TITLE
Activating click gui turns screen black

### ISSUE THREAD

**Issue by JustAnOkapi** [ImpactDevelopment/ImpactIssues#2870]
**Describe the bug**
bug: activating click gui turns screen black
cause: Anti aliasing

**To Reproduce**

1. 1.15.2 with optifine G6 
2. Turn on Anti Aliasing in setting
3. Restart minecraft

**Expected behavior**
Open Click GUI

**Screenshots**
![image](https://user-images.githubusercontent.com/39418801/105975545-afed0e80-6054-11eb-8a13-6c237c24f4a8.png)
![image](https://user-images.githubusercontent.com/39418801/105976699-1de60580-6056-11eb-9d4b-089aaa7de400.png)
![image](https://user-images.githubusercontent.com/39418801/105975581-bb403a00-6054-11eb-9b0f-70c16948d325.png)

<details> 
  <summary><strong>Game output (happens on start up, no output on click)</strong></summary>
 

```
[04:02:36] [main/INFO]: [OptiFine] *** Reloading custom textures ***
[04:02:36] [main/INFO]: [OptiFine] Disable Forge light pipeline
[04:02:36] [main/ERROR]: Setting skin to impaste
[04:02:40] [main/ERROR]: Setting skin to impaste
[04:02:43] [main/ERROR]: Error parsing GOLD
java.lang.NumberFormatException: For input string: "GOLD"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_232]
	at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_232]
	at java.lang.Long.valueOf(Long.java:776) ~[?:1.8.0_232]
	at java.lang.Long.decode(Long.java:928) ~[?:1.8.0_232]
	at net.impactclient.0Yp.1(0Yp.java:14) ~[0Yp.class:?]
	at net.impactclient.0Yp.0(0Yp.java:29) ~[0Yp.class:?]
	at net.impactclient.08.0(08.java:20) ~[08.class:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) [?:1.8.0_232]
	at net.impactclient.08.2(08.java:27) [08.class:?]
	at net.impactclient.0s.render(0s.java:37) [0s.class:?]
	at dqn.a(GameRenderer.java:807) [dqn.class:?]
	at dbn.d(SourceFile:989) [dbn.class:?]
	at dbn.d(SourceFile:619) [dbn.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[04:02:44] [main/ERROR]: Setting skin to impaste
[04:02:51] [main/ERROR]: Setting skin to impaste

```

</details>
<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9 (I haven't tested others, but latest nightly doesn't fix it)
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Click GUI, Nothing else
- Operating System: Windows 10 64bit

</details>

  <summary><strong>More version testing</strong></summary>

- 1.12.2 with G5 - Works
- 1.13.2 with G5 - Works
- 1.14.4 with G5 - Works
- 1.15.2 with G6 - Bugged

might be a bug in G6 optifine?

**Comment by l1ving** [comment]
Optifine issue then
