### ISSUE TITLE
Impact 1.12.2 crashing on launch - "java.lang.NullPointerException: Unexpected error"

### ISSUE THREAD

**Issue by tiswandy** [ImpactDevelopment/ImpactIssues#2922]
**Describe the bug**
When I launch Impact 1.12.2, Minecraft crashes as soon as it opens. It just says "unexpected error".

**To Reproduce**
1. Go to 'Minecraft Launcher'
2. Click on 'Play Minecraft'

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// You're mean.

Time: 2/27/21 11:28 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bib.t(SourceFile:1597)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 181782456 bytes (173 MB) / 469762048 bytes (448 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_nightly-20210226-OptiFine_HD_U_C8
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  1.12.2
- Using Optifine?  Yes, but also happens without Optifine
- Using LiteLoader?  No
- Enabled mods:  None
- Operating System:  Windows 10

</details>

**Additional context**
I installed Impact 1.12.2 a while ago and I remember it working fine. I deleted and reinstalled Impact 1.12.2 twice after seeing this issue and nothing changed. I should mention that this doesn't happen using other clients.

**Comment by l1ving** [comment]
Fairly certain you're trying to use a nightly version without a premium account.

**Comment by tiswandy** [comment]
Yeah, that was it. Idk how exactly I got the nightly version. Works fine now, though.
