### ISSUE TITLE
Impact Crash At Startup

### ISSUE THREAD

**Issue by GFSKGaming** [ImpactDevelopment/ImpactIssues#2937]
**Describe the bug**
Impact Instant Crash

**To Reproduce**
1. Go to 'Minecraft Launcher'
2. Click on 'Impact Nightly 1.16.4'
3. Click on 'Play'

**Expected behavior**
Minecraft starts

**Screenshots**
![image](https://user-images.githubusercontent.com/78292451/110230189-3e08be80-7f4a-11eb-8f16-5e23f8de6a17.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/7/21 1:20 PM
Description: Initializing game

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at deg.b(SourceFile:172)
	at deg.b(SourceFile:149)
	at deg.d(SourceFile:65)
	at deg.a(SourceFile:54)
	at deg.<init>(SourceFile:45)
	at djz.<init>(SourceFile:480)
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at deg.b(SourceFile:172)
	at deg.b(SourceFile:149)
	at deg.d(SourceFile:65)
	at deg.a(SourceFile:54)
	at deg.<init>(SourceFile:45)
	at djz.<init>(SourceFile:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 805227256 bytes (767 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.4-Impact_nightly-20210115
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Q45/Q43 Express Chipset GL version 2.1.0 - Build 8.15.10.2302, Intel
	GL Caps: Using framebuffer using EXT_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9505 @ 2.83GHz

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by l1ving** [comment]
Include the full latest.log file
