### ISSUE TITLE
optifine crashes 

### ISSUE THREAD

**Issue by kpopKPOOP** [ImpactDevelopment/ImpactIssues#2939]
**Describe the bug**
optifine crashes 1.12.2 as soon as the game opens

**To Reproduce**
1. download 1.12.2
2. Click on include optifine
3. Scroll down to install
Time: 3/7/21 7:15 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.optifine.TextureAnimations.updateAnimations(TextureAnimations.java:82)
	at biq.c(GuiIngame.java:1267)
	at bib.t(SourceFile:1594)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 608275264 bytes (580 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_nightly-20210306-OptiFine_HD_U_G5
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 605 GL version 4.6.0 - Build 26.20.100.7926, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) Silver J5040 CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7926
	OpenGlRenderer: Intel(R) UHD Graphics 605
	OpenGlVendor: Intel
	CpuCount: 4
**Expected behavior**
the game to not crash as soon as it opens

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine?  yes
- Using LiteLoader?  no (i can if i need to)
- Enabled mods: antihunger, light auto armour, auto tool, no fall(packet), bow aimbot, anti vanish, anti blind, inventory, no slow, hitbox.
- i will try to open it with these all off
- Operating System: Windows 10 64

</details>

**Additional context**
optifine 1.12.2 works by its self, and so does impact. 

i made this becuase i want sure it was meant to crash straight away as it opens

**Comment by kpopKPOOP** [comment]
nope, everything closed and all mods turned off. it bearly even opens before crashing
altough im using nightly to open 1.12.2 with optifine

**Comment by kpopKPOOP** [comment]
works with defult impact.
