### ISSUE TITLE
Impact Nightly 1.16.5 not working its been a month and no one solved it (1.12.2 nightly works (getting error code 0))

### ISSUE THREAD

**Issue by onayB09** [ImpactDevelopment/ImpactIssues#3013]
**Describe the bug**
Impact Nightly 1.16.5 not working and im getting error code 0 for a month

**To Reproduce**
1. Just Start Any Impact Nightly 1.16.5 Version
2. See the error code with BIG FAT 0

**Expected behavior**
Normally Open Impact Nightly 1.16.5

**Screenshots**
![image](https://user-images.githubusercontent.com/53120690/113172754-6639c380-9251-11eb-9c19-1b1cdcb5fc39.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
18:37:17.571
Preparing to launch minecraft client for 1.16.5-Impact_nightly-20210308
18:37:19.322
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.16.5/1.16.5.jar
18:37:19.324
Have local file C:\Users\tardu\AppData\Roaming\.minecraft\versions\1.16.5\1.16.5.jar but don't know what size or hash it should be. Have to assume it's good.
18:37:19.327
Checking installations.
18:37:19.332
Minecraft client 1.16.5-Impact_nightly-20210308 is ready to start.
18:37:19.332
Starting!
18:37:20.549
Using default game log configuration client-1.12.xml (outputs XML)
18:45:55.604
Loading tweak class name clientapi.load.ClientTweaker
18:45:55.616
Using primary tweak class name clientapi.load.ClientTweaker
18:45:55.617
Loading tweak class name baritone.launch.BaritoneTweaker
18:45:55.620
Calling tweak class clientapi.load.ClientTweaker
18:45:55.630
Injecting into ClassLoader
18:45:55.791
SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/tardu/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
18:45:56.811
FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
18:45:56.893
Initialized Mixin bootstrap
18:45:56.956
Setup Mixin Environment
18:45:57.018
Compatibility level set to JAVA_8
18:45:57.022
Mixin config mixins.impact.json does not specify "minVersion" property
18:45:57.023
Loaded Mixin Configurations
18:45:57.023
Calling tweak class baritone.launch.BaritoneTweaker
18:45:57.026
Mixin config mixins.baritone.json does not specify "minVersion" property
18:45:57.026
Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
18:45:57.027
Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
18:45:57.231
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBipedArmorLayer, 
18:45:57.280
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlockMode, name: clientapi.load.mixin.MixinBlockMode
18:45:57.283
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBossOverlayGui, name: clientapi.load.mixin.MixinBossOverlayGui
18:45:57.286
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayerEntity, name: clientapi.load.mixin.MixinClientPlayerEntity
18:45:57.298
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayNetHandler, name: clientapi.load.mixin.MixinClientPlayNetHandler
18:45:57.320
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
18:45:57.351
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
18:45:57.356
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRendererManager, name: clientapi.load.mixin.MixinEntityRendererManager
18:45:57.376
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFirstPersonRenderer, name: clientapi.load.mixin.MixinFirstPersonRenderer
18:45:57.381
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFogRenderer, name: clientapi.load.mixin.MixinFogRenderer
18:45:57.387
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
18:45:57.398
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGameRenderer, name: clientapi.load.mixin.MixinGameRenderer
18:45:57.407
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinIngameGui, name: clientapi.load.mixin.MixinIngameGui
18:45:57.413
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
18:45:57.417
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinKeyboardListener, name: clientapi.load.mixin.MixinKeyboardListener
18:45:57.421
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLivingEntity, name: clientapi.load.mixin.MixinLivingEntity
18:45:57.431
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
18:45:57.442
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMouseHelper, name: clientapi.load.mixin.MixinMouseHelper
18:45:57.446
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
18:45:57.449
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
18:45:57.451
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
18:45:57.455
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinOverlayRenderer, name: clientapi.load.mixin.MixinOverlayRenderer
18:45:57.458
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
18:45:57.467
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
18:45:57.471
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinSpectatorGui, name: clientapi.load.mixin.MixinSpectatorGui
18:45:57.475
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
18:45:57.478
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinWorldRenderer, name: clientapi.load.mixin.MixinWorldRenderer
18:45:57.688
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkArray, name: baritone.launch.mixins.MixinChunkArray
18:45:57.692
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientChunkProvider, name: baritone.launch.mixins.MixinClientChunkProvider
18:45:57.694
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayerEntity, name: baritone.launch.mixins.MixinClientPlayerEntity
18:45:57.697
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayNetHandler, name: baritone.launch.mixins.MixinClientPlayNetHandler
18:45:57.699
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinCommandSuggestionHelper, name: baritone.launch.mixins.MixinCommandSuggestionHelper
18:45:57.702
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntity, name: baritone.launch.mixins.MixinEntity
18:45:57.704
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderManager, name: baritone.launch.mixins.MixinEntityRenderManager
18:45:57.706
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
18:45:57.708
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLivingEntity, name: baritone.launch.mixins.MixinLivingEntity
18:45:57.709
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLootContext, name: baritone.launch.mixins.MixinLootContext
18:45:57.715
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
18:45:57.717
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
18:45:57.718
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerController, name: baritone.launch.mixins.MixinPlayerController
18:45:57.721
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinScreen, name: baritone.launch.mixins.MixinScreen
18:45:57.725
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinSodiumChunkProvider, name: baritone.launch.mixins.MixinSodiumChunkProvider
18:45:57.729
Error loading class: me/jellysquid/mods/sodium/client/world/SodiumChunkManager (java.lang.ClassNotFoundException: The specified class 'me.jellysquid.mods.sodium.client.world.SodiumChunkManager' was not found)
18:45:57.730
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinSodiumFixedLongHashTable, name: baritone.launch.mixins.MixinSodiumFixedLongHashTable
18:45:57.732
Error loading class: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable (java.lang.ClassNotFoundException: The specified class 
'me.jellysquid.mods.sodium.client.util.collections.FixedLongHashTable' was not found)
18:45:57.732
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinWorldRenderer, name: baritone.launch.mixins.MixinWorldRenderer
18:45:57.880
Launching wrapped minecraft {net.minecraft.client.main.Main}
18:45:59.177
Injection warning: LVT in aqa::g(Ldcn;)Ldcn; has incompatible changes at opcode 148 in callback aqa::handler$getAllowedMovement$development$zcc000.
Expected: [Ldci;, Ldcs;, Lddh;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Lafo;, Ldcn;, Z, Z, Z, Z]
   Found: [Ldci;, Ldcs;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Lafo;, Ldcn;, Z, Z, Z, Z]
Mixin apply failed mixins.impact.json:accessor.AccessorPlayerEntity -> bfw: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at bup.<clinit>(SourceFile:99)
	at ctt.<clinit>(SourceFile:13)
	at kp.<clinit>(SourceFile:11)
	at hk.g(SourceFile:44)
	at hk$$Lambda$129/594651850.get(Unknown Source)
	at hk.a(SourceFile:75)
	at hk$$Lambda$137/1041547629.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at hk.<clinit>(SourceFile:74)
	at gm.<clinit>(SourceFile:237)
	at vm.a(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
18:45:59.256
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.impact.json:accessor.AccessorPlayerEntity] from phase [DEFAULT] in config [mixins.impact.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at bup.<clinit>(SourceFile:99)
	at ctt.<clinit>(SourceFile:13)
	at kp.<clinit>(SourceFile:11)
	at hk.g(SourceFile:44)
	at hk$$Lambda$129/594651850.get(Unknown Source)
	at hk.a(SourceFile:75)
	at hk$$Lambda$137/1041547629.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at hk.<clinit>(SourceFile:74)
	at gm.<clinit>(SourceFile:237)
	at vm.a(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching �nventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 23 more
  <log4j:Event logger="LaunchWrapper" timestamp="1617205559255" level="ERROR" thread="main">
    <log4j:Message><![CDATA[Unable to launch]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: bfw
	at bup.<clinit>(SourceFile:99)
	at ctt.<clinit>(SourceFile:13)
	at kp.<clinit>(SourceFile:11)
	at hk.g(SourceFile:44)
	at hk$$Lambda$129/594651850.get(Unknown Source)
	at hk.a(SourceFile:75)
	at hk$$Lambda$137/1041547629.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at hk.<clinit>(SourceFile:74)
	at gm.<clinit>(SourceFile:237)
	at vm.a(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)
	... 6 more
Caused by: java.lang.ClassNotFoundException: bfw
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.impact.json:accessor.AccessorPlayerEntity] from phase [DEFAULT] in config [mixins.impact.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 23 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 23 more
]]></log4j:Throwable>
  </log4j:Event>
18:45:59.256
XML_ERROR_PARSING
18:45:59.333

18:45:59.333
Process crashed with exit code 1
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
No crash report file generated.
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: "Impact Nightly For 1.16.5 20210308"
- Using Optifine? "No"
- Using LiteLoader? "No"
- Enabled mods: "Cant Even Open It (No)"
- Operating System: "Windows 10 64-Bit"

</details>

**Additional context**
I donated 5$ and buyed account. Linked onayB09 and discord with donator account and trying to play with onayB09. Please dont say "use donation account" and close.

**Comment by l1ving** [comment]
CNR

**Comment by onayB09** [comment]
> CNR

whats CNR means?

**Comment by l1ving** [comment]
I can't reproduce this issue. You'll have to provide additional instructions on how to reproduce it reliably

**Comment by DiamondsInLava** [comment]
I could post a video or screen share via discord? getting the same error in all versions, even normal releases, i tought it was java so i updated to the latest version and still crashes.

I relinked my mc and discord account and still any impact works.
Maybe it cant pull files off the discord server since its dead and l1ving already has them?.

Thanks for replying and for your time.

**Comment by l1ving** [comment]
> latest version java 

that's probably going to cause some issues

**Comment by DiamondsInLava** [comment]
i didnt have the latest and didnt run, updated and still doesnt run cmon wdym

**Comment by l1ving** [comment]
> Maybe it cant pull files off the discord server since its dead and l1ving already has them?

No, it would be extremely stupid to use discord as a file host.

**Comment by DiamondsInLava** [comment]
> 
> 
> > latest version java
> 
> that's probably going to cause some issues

can i know at least your version to downgrade to a working java?

**Comment by l1ving** [comment]
Just use the bundled java

**Comment by NamelessRen** [comment]
this just happened to me, i was playing fine yesterday and now i got this error and cant play anymore

**Comment by onayB09** [comment]
> Just use the bundled java

what is bundled java? Im using java already. Is there a download link for "bundled java"?

**Comment by Kutaygb** [comment]
Sorunu çözebildin mi ? aynı hatayı alıyorum
Did you solve the problem? I'm getting the same error

**Comment by l1ving** [comment]
![image](https://user-images.githubusercontent.com/17222512/113488744-dfbdf580-948d-11eb-87ba-b96ea75d7489.png)

**Comment by onayB09** [comment]
> Sorunu çözebildin mi ? aynı hatayı alıyorum
> Did you solve the problem? I'm getting the same error
> Edit: Sorunu çözdüm eğer yardım istiyorsan discorddan yazabilirim dc:Kutay#4503

![image](https://user-images.githubusercontent.com/53120690/113488904-ad31ee00-94c9-11eb-9055-de86c737f257.png)
This Guy Helped Me Fix It And It Worked. Thanks you so much.
