### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by InFlamesAlone** [ImpactDevelopment/ImpactIssues#3211]
**Describe the bug**
Instant crash in 4.9 1.16.5 when I open the client.

Mixin apply failed mixins.impact.json:accessor.AccessorPlayerEntity -> bfw: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at bup.<clinit>(SourceFile:99)
	at ctt.<clinit>(SourceFile:13)
	at kp.<clinit>(SourceFile:11)
	at hk.g(SourceFile:44)
	at hk$$Lambda$130/350069300.get(Unknown Source)
	at hk.a(SourceFile:75)
	at hk$$Lambda$138/2033268925.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at hk.<clinit>(SourceFile:74)
	at gm.<clinit>(SourceFile:237)
	at vm.a(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

- Impact Version: 4.9.1 1.16.5
-  - Using Optifine? No
- Using LiteLoader? <No
- Operating System: Windows 10 64bit

**Comment by Sagiitarius** [comment]
+++++
