### ISSUE TITLE
i paid for a membership cannot playing.

### ISSUE THREAD

**Issue by geven26** [ImpactDevelopment/ImpactIssues#3225]
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/6906059/latest.log)

**Comment by geven26** [comment]
SOLVED . whoever got this error log should try MultiMC.

**Comment by geven26** [comment]
[11:14:40] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[11:14:40] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[11:14:40] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[11:14:40] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[11:14:40] [main/INFO]: Injecting into ClassLoader
[11:14:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Cydia/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[11:14:40] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[11:14:40] [main/INFO]: Initialized Mixin bootstrap
[11:14:40] [main/INFO]: Setup Mixin Environment
[11:14:40] [main/INFO]: Compatibility level set to JAVA_8
[11:14:40] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[11:14:40] [main/INFO]: Loaded Mixin Configurations
[11:14:40] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[11:14:40] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[11:14:40] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[11:14:40] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBipedArmorLayer, name: clientapi.load.mixin.MixinBipedArmorLayer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlockMode, name: clientapi.load.mixin.MixinBlockMode
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBossOverlayGui, name: clientapi.load.mixin.MixinBossOverlayGui
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayerEntity, name: clientapi.load.mixin.MixinClientPlayerEntity
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinClientPlayNetHandler, name: clientapi.load.mixin.MixinClientPlayNetHandler
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRendererManager, name: clientapi.load.mixin.MixinEntityRendererManager
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFirstPersonRenderer, name: clientapi.load.mixin.MixinFirstPersonRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFogRenderer, name: clientapi.load.mixin.MixinFogRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGameRenderer, name: clientapi.load.mixin.MixinGameRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinIngameGui, name: clientapi.load.mixin.MixinIngameGui
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinKeyboardListener, name: clientapi.load.mixin.MixinKeyboardListener
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLivingEntity, name: clientapi.load.mixin.MixinLivingEntity
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMouseHelper, name: clientapi.load.mixin.MixinMouseHelper
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinOverlayRenderer, name: clientapi.load.mixin.MixinOverlayRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinSpectatorGui, name: clientapi.load.mixin.MixinSpectatorGui
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinWorldRenderer, name: clientapi.load.mixin.MixinWorldRenderer
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkArray, name: baritone.launch.mixins.MixinChunkArray
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientChunkProvider, name: baritone.launch.mixins.MixinClientChunkProvider
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayerEntity, name: baritone.launch.mixins.MixinClientPlayerEntity
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayNetHandler, name: baritone.launch.mixins.MixinClientPlayNetHandler
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinCommandSuggestionHelper, name: baritone.launch.mixins.MixinCommandSuggestionHelper
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntity, name: baritone.launch.mixins.MixinEntity
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderManager, name: baritone.launch.mixins.MixinEntityRenderManager
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLivingEntity, name: baritone.launch.mixins.MixinLivingEntity
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLootContext, name: baritone.launch.mixins.MixinLootContext
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerController, name: baritone.launch.mixins.MixinPlayerController
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinScreen, name: baritone.launch.mixins.MixinScreen
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinSodiumChunkProvider, name: baritone.launch.mixins.MixinSodiumChunkProvider
[11:14:41] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/SodiumChunkManager (java.lang.ClassNotFoundException: The specified class 'me.jellysquid.mods.sodium.client.world.SodiumChunkManager' was not found)
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinSodiumFixedLongHashTable, name: baritone.launch.mixins.MixinSodiumFixedLongHashTable
[11:14:41] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable (java.lang.ClassNotFoundException: The specified class 'me.jellysquid.mods.sodium.client.util.collections.FixedLongHashTable' was not found)
[11:14:41] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinWorldRenderer, name: baritone.launch.mixins.MixinWorldRenderer
[11:14:41] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[11:14:42] [main/WARN]: Injection warning: LVT in aqa::g(Ldcn;)Ldcn; has incompatible changes at opcode 148 in callback aqa::handler$getAllowedMovement$development$zcc000.
Expected: [Ldci;, Ldcs;, Lddh;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Lafo;, Ldcn;, Z, Z, Z, Z]
   Found: [Ldci;, Ldcs;, Ljava/util/stream/Stream;, Ljava/util/stream/Stream;, Lafo;, Ldcn;, Z, Z, Z, Z]
[11:14:42] [main/FATAL]: Mixin apply failed mixins.impact.json:accessor.AccessorPlayerEntity -> bfw: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at bup.<clinit>(SourceFile:99) [bup.class:?]
	at ctt.<clinit>(SourceFile:13) [ctt.class:?]
	at kp.<clinit>(SourceFile:11) [kp.class:?]
	at hk.g(SourceFile:44) [hk.class:?]
	at hk$$Lambda$130/350069300.get(Unknown Source) [hk.class:?]
	at hk.a(SourceFile:75) [hk.class:?]
	at hk$$Lambda$138/2033268925.accept(Unknown Source) [hk.class:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at hk.<clinit>(SourceFile:74) [hk.class:?]
	at gm.<clinit>(SourceFile:237) [gm.class:?]
	at vm.a(SourceFile:42) [vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:14:42] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: bfw
	at bup.<clinit>(SourceFile:99) ~[bup.class:?]
	at ctt.<clinit>(SourceFile:13) ~[ctt.class:?]
	at kp.<clinit>(SourceFile:11) ~[kp.class:?]
	at hk.g(SourceFile:44) ~[hk.class:?]
	at hk$$Lambda$130/350069300.get(Unknown Source) ~[?:?]
	at hk.a(SourceFile:75) ~[hk.class:?]
	at hk$$Lambda$138/2033268925.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_51]
	at hk.<clinit>(SourceFile:74) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: bfw
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at bup.<clinit>(SourceFile:99) ~[bup.class:?]
	at ctt.<clinit>(SourceFile:13) ~[ctt.class:?]
	at kp.<clinit>(SourceFile:11) ~[kp.class:?]
	at hk.g(SourceFile:44) ~[hk.class:?]
	at hk$$Lambda$130/350069300.get(Unknown Source) ~[?:?]
	at hk.a(SourceFile:75) ~[hk.class:?]
	at hk$$Lambda$138/2033268925.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_51]
	at hk.<clinit>(SourceFile:74) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at bup.<clinit>(SourceFile:99) ~[bup.class:?]
	at ctt.<clinit>(SourceFile:13) ~[ctt.class:?]
	at kp.<clinit>(SourceFile:11) ~[kp.class:?]
	at hk.g(SourceFile:44) ~[hk.class:?]
	at hk$$Lambda$130/350069300.get(Unknown Source) ~[?:?]
	at hk.a(SourceFile:75) ~[hk.class:?]
	at hk$$Lambda$138/2033268925.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_51]
	at hk.<clinit>(SourceFile:74) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.impact.json:accessor.AccessorPlayerEntity] from phase [DEFAULT] in config [mixins.impact.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at bup.<clinit>(SourceFile:99) ~[bup.class:?]
	at ctt.<clinit>(SourceFile:13) ~[ctt.class:?]
	at kp.<clinit>(SourceFile:11) ~[kp.class:?]
	at hk.g(SourceFile:44) ~[hk.class:?]
	at hk$$Lambda$130/350069300.get(Unknown Source) ~[?:?]
	at hk.a(SourceFile:75) ~[hk.class:?]
	at hk$$Lambda$138/2033268925.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_51]
	at hk.<clinit>(SourceFile:74) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ınventory:Lbfv; in bfw for mixins.impact.json:accessor.AccessorPlayerEntity->@Accessor[FIELD_SETTER]::setInventory(Lbfv;)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at bup.<clinit>(SourceFile:99) ~[bup.class:?]
	at ctt.<clinit>(SourceFile:13) ~[ctt.class:?]
	at kp.<clinit>(SourceFile:11) ~[kp.class:?]
	at hk.g(SourceFile:44) ~[hk.class:?]
	at hk$$Lambda$130/350069300.get(Unknown Source) ~[?:?]
	at hk.a(SourceFile:75) ~[hk.class:?]
	at hk$$Lambda$138/2033268925.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_51]
	at hk.<clinit>(SourceFile:74) ~[hk.class:?]
	at gm.<clinit>(SourceFile:237) ~[gm.class:?]
	at vm.a(SourceFile:42) ~[vm.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:137) ~[Main.class:?]
	... 6 more

**Comment by geven26** [comment]
TRY MultiMC ASAP
