### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by realdeadbeef** [ImpactDevelopment/ImpactIssues#3232]
**Describe the bug**
Game won't launch from MultiMC

**To Reproduce**
1. Download installer jar
2. run jar
3. select multimc folder
4. (It creates an instance)
5. open instance
**Expected behavior**
The game to start

```
MultiMC version: 0.6.12-1530


Minecraft folder is:
G:/Epicc Games/MultiMC/instances/Impact-4.9-1.16.5/.minecraft


Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe


Checking Java version...
Java is version 16.0.1, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  G:/Epicc Games/MultiMC/instances/Impact-4.9-1.16.5/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/patchy/1.2.3/patchy-1.2.3.jar
  G:/Epicc Games/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  G:/Epicc Games/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  G:/Epicc Games/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  G:/Epicc Games/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  G:/Epicc Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  G:/Epicc Games/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  G:/Epicc Games/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  G:/Epicc Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  G:/Epicc Games/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  G:/Epicc Games/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  G:/Epicc Games/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  G:/Epicc Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  G:/Epicc Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  G:/Epicc Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  G:/Epicc Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  G:/Epicc Games/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  G:/Epicc Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  G:/Epicc Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  G:/Epicc Games/MultiMC/libraries/com/github/ImpactDevelopment/Impact/4.9.1-1.16.5/Impact-4.9.1-1.16.5.jar
  G:/Epicc Games/MultiMC/libraries/cabaletta/baritone-api/1.6.3/baritone-api-1.6.3.jar
  G:/Epicc Games/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  G:/Epicc Games/MultiMC/libraries/com/github/ImpactDevelopment/SimpleTweaker/1.2/SimpleTweaker-1.2.jar
  G:/Epicc Games/MultiMC/libraries/com/github/ZeroMemes/Alpine/1.8/Alpine-1.8.jar
  G:/Epicc Games/MultiMC/libraries/net/impactclient/feather/1.0-3.2/feather-1.0-3.2.jar
  G:/Epicc Games/MultiMC/libraries/net/jodah/typetools/0.5.0/typetools-0.5.0.jar
  G:/Epicc Games/MultiMC/libraries/io/jsonwebtoken/jjwt-api/0.10.7/jjwt-api-0.10.7.jar
  G:/Epicc Games/MultiMC/libraries/io/jsonwebtoken/jjwt-impl/0.10.7/jjwt-impl-0.10.7.jar
  G:/Epicc Games/MultiMC/libraries/io/jsonwebtoken/jjwt-orgjson/0.10.7/jjwt-orgjson-0.10.7.jar
  G:/Epicc Games/MultiMC/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar
  G:/Epicc Games/MultiMC/libraries/com/github/ImpactDevelopment/Installer/0.8.5/Installer-0.8.5.jar
  G:/Epicc Games/MultiMC/libraries/club/minnced/java-discord-rpc/2.0.1/java-discord-rpc-2.0.1.jar
  G:/Epicc Games/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  G:/Epicc Games/MultiMC/libraries/org/json/json/20190722/json-20190722.jar
  G:/Epicc Games/MultiMC/libraries/club/minnced/discord-rpc-release/v3.3.0/discord-rpc-release-v3.3.0.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  G:/Epicc Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  G:/Epicc Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir G:/Epicc Games/MultiMC/instances/Impact-4.9-1.16.5/.minecraft --assetsDir G:/Epicc Games/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --tweakClass clientapi.load.ClientTweaker --tweakClass baritone.launch.BaritoneTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 8916


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
```

**Comment by Civitello** [comment]
Try:
Edit Instance > Settings > Java > Check Java Installation > Auto-detect... > Ensure that the correct Java version is selected for the version of Minecraft that you are running.
