### ISSUE TITLE
Using a mod tool to use the Baritone Autominer crashes the game.

### ISSUE THREAD

**Issue by Shigetorum635** [ImpactDevelopment/ImpactIssues#3273]
**Describe the bug**
When you try to mine with a tool that is not from @minecraft it will crash the game.

**To Reproduce**
1. Download IndustrialCraft mod
2. Start Autominer with tin pickaxe
3. Crash

**Expected behavior**
To begin auto-mining

<details> 
  <summary><strong>
  
  
  </strong></summary>
 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  GTCELoadingPlugin (gregtech-1.12.2-1.17.0.764.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 9/3/21 1:52 PM
Description: Ticking entity

java.lang.IllegalArgumentException: No enum constant net.minecraft.item.Item.ToolMaterial.TIN
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.minecraft.item.Item$ToolMaterial.valueOf(Item.java:1769)
	at baritone.fz.a(Unknown Source)
	at baritone.fz.a(Unknown Source)
	at baritone.fz.a(Unknown Source)
	at baritone.fz$$Lambda$4023/441270248.apply(Unknown Source)
	at java.util.function.Function.lambda$compose$5(Function.java:68)
	at java.util.function.Function$$Lambda$4024/1384953505.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at baritone.fz.a(Unknown Source)
	at baritone.cl.a(Unknown Source)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.b(Unknown Source)
	at baritone.fc$$Lambda$4028/1798129059.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.mine(Unknown Source)
	at baritone.fc.mineByName(Unknown Source)
	at baritone.api.process.IMineProcess.mineByName(Unknown Source)
	at net.impactclient.87.0(87.java:68)
	at net.impactclient.87$$Lambda$3473/913727012.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$3243/2135341098.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.1X.post(1X.java:2)
	at net.minecraft.client.entity.EntityPlayerSP.handler$onPostUpdate$zzd000(EntityPlayerSP.java:1317)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:199)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.minecraft.item.Item$ToolMaterial.valueOf(Item.java:1769)
	at baritone.fz.a(Unknown Source)
	at baritone.fz.a(Unknown Source)
	at baritone.fz.a(Unknown Source)
	at baritone.fz$$Lambda$4023/441270248.apply(Unknown Source)
	at java.util.function.Function.lambda$compose$5(Function.java:68)
	at java.util.function.Function$$Lambda$4024/1384953505.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at baritone.fz.a(Unknown Source)
	at baritone.cl.a(Unknown Source)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.b(Unknown Source)
	at baritone.fc$$Lambda$4028/1798129059.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.a(Unknown Source)
	at baritone.fc.mine(Unknown Source)
	at baritone.fc.mineByName(Unknown Source)
	at baritone.api.process.IMineProcess.mineByName(Unknown Source)
	at net.impactclient.87.0(87.java:68)
	at net.impactclient.87$$Lambda$3473/913727012.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$3243/2135341098.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.1X.post(1X.java:2)
	at net.minecraft.client.entity.EntityPlayerSP.handler$onPostUpdate$zzd000(EntityPlayerSP.java:1317)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:199)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 336988
	Entity Name: Shigetorum
	Entity's Exact location: 507.58, 22.00, 258.56
	Entity's Block location: World: (507,22,258), Chunk: (at 11,1,2 in 31,16; contains blocks 496,0,256 to 511,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Shigetorum'/336988, l='MpServer', x=507.58, y=22.00, z=258.56]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (184,64,256), Chunk: (at 8,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 498388 game time, 520814 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 9 total; [EntityPlayerSP['Shigetorum'/336988, l='MpServer', x=507.58, y=22.00, z=258.56], EntityItem['item.item.srparasites.assimilated_flesh'/336996, l='MpServer', x=457.70, y=69.00, z=321.61], EntityInfHuman['Assimilated Human'/336993, l='MpServer', x=491.22, y=18.00, z=301.50], EntityInfHuman['Assimilated Human'/336992, l='MpServer', x=486.44, y=17.00, z=300.18], EntityInfSheep['Assimilated Sheep'/336994, l='MpServer', x=486.34, y=17.00, z=293.42], EntityInfHuman['Assimilated Human'/336974, l='MpServer', x=489.56, y=18.00, z=301.50], EntityBoat['Boat'/336629, l='MpServer', x=472.80, y=97.00, z=262.15], EntityInhooM['Incomplete Form'/337009, l='MpServer', x=481.59, y=76.00, z=311.17], EntityRayleigh['Rayleigh'/336991, l='MpServer', x=509.23, y=78.00, z=287.70]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3002265456 bytes (2863 MB) / 5268045824 bytes (5024 MB) up to 5268045824 bytes (5024 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx5000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version                            | Source                                         | Signature                                |
	|:------ |:-------------------------- |:---------------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2                             | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                        | 9.42                               | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                        | 8.0.99.99                          | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2855                       | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | securitycraft              | v1.8.23.1                          | [1.12.2]+SecurityCraft+v1.8.23.1.jar           | None                                     |
	| LCHIJA | baubles                    | 1.5.2                              | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | bibliotheca                | 1.3.6-1.12.2                       | bibliotheca-1.3.6-1.12.2.jar                   | None                                     |
	| LCHIJA | jei                        | 4.16.1.302                         | jei_1.12.2-4.16.1.302.jar                      | None                                     |
	| LCHIJA | botania                    | r1.10-364                          | Botania+r1.10-364.4.jar                        | None                                     |
	| LCHIJA | castle_dungeons            | 1.3                                | castle_dungeons-2.2-1.12.2-forge.jar           | None                                     |
	| LCHIJA | codechickenlib             | 3.2.3.358                          | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux               | 2.1.1                              | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCHIJA | cofhcore                   | 4.6.6                              | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCHIJA | cofhworld                  | 1.4.0                              | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCHIJA | elevatorid                 | 1.3.14                             | ElevatorMod-1.12.2-1.3.14.jar                  | None                                     |
	| LCHIJA | enderstorage               | 2.4.6.137                          | EnderStorage-1.12.2-2.4.6.137-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | gregtech                   | 1.17.0.764                         | gregtech-1.12.2-1.17.0.764.jar                 | None                                     |
	| LCHIJA | hammertime                 | 2.2.0                              | Hammer Time-2.2.0-1.12.2.jar                   | None                                     |
	| LCHIJA | waila                      | 1.8.26                             | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | ic2                        | 2.8.221-ex112                      | industrialcraft-2-2.8.221-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | journeymap                 | 1.12.2-5.7.1                       | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCHIJA | mantle                     | 1.12-1.3.3.55                      | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCHIJA | minejurassic               | 1.2.1 - The Secret of InGen Update | MineJurassic-1.2.1-1.12.2.jar                  | None                                     |
	| LCHIJA | neat                       | 1.4-17                             | Neat 1.4-17.jar                                | None                                     |
	| LCHIJA | onepiececraft              | 2.4.3                              | onepiececraft-2.4.3.jar                        | None                                     |
	| LCHIJA | patchouli                  | 1.0-23.6                           | Patchouli-1.0-23.6.jar                         | None                                     |
	| LCHIJA | radixcore                  | 1.12.x-2.2.1                       | RadixCore-1.12.x-2.2.1-universal.jar           | None                                     |
	| LCHIJA | rustic                     | 1.1.7                              | rustic-1.1.7.jar                               | None                                     |
	| LCHIJA | silentlib                  | 3.0.13                             | SilentLib-1.12.2-3.0.14+168.jar                | None                                     |
	| LCHIJA | scalinghealth              | 1.3.37                             | ScalingHealth-1.12.2-1.3.42+147.jar            | None                                     |
	| LCHIJA | srparasites                | 1.9.0                              | SRParasites-1.12.2v1.9.0ALPHA18.jar            | None                                     |
	| LCHIJA | tconstruct                 | 1.12.2-2.13.0.183                  | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCHIJA | thermalfoundation          | 2.6.7                              | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCHIJA | thermalexpansion           | 5.5.7                              | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4                                | tlskincape1.12.2-1.4.jar                       | None                                     |
	| LCHIJA | tombstone                  | 4.4.7                              | tombstone-1.12.2-4.4.7.jar                     | None                                     |
	| LCHIJA | travelersbackpack          | 1.0.35                             | TravelersBackpack-1.12.2-1.0.35.jar            | None                                     |
	| LCHIJA | waystones                  | 4.1.0                              | Waystones_1.12.2-4.1.0.jar                     | None                                     |
	| LCHIJA | llibrary                   | 1.7.20                             | llibrary-1.7.20-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
GTCELoadingPlugin (gregtech-1.12.2-1.17.0.764.jar)
  gregtech.common.asm.GTCETransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.68' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Launched Version: Server Richard Y Compania
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.68, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 471.68
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9.1 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Light, Norender, XRay Automining
- Operating System: Windows 64 Bits

</details>

**Additional context**

**Comment by Shigetorum635** [comment]
Bumping
