### ISSUE TITLE
Not working on 1.12.2 Forge OR Regular Minecraft Launcher

### ISSUE THREAD

**Issue by RaptorWasTaken** [ImpactDevelopment/ImpactIssues#3315]
**Describe the bug**

**To Reproduce**
1. Download 4.9.1, for 1.12.2
2. Try to use it
3. See it doesnt work
4. see the error and see if matches

**Expected behavior**
I expect the game to run, and the client to run

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: No OpenGL context found in the current thread.
Exit Code: -1
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// My bad.

Time: 11/7/21 9:20 PM
Description: Initializing game

java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:1403)
	at net.minecraft.client.renderer.GlStateManager.func_179146_y(GlStateManager.java:569)
	at net.impactclient.5A.<init>(5A.java:26)
	at net.impactclient.74.0(74.java:1)
	at net.impactclient.5J.<init>(5J.java:17)
	at net.impactclient.62.0(62.java:6)
	at net.impactclient.62.0(62.java:13)
	at net.impactclient.0ay.2(0ay.java:20)
	at net.impactclient.4t.0(4t.java:5)
	at net.minecraft.client.Minecraft.handler$init$zzl000(Minecraft.java:3332)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:570)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:1403)
	at net.minecraft.client.renderer.GlStateManager.func_179146_y(GlStateManager.java:569)
	at net.impactclient.5A.<init>(5A.java:26)
	at net.impactclient.74.0(74.java:1)
	at net.impactclient.5J.<init>(5J.java:17)
	at net.impactclient.62.0(62.java:6)
	at net.impactclient.62.0(62.java:13)
	at net.impactclient.0ay.2(0ay.java:20)
	at net.impactclient.4t.0(4t.java:5)
	at net.minecraft.client.Minecraft.handler$init$zzl000(Minecraft.java:3332)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:570)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 368436752 bytes (351 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 64
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
  It is simply not runnnig at all, no matter what i try, normal launcher or forge. I am not using lite loader, and im running windows 10 64bit. Putting hear because not showing up above.

**Comment by AghoyPandaaa** [comment]
Do you have Premium Launcher?
impact doesnt support non premium launchers anymore

**Comment by RaptorWasTaken** [comment]
Yeah, this is a stock launcher, with the purchased game for over 8 years now.
