### ISSUE TITLE
Java not working when i try to run Impact Installer. (Java 11)

### ISSUE THREAD

**Issue by Iwo24pl** [ImpactDevelopment/ImpactIssues#3394]
When i try to run command: java -jar ImpactInstaller-0.9.5.jar
i get this:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-11.0.14.1.1-5.fc35.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at com.brsanthu.googleanalytics.discovery.AwtRequestParameterDiscoverer.discoverParameters(Unknown Source)
	at com.brsanthu.googleanalytics.GoogleAnalyticsBuilder.build(Unknown Source)
	at io.github.ImpactDevelopment.installer.utils.Tracky.analytics(Unknown Source)
	at io.github.ImpactDevelopment.installer.utils.Tracky.awtEnabled(Unknown Source)
	at io.github.ImpactDevelopment.installer.Installer.main(Unknown Source)
Can someone help me?

**Comment by Iwo24pl** [comment]
Ok i used java 1.8.0 and its working.
