### ISSUE TITLE
Impact crashes when I try to launch it on Multimc.

### ISSUE THREAD

**Issue by tyfg6yugt** [ImpactDevelopment/ImpactIssues#3405]
**Describe the bug**
When I try to launch it, it gives me weird errors and process exited code -1

**To Reproduce**
1. Install impact in multimc folder.
2. Click on impact instance.
3.  Wait for it to launch.
4. See error and become frustrated.

**Expected behavior**
Starting up normally without errors.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: < "4.9.1 for 1.12.2" -->
- Using Optifine? <No>
- Using LiteLoader? <No>
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by Excaliburn123455678889900** [comment]
Just use impact on normal one

**Comment by SergioFLS** [comment]
It seems like this affects later Java versions? I tried with Java 16 and I got the same crash, but using Java 8 works just fine...

**Comment by yemix** [comment]
just go to instance settings and enter your java 8 path.
Try enter this.
C:\Program Files\Java\jre1.8.0_351\bin\javaw.exe
