### ISSUE TITLE
Game disconnect issue

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactIssues#658]
### What happens?

![NullPointerException](https://i.gyazo.com/87120c5730099a54adda7d881b515a6e.png)

I get the above error every time I try to join and play a game on mineplex. Also happens when I try to join `play.gotpvp.com` server.

### Exact steps to reproduce?

- Join mineplex
- Join a game
- after game starts move for a bit and interact

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.3
- Using Optifine? No
- Enabled mods:
  ![](https://i.gyazo.com/5f9724b114459536d35a30ed8d2c070c.png)
- Operating System: Windows 10 64bit

</details>

**Comment by CollierPlays** [comment]
I'm having the same issue. i hope they can fix it.
Same specs too.

**Comment by Pabsb** [comment]
Update: Still happens with no Modules enabled

**Comment by zeroeightysix** [comment]
This happens universally, outside of impact and in vanilla as well. It is not an impact issue.

**Comment by 0-x-2-2** [comment]
This happens when there is a exception when receiving or sending packets without logs the info here is useless and generic.

**Comment by ZeroMemes** [comment]
I've added a Mixin to Impact 4.4 which will print the stack-trace to console when this happens.

**Comment by ThaUnknown** [comment]
Impact 4.8.3 for 1.14.4 joining a 1.8+ server
[13:56:34] [main/INFO]: Connecting to play.cubecraft.net, 25565
[13:56:34] [main/WARN]: Unknown custom packed identifier: minecraft:register
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: java.lang.NullPointerException
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at dkc.handler$preChunkUnload$zeg000(SourceFile)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at dkc.a(SourceFile)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at lk.a(SourceFile:35)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at lk.a(SourceFile:8)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at jc.redirect$channelRead0$processPacket$zbd000(SourceFile:517)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at jc.a(SourceFile:148)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at jc.channelRead0(SourceFile:53)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:34] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at jc.b(SourceFile:193)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at jc.redirect$sendPacket$dispatchPacket$zbd000(SourceFile:527)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at jc.a(SourceFile:173)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at jc.exceptionCaught(SourceFile:135)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: Caused by: java.io.IOException: Can't serialize unregistered packet
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at jg.a(SourceFile:39)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at jg.encode(SourceFile:15)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:56:35] [Netty Client IO #8/INFO]: [STDERR]: 	... 52 more

**Comment by LeafHacker** [comment]
Not sure it's worth keeping this open since it doesn't cover a specific issue. Now that stacktraces are printed to latest.log we should probably be opening separate issues for each stacktrace.
