### ISSUE TITLE
cant run impact

### ISSUE THREAD

**Issue by ichabodphage** [ImpactDevelopment/ImpactIssues#673]
when i try i get this error Error: java.lang.RuntimeException: No OpenGL context found in the current thread.

**Comment by ZeroMemes** [comment]
Provided information from Discord:

<details> 
  <summary><strong>Crash report</strong></summary>

```
--- Minecraft Crash Report ----
// My bad.

Time: 8/2/18 10:22 PM
Description: Initializing game

java.lang.RuntimeException: No OpenGL context found in the current thread.
    at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
    at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:1403)
    at bus.A(SourceFile:482)
    at me.zero.clarinet.bM.<init>(bM.java)
    at me.zero.clarinet.aa.a(aa.java)
    at me.zero.clarinet.aa.a(aa.java)
    at me.zero.clarinet.dc.a(dc.java)
    at me.zero.clarinet.dc.<init>(dc.java)
    at me.zero.clarinet.dc.<init>(dc.java)
    at me.zero.clarinet.cC.a(cC.java)
    at me.zero.clarinet.cC.r(cC.java)
    at me.zero.clarinet.Impact.a(Impact.java)
    at me.zero.clarinet.Impact.onInit(Impact.java)
    at bib.handler$init$zzp000(SourceFile:3258)
    at bib.aq(SourceFile:583)
    at bib.a(SourceFile:404)
at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>

- Impact Version: 4.3

</details>

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
